//--------------------------------------------------------------------------------------------------
// Copyright (c) 2026                   orgrinrt                 ort@hiisi.digital
// SPDX-License-Identifier: MPL-2.0     https://mozilla.org/MPL/2.0        contact@hiisi.digital
//--------------------------------------------------------------------------------------------------

use super::*;

/// Platform-specific hook helpers injected into {{HOOK_HELPERS}} for Claude.
///
/// - _extract: reads fields from tool_input (Claude's input format)
/// - deny: outputs hookSpecificOutput JSON wrapper with deny decision
/// - context: outputs hookSpecificOutput JSON wrapper with additionalContext
pub(crate) const CLAUDE_HOOK_HELPERS: &str = r##"# --- Platform helpers (Claude): generated by xtask ---
_extract() {
    echo "$__INPUT" | jq -r ".tool_input.$1 // \"\"" 2>/dev/null || echo ""
}

allow() {
    printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse"}}\n'
    exit 0
}

deny() {
    printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' "$1"
    exit 0
}

context() {
    printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","additionalContext":"%s"}}\n' "$1"
}

# Absolute path of the repo this hook belongs to; baked at generation time.
readonly __HOOK_REPO_ROOT="{{REPO_ROOT}}"

# Exit with `allow` if the current tool invocation doesn't target this repo.
# Reads FILE_PATH and COMMAND from the environment (callers must set them
# first via _extract). A tool call targets this repo if:
#   * FILE_PATH is under __HOOK_REPO_ROOT (absolute path match), OR
#   * COMMAND mentions __HOOK_REPO_ROOT by absolute path, OR
#   * The process cwd is __HOOK_REPO_ROOT or a descendant (relative-path
#     shell commands like `git mv mock/foo bar` count via cwd).
_scope_or_allow() {
    if [[ -n "$FILE_PATH" ]]; then
        case "$FILE_PATH" in
            "$__HOOK_REPO_ROOT"/*) return 0 ;;
            *) allow ;;
        esac
    fi
    if [[ -n "$COMMAND" ]]; then
        if echo "$COMMAND" | grep -qF "$__HOOK_REPO_ROOT"; then
            return 0
        fi
        case "$(pwd)" in
            "$__HOOK_REPO_ROOT"|"$__HOOK_REPO_ROOT"/*) return 0 ;;
        esac
        allow
    fi
    allow
}
# --- End platform helpers ---"##;

/// Platform-specific hook helpers injected into {{HOOK_HELPERS}} for Copilot.
///
/// - _extract: reads fields from toolArgs (Copilot's stringified JSON format)
/// - deny: outputs flat JSON deny decision
/// - context: outputs plain text (non-blocking)
pub(crate) const COPILOT_HOOK_HELPERS: &str = r##"# --- Platform helpers (Copilot): generated by xtask ---
_extract() {
    echo "$__INPUT" | jq -r "if .toolArgs then (.toolArgs | fromjson? | .$1 // \"\") else \"\" end" 2>/dev/null || echo ""
}

allow() {
    exit 0
}

deny() {
    printf '{"permissionDecision":"deny","permissionDecisionReason":"%s"}\n' "$1"
    exit 0
}

context() {
    printf '%s\n' "$1"
}

# Absolute path of the repo this hook belongs to; baked at generation time.
readonly __HOOK_REPO_ROOT="{{REPO_ROOT}}"

# Exit with `allow` if the current tool invocation doesn't target this repo.
# Mirrors the Claude variant; see that one for detailed semantics.
_scope_or_allow() {
    if [[ -n "$FILE_PATH" ]]; then
        case "$FILE_PATH" in
            "$__HOOK_REPO_ROOT"/*) return 0 ;;
            *) allow ;;
        esac
    fi
    if [[ -n "$COMMAND" ]]; then
        if echo "$COMMAND" | grep -qF "$__HOOK_REPO_ROOT"; then
            return 0
        fi
        case "$(pwd)" in
            "$__HOOK_REPO_ROOT"|"$__HOOK_REPO_ROOT"/*) return 0 ;;
        esac
        allow
    fi
    allow
}
# --- End platform helpers ---"##;

/// Set the executable bit on a file.
#[cfg(unix)]
pub(crate) fn set_executable(path: &Path) {
    if let Ok(meta) = fs::metadata(path) {
        let mut perms = meta.permissions();
        perms.set_mode(0o755);
        let _ = fs::set_permissions(path, perms);
    }
}

// ---------------------------------------------------------------------------
// Hook metadata for settings generation (Phase 7)
// ---------------------------------------------------------------------------

/// Metadata collected from each hook for settings generation.
pub(crate) struct HookMeta {
    /// Output file name (e.g. "check-message.sh").
    pub(crate) name:     String,
    /// Tool matchers this hook should fire on (e.g. ["Bash", "Write", "Edit"]).
    pub(crate) matchers: Vec<String>,
}

/// Derive tool matchers from a hook file name using naming conventions.
pub(crate) fn matchers_from_name(name: &str) -> Vec<String> {
    if name.ends_with("-guard.sh") {
        vec!["Bash".into(), "Write".into(), "Edit".into()]
    } else if name.ends_with("-reminder.sh") {
        vec!["Bash".into()]
    } else if name.starts_with("check-") {
        // Every tool, not just Bash. A git-commit or pull-request MCP tool is
        // not Bash, and scoping these to Bash is precisely why authored-message
        // violations went unnoticed once such tools existed. The hook decides
        // relevance itself, from the tool name and the whole input.
        vec!["*".into()]
    } else {
        vec!["Bash".into()]
    }
}

/// Parse `# @matchers:` frontmatter from the first 5 lines of a hook template.
pub(crate) fn parse_hook_matchers(template: &str) -> Option<Vec<String>> {
    for line in template.lines().take(5) {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("# @matchers:") {
            let matchers: Vec<String> = rest
                .split(',')
                .map(|s| s.trim().to_string())
                .filter(|s| !s.is_empty())
                .collect();
            if !matchers.is_empty() {
                return Some(matchers);
            }
        }
    }
    None
}

// ---------------------------------------------------------------------------
// Phase 6: Builtin agent hooks
// ---------------------------------------------------------------------------

/// Derive the agent mode env var name from a project name.
///
/// e.g. "widget" -> "WIDGET_AGENT_MODE", "two-words" -> "TWO_WORDS_AGENT_MODE"
pub(crate) fn agent_mode_var(project_name: &str) -> String {
    let upper = project_name.to_uppercase().replace('-', "_");
    format!("{upper}_AGENT_MODE")
}
