//! `ClaudePlatform` — output paths and helpers for Anthropic Claude Code.

use std::path::{Path, PathBuf};

use crate::platform::{HookDecl, Platform};

const CLAUDE_HOOK_HELPERS: &str = r##"# --- Platform helpers (Claude) — generated by mockspace-template ---
_extract() {
    echo "$__INPUT" | jq -r ".tool_input.$1 // \"\"" 2>/dev/null || echo ""
}

allow() {
    printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse"}}\n'
    exit 0
}

deny() {
    printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' "$1"
    exit 0
}

context() {
    printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","additionalContext":"%s"}}\n' "$1"
}

# Absolute path of the repo this hook belongs to; baked at generation time.
readonly __HOOK_REPO_ROOT="{{REPO_ROOT}}"

# Exit with `allow` if the current tool invocation doesn't target this repo.
# Reads FILE_PATH and COMMAND from the environment (callers must set them
# first via _extract). A tool call targets this repo if:
#   * FILE_PATH is under __HOOK_REPO_ROOT (absolute path match), OR
#   * COMMAND mentions __HOOK_REPO_ROOT by absolute path, OR
#   * The process cwd is __HOOK_REPO_ROOT or a descendant (relative-path
#     shell commands like `git mv mock/foo bar` count via cwd).
_scope_or_allow() {
    if [[ -n "$FILE_PATH" ]]; then
        case "$FILE_PATH" in
            "$__HOOK_REPO_ROOT"/*) return 0 ;;
            *) allow ;;
        esac
    fi
    if [[ -n "$COMMAND" ]]; then
        if echo "$COMMAND" | grep -qF "$__HOOK_REPO_ROOT"; then
            return 0
        fi
        case "$(pwd)" in
            "$__HOOK_REPO_ROOT"|"$__HOOK_REPO_ROOT"/*) return 0 ;;
        esac
        allow
    fi
    allow
}
# --- End platform helpers ---"##;

/// Claude Code platform: writes under `.claude/` with `paths:` frontmatter
/// and `hookSpecificOutput`-shaped JSON for hooks.
pub struct ClaudePlatform;

impl Platform for ClaudePlatform {
    fn name(&self) -> &'static str {
        "claude"
    }

    fn output_path(&self, repo_root: &Path, logical: &str) -> PathBuf {
        let claude = repo_root.join(".claude");
        if let Some(rest) = logical.strip_prefix("rules/") {
            return claude.join("rules").join(format!("{rest}.md"));
        }
        if let Some(rest) = logical.strip_prefix("skills/") {
            return claude.join("skills").join(rest).join("SKILL.md");
        }
        if let Some(rest) = logical.strip_prefix("hooks/") {
            return claude.join("hooks").join(format!("{rest}.sh"));
        }
        if let Some(rest) = logical.strip_prefix("agents/") {
            return claude.join("agents").join(format!("{rest}.md"));
        }
        if logical == "instructions" {
            return claude.join("CLAUDE.md");
        }
        if logical == "settings" {
            return claude.join("settings.json");
        }
        claude.join(format!("{logical}.md"))
    }

    fn frontmatter(&self, applies_to: &[&str]) -> String {
        let mut s = String::from("---\npaths:\n");
        for p in applies_to {
            s.push_str(&format!("  - \"{p}\"\n"));
        }
        s.push_str("---\n");
        s
    }

    fn hook_helpers(&self, repo_root: &Path) -> String {
        CLAUDE_HOOK_HELPERS.replace("{{REPO_ROOT}}", &repo_root.display().to_string())
    }

    fn settings_file(
        &self,
        repo_root: &Path,
        hooks: &[HookDecl],
    ) -> Option<(PathBuf, String)> {
        if hooks.is_empty() {
            return None;
        }
        let path = repo_root.join(".claude/settings.json");
        Some((path, build_claude_settings_json(hooks)))
    }
}

fn build_claude_settings_json(hooks: &[HookDecl]) -> String {
    // Group hooks by event name; each event maps to an array of {matcher, hooks: [{type, command}]}.
    use std::collections::BTreeMap;
    let mut by_event: BTreeMap<&str, Vec<&HookDecl>> = BTreeMap::new();
    for h in hooks {
        by_event.entry(h.event.as_str()).or_default().push(h);
    }
    let mut s = String::from("{\n  \"hooks\": {\n");
    let n_events = by_event.len();
    for (i, (event, hooks_for_event)) in by_event.iter().enumerate() {
        s.push_str(&format!("    \"{event}\": [\n"));
        let n_h = hooks_for_event.len();
        for (j, h) in hooks_for_event.iter().enumerate() {
            s.push_str("      {\n");
            s.push_str(&format!("        \"matcher\": \"{}\",\n", json_escape(&h.matcher)));
            s.push_str("        \"hooks\": [\n");
            s.push_str("          {\n");
            s.push_str("            \"type\": \"command\",\n");
            s.push_str(&format!("            \"command\": \"{}\"\n", json_escape(&h.command)));
            s.push_str("          }\n");
            s.push_str("        ]\n");
            if j + 1 < n_h {
                s.push_str("      },\n");
            } else {
                s.push_str("      }\n");
            }
        }
        if i + 1 < n_events {
            s.push_str("    ],\n");
        } else {
            s.push_str("    ]\n");
        }
    }
    s.push_str("  }\n}\n");
    s
}

fn json_escape(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for c in input.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}
