//! `CopilotPlatform` — output paths and helpers for GitHub Copilot CLI.

use std::path::{Path, PathBuf};

use crate::platform::{HookDecl, Platform};

const COPILOT_HOOK_HELPERS: &str = r##"# --- Platform helpers (Copilot) — generated by mockspace-template ---
_extract() {
    echo "$__INPUT" | jq -r "if .toolArgs then (.toolArgs | fromjson? | .$1 // \"\") else \"\" end" 2>/dev/null || echo ""
}

allow() {
    exit 0
}

deny() {
    printf '{"permissionDecision":"deny","permissionDecisionReason":"%s"}\n' "$1"
    exit 0
}

context() {
    printf '%s\n' "$1"
}

# Absolute path of the repo this hook belongs to; baked at generation time.
readonly __HOOK_REPO_ROOT="{{REPO_ROOT}}"

# Exit with `allow` if the current tool invocation doesn't target this repo.
# Mirrors the Claude variant; see that one for detailed semantics.
_scope_or_allow() {
    if [[ -n "$FILE_PATH" ]]; then
        case "$FILE_PATH" in
            "$__HOOK_REPO_ROOT"/*) return 0 ;;
            *) allow ;;
        esac
    fi
    if [[ -n "$COMMAND" ]]; then
        if echo "$COMMAND" | grep -qF "$__HOOK_REPO_ROOT"; then
            return 0
        fi
        case "$(pwd)" in
            "$__HOOK_REPO_ROOT"|"$__HOOK_REPO_ROOT"/*) return 0 ;;
        esac
        allow
    fi
    allow
}
# --- End platform helpers ---"##;

/// GitHub Copilot CLI platform: writes under `.github/` with `applyTo:`
/// frontmatter and flat-JSON hook decisions.
pub struct CopilotPlatform;

impl Platform for CopilotPlatform {
    fn name(&self) -> &'static str {
        "copilot"
    }

    fn output_path(&self, repo_root: &Path, logical: &str) -> PathBuf {
        let gh = repo_root.join(".github");
        if let Some(rest) = logical.strip_prefix("rules/") {
            return gh.join("instructions").join(format!("{rest}.instructions.md"));
        }
        if let Some(rest) = logical.strip_prefix("skills/") {
            return gh.join("skills").join(rest).join("SKILL.md");
        }
        if let Some(rest) = logical.strip_prefix("hooks/") {
            return gh.join("hooks").join(format!("{rest}.sh"));
        }
        if let Some(rest) = logical.strip_prefix("agents/") {
            // No native Copilot equivalent; keep under .github/agents/
            return gh.join("agents").join(format!("{rest}.md"));
        }
        if logical == "instructions" {
            return gh.join("copilot-instructions.md");
        }
        if logical == "settings" {
            return gh.join("copilot").join("hooks.json");
        }
        gh.join(format!("{logical}.md"))
    }

    fn frontmatter(&self, applies_to: &[&str]) -> String {
        let joined = applies_to.join(",");
        format!("---\napplyTo: \"{joined}\"\n---\n")
    }

    fn hook_helpers(&self, repo_root: &Path) -> String {
        COPILOT_HOOK_HELPERS.replace("{{REPO_ROOT}}", &repo_root.display().to_string())
    }

    fn settings_file(
        &self,
        repo_root: &Path,
        hooks: &[HookDecl],
    ) -> Option<(PathBuf, String)> {
        if hooks.is_empty() {
            return None;
        }
        let path = repo_root.join(".github/copilot/hooks.json");
        Some((path, build_copilot_settings_json(hooks)))
    }
}

fn build_copilot_settings_json(hooks: &[HookDecl]) -> String {
    // Copilot expects a flat array of hook objects.
    let mut s = String::from("{\n  \"hooks\": [\n");
    let n = hooks.len();
    for (i, h) in hooks.iter().enumerate() {
        s.push_str("    {\n");
        s.push_str(&format!("      \"event\": \"{}\",\n", json_escape(&h.event)));
        s.push_str(&format!("      \"matcher\": \"{}\",\n", json_escape(&h.matcher)));
        s.push_str(&format!("      \"command\": \"{}\"\n", json_escape(&h.command)));
        if i + 1 < n {
            s.push_str("    },\n");
        } else {
            s.push_str("    }\n");
        }
    }
    s.push_str("  ]\n}\n");
    s
}

fn json_escape(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for c in input.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}
