//--------------------------------------------------------------------------------------------------
// Copyright (c) 2026                   orgrinrt                 ort@hiisi.digital
// SPDX-License-Identifier: MPL-2.0     https://mozilla.org/MPL/2.0        contact@hiisi.digital
//--------------------------------------------------------------------------------------------------

//! The consumer hooks: every named extension point the driver runs,
//! and the only places consumer code executes inside the drive loop.
//!
//! Hooks are fields of [`Hooks`], so the set is closed and
//! harness-ordered: a consumer cannot invent a hook (an unknown field
//! is a compile error listing the fields that exist) and cannot run
//! one at the wrong moment (the driver owns the sequence). The
//! ordering, with what is guaranteed before each:
//!
//! 1. `on_init`: the manifest is loaded and validated. Nothing else
//!    has happened: no selection, no cell resolution, no preflight,
//!    no staging. May abort the run.
//! 2. `after_init`: every cell is resolved, the preflight passed, and
//!    the staging root exists. Nothing has been measured.
//! 3. `routine_for`: per cell, consulted before the generated byte
//!    dispatch. This is where `routine_table!` plugs in.
//! 4. `after_cell`: per cell, after the cell's samples, meta and
//!    report are written into its staged output directory and the
//!    validation drops are final. Staging is not yet promoted, and a
//!    `Fail` verdict withholds the cell's history append outright,
//!    so a gated-out run cannot become the next run's regression
//!    baseline. The staged artifacts still promote: they are the
//!    evidence of what ran and why it was failed.
//!
//! `routine_for` and `after_cell` have callers today (a custom
//! routine table; a post-cell disassembly gate with an exit-code
//! policy). `on_init` and `after_init` have none and exist so the
//! lifecycle is visible and complete from day one rather than grown
//! piecemeal; they are the maintainer's call, recorded as such.

use std::path::{Path, PathBuf};

use crate::config::BenchConfig;
use crate::sample::BenchResult;
use crate::spec::RoutineSpec;

/// The consumer extension points, in the order the driver runs them.
///
/// Construct with struct-update syntax so adding a hook later is not
/// a breaking change for consumers that set only some:
///
/// ```ignore
/// Hooks { routine_for: Some(my_table), ..Hooks::default() }
/// ```
#[derive(Clone, Copy, Default)]
pub struct Hooks {
    /// Runs once, right after the manifest is loaded and validated
    /// and before anything is resolved or built upon it. May abort.
    ///
    /// No consumer needed this at the time it was added; it exists
    /// for lifecycle completeness.
    pub on_init:     Option<fn(&InitContext<'_>) -> InitVerdict>,
    /// Runs once, after every cell is resolved, the preflight has
    /// passed and the staging root exists; before the first cell.
    ///
    /// No consumer needed this at the time it was added; it exists
    /// for lifecycle completeness.
    pub after_init:  Option<fn(&RunPlan<'_>)>,
    /// Serves a custom routine for a cell whose input is not plain
    /// bytes. `None` falls through to the generated byte dispatch.
    /// Build one declaratively with [`crate::routine_table!`].
    pub routine_for: Option<fn(&BenchConfig) -> Option<RoutineSpec>>,
    /// Runs after each cell's artifacts are staged. The verdict
    /// feeds the process exit code after promotion.
    pub after_cell:  Option<fn(&AfterCell<'_>) -> CellVerdict>,
}

/// What `on_init` sees: the manifest as loaded, before the driver
/// acts on it.
pub struct InitContext<'a> {
    /// The loaded, validated manifest (flat or composed from a
    /// nested tree).
    pub manifest:    &'a crate::config::BenchManifest,
    /// The bench names requested on the command line; empty means
    /// everything.
    pub requested:   &'a [String],
    /// Whether this run only regenerates reports from cached
    /// samples.
    pub report_only: bool,
}

/// `on_init`'s answer.
pub enum InitVerdict {
    /// Continue the run.
    Proceed,
    /// Stop before anything is resolved or measured. The reason is
    /// printed and the process exits with failure.
    Abort(String),
}

/// What `after_init` sees: the resolved plan, immediately before the
/// first cell runs.
pub struct RunPlan<'a> {
    /// Every cell that will run, in run order.
    pub cells:        &'a [BenchConfig],
    /// Whether this run only regenerates reports.
    pub report_only:  bool,
    /// The promoted results root (`results/` under the bench tree).
    /// During a measuring run the cells write to a staging tree that
    /// promotes here on orderly completion.
    pub results_root: &'a Path,
}

/// What `after_cell` sees: one finished cell, staged but not yet
/// promoted.
pub struct AfterCell<'a> {
    /// The cell's config: bench, sweep, point, flags, resolved seed.
    pub config:    &'a BenchConfig,
    /// The samples the cell just collected.
    pub result:    &'a BenchResult,
    /// The arm cdylibs that were measured: the validation survivors,
    /// not the declared list.
    pub arm_paths: &'a [PathBuf],
    /// The arms validation dropped before timing.
    pub dropped:   &'a [String],
    /// The cell's staged output directory. The samples, meta and
    /// report are already in it; anything the hook writes here is
    /// promoted with them.
    pub out_dir:   &'a Path,
}

/// `after_cell`'s answer.
pub enum CellVerdict {
    /// Nothing to report.
    Pass,
    /// Recorded in the run output; does not fail the run.
    Note(String),
    /// Recorded, and fails the process exit code once every cell has
    /// run and the staged results are promoted.
    Fail(String),
}

/// Run `on_init` if declared. Returns the abort reason when the hook
/// vetoes the run.
pub(super) fn run_on_init(hooks: &Hooks, ctx: &InitContext<'_>) -> Result<(), String> {
    match hooks.on_init.map(|h| h(ctx)) {
        None | Some(InitVerdict::Proceed) => Ok(()),
        Some(InitVerdict::Abort(reason)) => Err(reason),
    }
}

/// Run `after_init` if declared.
pub(super) fn run_after_init(hooks: &Hooks, plan: &RunPlan<'_>) {
    if let Some(h) = hooks.after_init {
        h(plan);
    }
}

/// Run `after_cell` if declared, printing its verdict. Returns
/// whether the cell failed, which the driver folds into the exit
/// code and uses to withhold the cell's history append.
#[must_use]
pub(super) fn run_after_cell(hooks: &Hooks, cell: &AfterCell<'_>) -> bool {
    let Some(h) = hooks.after_cell else {
        return false;
    };
    match h(cell) {
        CellVerdict::Pass => false,
        CellVerdict::Note(msg) => {
            eprintln!("  after_cell: {msg}");
            false
        },
        CellVerdict::Fail(msg) => {
            eprintln!("  after_cell FAIL: {msg}");
            true
        },
    }
}

#[cfg(test)]
mod tests {
    use std::path::Path;
    use std::sync::atomic::{AtomicUsize, Ordering};

    use super::*;
    use crate::config::BenchConfig;
    use crate::env::EnvMeta;
    use crate::sample::BenchResult;

    fn result() -> BenchResult {
        BenchResult {
            title:       "t".into(),
            env:         EnvMeta::default(),
            samples:     Vec::new(),
            cache_path:  String::new(),
            report_path: String::new(),
        }
    }

    fn cell<'a>(
        config: &'a BenchConfig,
        result: &'a BenchResult,
        dropped: &'a [String],
    ) -> AfterCell<'a> {
        AfterCell {
            config,
            result,
            arm_paths: &[],
            dropped,
            out_dir: Path::new("/staged/out"),
        }
    }

    #[test]
    fn absent_hooks_do_nothing_and_never_fail() {
        let hooks = Hooks::default();
        let config = BenchConfig::default();
        let r = result();
        assert!(!run_after_cell(&hooks, &cell(&config, &r, &[])));
        let manifest = crate::config::BenchManifest::default();
        assert!(
            run_on_init(&hooks, &InitContext {
                manifest:    &manifest,
                requested:   &[],
                report_only: false,
            })
            .is_ok()
        );
        run_after_init(&hooks, &RunPlan {
            cells:        &[],
            report_only:  false,
            results_root: Path::new("results"),
        });
    }

    #[test]
    fn an_on_init_abort_stops_with_its_reason() {
        fn veto(_: &InitContext<'_>) -> InitVerdict {
            InitVerdict::Abort("wrong moon phase".into())
        }
        let hooks = Hooks {
            on_init: Some(veto),
            ..Hooks::default()
        };
        let manifest = crate::config::BenchManifest::default();
        let err = run_on_init(&hooks, &InitContext {
            manifest:    &manifest,
            requested:   &[],
            report_only: false,
        })
        .unwrap_err();
        assert_eq!(err, "wrong moon phase");
    }

    #[test]
    fn a_fail_verdict_sets_the_failure_flag_and_a_note_does_not() {
        static CALLS: AtomicUsize = AtomicUsize::new(0);
        fn verdict(cell: &AfterCell<'_>) -> CellVerdict {
            CALLS.fetch_add(1, Ordering::SeqCst);
            // the payload carries the cell identity the hook keys on
            if cell.config.bench == "gate" && cell.config.n == 64 {
                CellVerdict::Fail("regression".into())
            } else {
                CellVerdict::Note("expected counter-example".into())
            }
        }
        let hooks = Hooks {
            after_cell: Some(verdict),
            ..Hooks::default()
        };
        let r = result();

        let mut failing = BenchConfig::default();
        failing.bench = "gate".into();
        failing.n = 64;
        assert!(
            run_after_cell(&hooks, &cell(&failing, &r, &[])),
            "Fail must report the cell as failed"
        );

        let mut noting = BenchConfig::default();
        noting.bench = "other".into();
        noting.n = 64;
        assert!(
            !run_after_cell(&hooks, &cell(&noting, &r, &[])),
            "Note must not report the cell as failed"
        );

        assert_eq!(CALLS.load(Ordering::SeqCst), 2, "the hook ran per cell");
    }
}
