//--------------------------------------------------------------------------------------------------
// Copyright (c) 2026                   orgrinrt                 ort@hiisi.digital
// SPDX-License-Identifier: MPL-2.0     https://mozilla.org/MPL/2.0        contact@hiisi.digital
//--------------------------------------------------------------------------------------------------

//! Summary rows, human units, and the findings index for the driver.

use std::path::Path;

use crate::error::BenchError;

/// One row of the end-of-run summary.
pub(super) struct SummaryRow {
    pub(super) bench:         String,
    pub(super) n:             usize,
    pub(super) variant:       String,
    pub(super) median_ns:     f64,
    pub(super) ratio_vs_best: f64,
    pub(super) regression:    bool,
}

pub(super) fn fmt_ns(ns: f64) -> String {
    if ns >= 1_000_000.0 {
        format!("{:.2} ms", ns / 1_000_000.0)
    } else if ns >= 1_000.0 {
        format!("{:.2} us", ns / 1_000.0)
    } else {
        format!("{ns:.0} ns")
    }
}

/// Regenerate `results/INDEX.md`: the latest summary rows plus links
/// to every findings file present under `results/`.
pub(super) fn write_index(root: &Path, summary: &[SummaryRow]) -> Result<(), BenchError> {
    if !root.exists() {
        return Ok(());
    }
    let mut md = String::from(
        "# Bench Results Index\n\nGenerated by the bench driver; regenerated on every \
         run. Full per-run data (CSV samples, meta, findings) lives beside each entry.\n\n",
    );
    if !summary.is_empty() {
        md.push_str(
            "## Latest run\n\n| bench | n | variant | median | vs best |\n|---|---|---|---|---|\n",
        );
        for row in summary {
            md.push_str(&format!(
                "| {} | {} | {} | {} | {:.2}x{} |\n",
                row.bench,
                row.n,
                row.variant,
                fmt_ns(row.median_ns),
                row.ratio_vs_best,
                if row.regression { " (regression)" } else { "" }
            ));
        }
        md.push('\n');
    }
    md.push_str("## Findings\n\n");
    let mut links: Vec<String> = Vec::new();
    if let Ok(dirs) = std::fs::read_dir(root) {
        for d in dirs.flatten() {
            if let Ok(files) = std::fs::read_dir(d.path()) {
                for f in files.flatten() {
                    let name = f.file_name().to_string_lossy().into_owned();
                    if name.ends_with("_findings.md") || name.ends_with("_report.md") {
                        let rel = f
                            .path()
                            .strip_prefix(root)
                            .map(|p| p.display().to_string())
                            .unwrap_or(name.clone());
                        links.push(format!("- [{name}]({rel})"));
                    }
                }
            }
        }
    }
    links.sort();
    md.push_str(&links.join("\n"));
    md.push('\n');
    std::fs::write(root.join("INDEX.md"), md)
        .map_err(|e| BenchError::io("writing results/INDEX.md", e))
}
