//--------------------------------------------------------------------------------------------------
// Copyright (c) 2026                   orgrinrt                 ort@hiisi.digital
// SPDX-License-Identifier: MPL-2.0     https://mozilla.org/MPL/2.0        contact@hiisi.digital
//--------------------------------------------------------------------------------------------------

//! Summary rows, human units, and the findings index for the driver.

use std::path::Path;

use crate::error::BenchError;

/// One row of the end-of-run summary.
pub(super) struct SummaryRow {
    pub(super) bench:         String,
    pub(super) n:             usize,
    pub(super) variant:       String,
    pub(super) median_ns:     f64,
    pub(super) ratio_vs_best: f64,
    pub(super) regression:    bool,
}

pub(super) fn fmt_ns(ns: f64) -> String {
    if ns >= 1_000_000.0 {
        format!("{:.2} ms", ns / 1_000_000.0)
    } else if ns >= 1_000.0 {
        format!("{:.2} us", ns / 1_000.0)
    } else {
        format!("{ns:.0} ns")
    }
}

/// The `## Latest run` block of an existing index, heading included, or `None`
/// when there is no such block.
///
/// Used to carry the last measured run's rows across a regeneration that has no
/// rows of its own. `--report-only` never produces a summary row (it returns
/// before the timed run), and neither does a run whose every variant failed
/// validation, so rebuilding the file from scratch on those deleted the record
/// of the last run that did measure something.
fn existing_latest_run(root: &Path) -> Option<String> {
    let md = std::fs::read_to_string(root.join("INDEX.md")).ok()?;
    let start = md.find("## Latest run")?;
    let rest = &md[start ..];
    let end = rest[1 ..]
        .find("\n## ")
        .map(|i| i + 2)
        .unwrap_or(rest.len());
    Some(rest[.. end].to_string())
}

/// Regenerate `results/INDEX.md`: the latest summary rows plus links
/// to every findings file present under `results/`.
pub(super) fn write_index(root: &Path, summary: &[SummaryRow]) -> Result<(), BenchError> {
    if !root.exists() {
        return Ok(());
    }
    let mut md = String::from(
        "# Bench Results Index\n\nGenerated by the bench driver; regenerated on every \
         run. Full per-run data (CSV samples, meta, findings) lives beside each entry.\n\n",
    );
    if summary.is_empty() {
        if let Some(block) = existing_latest_run(root) {
            md.push_str(&block);
            if !md.ends_with("\n\n") {
                md.push('\n');
            }
        }
    } else {
        md.push_str(
            "## Latest run\n\n| bench | n | variant | median | vs best |\n|---|---|---|---|---|\n",
        );
        for row in summary {
            md.push_str(&format!(
                "| {} | {} | {} | {} | {:.2}x{} |\n",
                row.bench,
                row.n,
                row.variant,
                fmt_ns(row.median_ns),
                row.ratio_vs_best,
                if row.regression { " (regression)" } else { "" }
            ));
        }
        md.push('\n');
    }
    md.push_str("## Findings\n\n");
    let mut links: Vec<String> = Vec::new();
    if let Ok(dirs) = std::fs::read_dir(root) {
        for d in dirs.flatten() {
            if let Ok(files) = std::fs::read_dir(d.path()) {
                for f in files.flatten() {
                    let name = f.file_name().to_string_lossy().into_owned();
                    if name.ends_with("_findings.md") || name.ends_with("_report.md") {
                        let rel = f
                            .path()
                            .strip_prefix(root)
                            .map(|p| p.display().to_string())
                            .unwrap_or(name.clone());
                        links.push(format!("- [{name}]({rel})"));
                    }
                }
            }
        }
    }
    links.sort();
    md.push_str(&links.join("\n"));
    md.push('\n');
    std::fs::write(root.join("INDEX.md"), md)
        .map_err(|e| BenchError::io("writing results/INDEX.md", e))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn row(bench: &str, variant: &str, med: f64) -> SummaryRow {
        SummaryRow {
            bench:         bench.into(),
            n:             64,
            variant:       variant.into(),
            median_ns:     med,
            ratio_vs_best: 1.0,
            regression:    false,
        }
    }

    fn temp_root(tag: &str) -> std::path::PathBuf {
        let root =
            std::env::temp_dir().join(format!("mockspace-index-test-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("hash")).unwrap();
        std::fs::write(root.join("hash/hash_n64_findings.md"), "# f\n").unwrap();
        root
    }

    #[test]
    fn a_run_writes_its_rows_and_links_every_findings_file() {
        let root = temp_root("write");
        write_index(&root, &[row("hash", "fnv1a", 12.0)]).unwrap();
        let md = std::fs::read_to_string(root.join("INDEX.md")).unwrap();
        assert!(md.contains("## Latest run"), "{md}");
        assert!(md.contains("| hash | 64 | fnv1a |"), "{md}");
        assert!(md.contains("hash/hash_n64_findings.md"), "{md}");
        std::fs::remove_dir_all(&root).ok();
    }

    /// `--report-only` never pushes a summary row (it `continue`s before the
    /// timed run), and a run where every variant fails validation does not
    /// either. `write_index` is called unconditionally at the end of both, and
    /// it rebuilt the file from scratch, so regenerating a report deleted the
    /// record of the last measured run from the index.
    #[test]
    fn a_run_with_no_rows_leaves_the_last_runs_table_standing() {
        let root = temp_root("preserve");
        write_index(&root, &[row("hash", "fnv1a", 12.0)]).unwrap();
        std::fs::write(root.join("hash/hash_n1024_findings.md"), "# f\n").unwrap();

        write_index(&root, &[]).unwrap();
        let md = std::fs::read_to_string(root.join("INDEX.md")).unwrap();
        assert!(
            md.contains("| hash | 64 | fnv1a |"),
            "the last measured run's rows were dropped:\n{md}"
        );
        assert!(
            md.contains("hash/hash_n1024_findings.md"),
            "the newly rendered findings file was not linked:\n{md}"
        );
        std::fs::remove_dir_all(&root).ok();
    }

    /// A fresh tree with nothing measured yet has no table to preserve, and
    /// must not invent one.
    #[test]
    fn a_first_run_with_no_rows_writes_no_table() {
        let root = temp_root("fresh");
        write_index(&root, &[]).unwrap();
        let md = std::fs::read_to_string(root.join("INDEX.md")).unwrap();
        assert!(!md.contains("## Latest run"), "{md}");
        assert!(md.contains("## Findings"), "{md}");
        std::fs::remove_dir_all(&root).ok();
    }
}
