#!/usr/bin/env bash
# =============================================================================
# mockspace/attribution/adverts.sh - the advert net: the suffixes tools append
# =============================================================================
# Part of the attribution library, sourced by `lib/attribution.sh` and reached
# through `use mockspace::attribution` like the rest of it, not on its own.
# =============================================================================

# -----------------------------------------------------------------------------
# Adverts: the tool-promotion suffixes platforms bake into their defaults.
#
# Domains, mailboxes and the robot emoji, which have no innocent reading in a
# commit message. Deliberately not bare English.
# -----------------------------------------------------------------------------
ATTRIBUTION_ADVERT_URL_RE='(claude\.com/claude-code|claude\.ai/code|noreply@anthropic\.com|github\.com/features/copilot|copilot@github\.com|noreply@github\.com|openai\.com/(codex|chatgpt)|chatgpt\.com|noreply@openai\.com|cursor\.(com|sh|so)|codeium\.com|windsurf\.com|sourcegraph\.com/cody|ampcode\.com|devin\.ai|cognition\.ai|aider\.chat|gemini\.google\.com|jules\.google|tabnine\.com|supermaven\.com|augmentcode\.com|replit\.com/ai|phind\.com|blackbox\.ai|v0\.dev|lovable\.dev|bolt\.new|factory\.ai|continue\.dev|🤖)'

# The "generated with" family, anchored.
#
# An earlier scanner matched these phrases bare, anywhere in a message. It
# reported a repository as contaminated on the strength of
#
#     fix: accept a placeholder written with spaces inside its braces
#
# and reported its own rule documentation as a violation of itself. A check
# whose false positives condemn a repository is worse than no check, because the
# remedy it triggers is irreversible. So the phrase must be followed, within a
# short window, by something that is actually a tool: a markdown link, a URL or
# an angle-bracketed address.
ATTRIBUTION_ADVERT_PHRASE_RE='(generated|created|written|authored|made|built)[[:space:]]+(with|by)[[:space:]]*:?[[:space:]]*(\[|https?://|<)'

ATTRIBUTION_ADVERT_RE="(${ATTRIBUTION_ADVERT_URL_RE}|${ATTRIBUTION_ADVERT_PHRASE_RE})"

# attribution_strip_quoted
#
# Filter. Drops fenced blocks and inline backticks from stdin.
#
# This workspace contains rules and documentation that quote forbidden strings
# in order to forbid them, and a scanner that cannot tell a rule from a
# violation is a scanner that condemns the rule.
#
# A code span may wrap, so the inline strip runs over a paragraph rather than
# over a line. Prose wraps and a commit body wraps hardest, so the quotation
# this exists to spare arrives split as often as not, and a line-oriented strip
# sees an opening backtick with no closing one and leaves the span standing.
#
# The paragraph is the bound and it is deliberate. Joining the whole message
# instead would let one unbalanced backtick swallow everything up to the next
# one anywhere later, hiding a real suffix behind a stray quote written
# paragraphs above it. A blank line closes a span whatever the backticks are
# doing, and a tool's suffix sits in its own paragraph, which is what keeps the
# repair from buying a hole. Both directions are pinned in the suite.
#
# The lines inside a paragraph stay lines. The span strip already crosses a
# line break on its own, since a paragraph is one record, and joining the
# lines besides would let the phrase net read "generated by" on one line
# together with a link starting the next, which is ordinary prose and not a
# suffix. That direction is pinned too.
#
# Usage: printf '%s' "$text" | attribution_strip_quoted
#[pub]
attribution_strip_quoted() {
    sed -e '/^```/,/^```/d' | awk '
        BEGIN { RS = ""; ORS = "\n\n" }
        { gsub(/`[^`]*`/, ""); print }
    '
}

# attribution_has_advert <text>
#
# Whether text carries a tool-promotion advert, ignoring anything quoted.
#
# Usage: attribution_has_advert "$body" && ...
#[pub]
attribution_has_advert() {
    printf '%s' "${1:-}" | attribution_strip_quoted | grep -qiE "${ATTRIBUTION_ADVERT_RE}"
}

# attribution_advert_excerpt <text>
#
# The first advert in text with a little context either side, for a report.
# Empty when there is none.
#
# Usage: excerpt=$(attribution_advert_excerpt "$body")
#[pub]
attribution_advert_excerpt() {
    printf '%s' "${1:-}" | attribution_strip_quoted \
        | grep -oiE ".{0,30}${ATTRIBUTION_ADVERT_RE}.{0,30}" | head -1
}
