//! `generate_all`: map each `MatrixDecl` onto one `harness::MatrixSpec` per sweep
//! value and let the harness transport write the isolated variant crates and the
//! `bench.toml` sections. The single canonical `LIB_TEMPLATE` lives here, owned by
//! this crate; a consumer never authors a measurement template, so the four
//! distortions the review panel found in a hand-rolled template cannot recur.

use std::collections::BTreeMap;
use std::path::Path;

use mockspace_bench_harness::matrix::{generate, AxisSpec, AxisValue, MatrixSpec};

use crate::decl::MatrixDecl;

/// The one measurement template every generated variant uses. It calls the
/// scaffold (which owns the anti-hoist, the seed table, the S timing, the digest,
/// the fold-one-keep-alive rule) with the consumer's setup and cell functions
/// named by PATH. There is no measurement logic here to get wrong: the file is a
/// single call. `bench_variant` declares the full size set; the `MatrixSpec.sizes`
/// requests the subset a given family actually runs.
///
/// Rendered by `harness::render` (`{key}` substitution, literal braces escaped
/// `{{`/`}}`). Substituted keys: `{name}` (variant name, injected by the harness),
/// `{scaffold_fn}` (warm/cold_cycle), `{setup_path}`, `{op_path}`, `{sweep_value}`,
/// `{sizes}` (the family's own size set, so `run::<N>` monomorphizes exactly the
/// sizes the decl sweeps rather than a fixed global list).
pub const LIB_TEMPLATE: &str = r#"// generated by mockspace-bench-matrix; never hand-edited.
use mockspace_bench_core::FfiBenchCall;
use mockspace_bench_macro::bench_variant;

#[bench_variant("{name}", sizes = {sizes})]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {{
    mockspace_bench_matrix::scaffold::{scaffold_fn}::<N, _, _, _>(
        input,
        output,
        move |n| {setup_path}("{sweep_value}", n),
        {op_path},
    ).into_ffi()
}}
"#;

const MARKER: &str = "# >>> bench_matrix (generated by mockspace-bench-matrix)";

/// Render a `decl.sizes` list as the Rust array literal the `#[bench_variant(sizes =
/// ...)]` attribute takes, e.g. `[1, 2, 4, 8]`. Each family monomorphizes `run::<N>`
/// over exactly the sizes it sweeps, so a family that sweeps a batch width or a field
/// count carries its own set instead of sharing a fixed global list. The `MatrixSpec.sizes`
/// (the requested set) is this same `decl.sizes`, so the requested and monomorphized sets
/// match by construction.
fn sizes_literal(sizes: &[usize]) -> String {
    let inner: Vec<String> = sizes.iter().map(|s| s.to_string()).collect();
    format!("[{}]", inner.join(", "))
}

/// Build the `harness::MatrixSpec` for one `(decl, sweep_value)` pair.
fn to_spec(decl: &MatrixDecl, sweep_value: &str) -> MatrixSpec {
    let bench = if sweep_value.is_empty() {
        decl.name.clone()
    } else {
        format!("{}_{}", decl.name, sweep_value)
    };
    let values = decl
        .cells
        .iter()
        .map(|c| {
            let setup_path = c.setup_path.clone().unwrap_or_else(|| decl.setup_path.clone());
            AxisValue {
                tag:   c.tag.clone(),
                subst: BTreeMap::from([
                    ("scaffold_fn".to_string(), decl.regime.scaffold_fn().to_string()),
                    ("setup_path".to_string(), setup_path),
                    ("op_path".to_string(), c.op_path.clone()),
                    ("sweep_value".to_string(), sweep_value.to_string()),
                    // every cell of a family shares the family's size set; the variant
                    // monomorphizes `run::<N>` over exactly these.
                    ("sizes".to_string(), sizes_literal(&decl.sizes)),
                ]),
                features: c.features.clone(),
            }
        })
        .collect();
    MatrixSpec {
        bench:             bench.clone(),
        title:             format!("{} ({sweep_value})", decl.name),
        carrier_dep:       decl.crate_dep.clone(),
        extra_deps:        decl.extra_deps.clone(),
        master_seed:       decl.master_seed.clone(),
        sizes:             decl.sizes.clone(),
        baseline_contains: Some(decl.baseline.clone()),
        normalise_mode:    Some("subtract".to_string()),
        // null-floor differencing target: the floor cell tag, resolved to its
        // variant name by the harness section renderer.
        floor_contains:    decl.floor.clone(),
        name_template:     format!("{bench}_{{cell}}"),
        lib_template:      LIB_TEMPLATE.to_string(),
        axes:              vec![AxisSpec { name: "cell".to_string(), values }],
    }
}

/// Generate every variant crate for every matrix, and rewrite the `bench.toml`
/// marker section with all the generated `[bench.*]` sections. `out_dir` is the
/// bench workspace root (where `bench.toml` and `variants/` live).
pub fn generate_all(decls: &[MatrixDecl], out_dir: &Path) -> std::io::Result<()> {
    let mut sections: Vec<String> = Vec::new();
    for decl in decls {
        // Each variant monomorphizes over the decl's own sizes (rendered into the
        // bench_variant attribute), so the only failure is a decl that declares none.
        if decl.sizes.is_empty() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                format!("matrix '{}' declares no sizes; run::<N> has nothing to monomorphize", decl.name),
            ));
        }
        let values = if decl.sweep.values.is_empty() {
            vec![String::new()]
        } else {
            decl.sweep.values.clone()
        };
        for val in &values {
            let spec = to_spec(decl, val);
            if let Err(e) = spec.validate() {
                return Err(std::io::Error::new(std::io::ErrorKind::InvalidInput, e));
            }
            sections.push(generate(&spec, out_dir)?);
        }
    }
    let toml_path = out_dir.join("bench.toml");
    let existing = std::fs::read_to_string(&toml_path).unwrap_or_default();
    let base = match existing.split_once(MARKER) {
        Some((before, _)) => before.trim_end().to_string(),
        None => existing.trim_end().to_string(),
    };
    let body = format!("{base}\n\n{MARKER}\n{}\n", sections.join("\n"));
    std::fs::write(&toml_path, body)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::decl::{CellDecl, MatrixDecl, Regime, SweepAxis};

    fn boundary_decl() -> MatrixDecl {
        MatrixDecl {
            name:        "abi_cross_scalar".to_string(),
            crate_path:  "vehje_bench_carrier".to_string(),
            crate_dep:   "vehje-bench-carrier = { path = \"../../carrier\" }".to_string(),
            extra_deps:  vec![],
            master_seed: "0x1".to_string(),
            sweep:       SweepAxis { name: "profile".to_string(), values: vec!["real".to_string()] },
            // a batch-width sweep: none of these are in the old fixed global set.
            sizes:       vec![1, 2, 4, 8, 16, 32, 64, 128, 256],
            baseline:    "inproc_direct".to_string(),
            floor:       Some("null_entry".to_string()),
            regime:      Regime::Warm,
            setup_path:  "m::setup".to_string(),
            cells:       vec![CellDecl {
                tag:        "ffi".to_string(),
                op_path:    "m::cell_ffi".to_string(),
                setup_path: None,
                features:   vec![],
            }],
        }
    }

    #[test]
    fn sizes_literal_renders_a_rust_array() {
        assert_eq!(sizes_literal(&[1, 2, 4, 8]), "[1, 2, 4, 8]");
        assert_eq!(sizes_literal(&[256]), "[256]");
    }

    #[test]
    fn template_takes_a_sizes_placeholder_not_a_fixed_list() {
        // the fix: the monomorphization set is a per-decl placeholder, so a family that
        // sweeps a batch width carries its own sizes rather than a hardcoded global list.
        assert!(LIB_TEMPLATE.contains("sizes = {sizes}"), "template must take a sizes placeholder");
        assert!(
            !LIB_TEMPLATE.contains("64, 256, 1024, 4096, 16384"),
            "template must not hardcode the interpreter-bench size set"
        );
    }

    #[test]
    fn a_batch_width_decl_carries_its_own_sizes_into_the_spec() {
        // the boundary sweep values (1..256) previously failed the TEMPLATE_SIZES guard;
        // now each cell's subst carries the decl's own sizes for the variant to monomorphize.
        let decl = boundary_decl();
        let spec = to_spec(&decl, "real");
        assert_eq!(spec.sizes, vec![1, 2, 4, 8, 16, 32, 64, 128, 256]);
        let cell = &spec.axes[0].values[0];
        assert_eq!(
            cell.subst.get("sizes").map(String::as_str),
            Some("[1, 2, 4, 8, 16, 32, 64, 128, 256]"),
            "the cell must carry the family's own size set for run::<N> monomorphization"
        );
    }
}
