//! `generate_all`: map each `MatrixDecl` onto one `harness::MatrixSpec` per sweep
//! value and let the harness transport write the isolated variant crates and the
//! `bench.toml` sections. The single canonical `LIB_TEMPLATE` lives here, owned by
//! this crate; a consumer never authors a measurement template, so the four
//! distortions the review panel found in a hand-rolled template cannot recur.

use std::collections::BTreeMap;
use std::path::Path;

use mockspace_bench_harness::matrix::{generate, AxisSpec, AxisValue, MatrixSpec};

use crate::decl::MatrixDecl;

/// The one measurement template every generated variant uses. It calls the
/// scaffold (which owns the anti-hoist, the seed table, the S timing, the digest,
/// the fold-one-keep-alive rule) with the consumer's setup and cell functions
/// named by PATH. There is no measurement logic here to get wrong: the file is a
/// single call. `bench_variant` declares the full size set; the `MatrixSpec.sizes`
/// requests the subset a given family actually runs.
///
/// Rendered by `harness::render` (`{key}` substitution, literal braces escaped
/// `{{`/`}}`). Substituted keys: `{name}` (variant name, injected by the harness),
/// `{scaffold_fn}` (warm/cold_cycle), `{setup_path}`, `{op_path}`, `{sweep_value}`.
pub const LIB_TEMPLATE: &str = r#"// generated by mockspace-bench-matrix; never hand-edited.
use mockspace_bench_core::FfiBenchCall;
use mockspace_bench_macro::bench_variant;

#[bench_variant("{name}", sizes = [64, 256, 1024, 4096, 16384])]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {{
    mockspace_bench_matrix::scaffold::{scaffold_fn}::<N, _, _, _>(
        input,
        output,
        move |n| {setup_path}("{sweep_value}", n),
        {op_path},
    ).into_ffi()
}}
"#;

const MARKER: &str = "# >>> bench_matrix (generated by mockspace-bench-matrix)";

/// The size set the `LIB_TEMPLATE`'s `#[bench_variant]` monomorphizes over. A
/// `decl.sizes` value outside this set would be requested by the `bench.toml`
/// section but have no matching `run::<N>` instantiation in the variant, so the
/// harness would ask for a size the dylib cannot serve. `generate_all` rejects it
/// up front. Keep in sync with the `sizes = [...]` in `LIB_TEMPLATE`.
const TEMPLATE_SIZES: &[usize] = &[64, 256, 1024, 4096, 16384];

/// Build the `harness::MatrixSpec` for one `(decl, sweep_value)` pair.
fn to_spec(decl: &MatrixDecl, sweep_value: &str) -> MatrixSpec {
    let bench = if sweep_value.is_empty() {
        decl.name.clone()
    } else {
        format!("{}_{}", decl.name, sweep_value)
    };
    let values = decl
        .cells
        .iter()
        .map(|c| {
            let setup_path = c.setup_path.clone().unwrap_or_else(|| decl.setup_path.clone());
            AxisValue {
                tag:   c.tag.clone(),
                subst: BTreeMap::from([
                    ("scaffold_fn".to_string(), decl.regime.scaffold_fn().to_string()),
                    ("setup_path".to_string(), setup_path),
                    ("op_path".to_string(), c.op_path.clone()),
                    ("sweep_value".to_string(), sweep_value.to_string()),
                ]),
                features: c.features.clone(),
            }
        })
        .collect();
    MatrixSpec {
        bench:             bench.clone(),
        title:             format!("{} ({sweep_value})", decl.name),
        carrier_dep:       decl.crate_dep.clone(),
        extra_deps:        decl.extra_deps.clone(),
        master_seed:       decl.master_seed.clone(),
        sizes:             decl.sizes.clone(),
        baseline_contains: Some(decl.baseline.clone()),
        normalise_mode:    Some("subtract".to_string()),
        // null-floor differencing target: the floor cell tag, resolved to its
        // variant name by the harness section renderer.
        floor_contains:    decl.floor.clone(),
        name_template:     format!("{bench}_{{cell}}"),
        lib_template:      LIB_TEMPLATE.to_string(),
        axes:              vec![AxisSpec { name: "cell".to_string(), values }],
    }
}

/// Generate every variant crate for every matrix, and rewrite the `bench.toml`
/// marker section with all the generated `[bench.*]` sections. `out_dir` is the
/// bench workspace root (where `bench.toml` and `variants/` live).
pub fn generate_all(decls: &[MatrixDecl], out_dir: &Path) -> std::io::Result<()> {
    let mut sections: Vec<String> = Vec::new();
    for decl in decls {
        if let Some(bad) = decl.sizes.iter().find(|s| !TEMPLATE_SIZES.contains(s)) {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                format!(
                    "matrix '{}' requests size {bad}, which the variant template does not \
                     monomorphize (allowed: {TEMPLATE_SIZES:?}); add it to LIB_TEMPLATE's \
                     bench_variant sizes or drop it from the decl",
                    decl.name
                ),
            ));
        }
        let values = if decl.sweep.values.is_empty() {
            vec![String::new()]
        } else {
            decl.sweep.values.clone()
        };
        for val in &values {
            let spec = to_spec(decl, val);
            if let Err(e) = spec.validate() {
                return Err(std::io::Error::new(std::io::ErrorKind::InvalidInput, e));
            }
            sections.push(generate(&spec, out_dir)?);
        }
    }
    let toml_path = out_dir.join("bench.toml");
    let existing = std::fs::read_to_string(&toml_path).unwrap_or_default();
    let base = match existing.split_once(MARKER) {
        Some((before, _)) => before.trim_end().to_string(),
        None => existing.trim_end().to_string(),
    };
    let body = format!("{base}\n\n{MARKER}\n{}\n", sections.join("\n"));
    std::fs::write(&toml_path, body)
}
