//! Build-time codegen for the first-party preset table (#539).
//!
//! Walks `presets/*.toml` in this crate's source tree and emits
//! `embedded_presets.rs` under `OUT_DIR` with a `pub static
//! EMBEDDED_PRESET_TOML: &[(&str, &str)]` slice keyed by preset name.
//!
//! The slice ships the raw TOML; runtime parsing into `PresetFile`
//! happens lazily in `preset_source::FirstPartyPresetSource` on first
//! access. Validation of preset shape (schema_version, primitive
//! name, etc.) is also runtime; build.rs cannot reach
//! `mockspace_config::PresetFile` without making this crate compile
//! after that crate, which the existing dep ordering already
//! satisfies, but parsing TOML at build.rs time would block a
//! valuable cargo-publish behaviour (`cargo package` runs build.rs
//! before reading dependencies, so a parser dep here would force a
//! workspace cycle). Raw-string embedding sidesteps that entirely.
//!
//! Re-runs when `presets/` itself or any file under it changes. The
//! generated file always exists (empty slice when no presets are
//! present) so the include site never has to conditionalise.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo"));
    let presets_dir = manifest_dir.join("presets");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", presets_dir.display());

    let mut entries: Vec<(String, String)> = Vec::new();

    if presets_dir.is_dir() {
        let read = fs::read_dir(&presets_dir).unwrap_or_else(|e| {
            panic!(
                "failed to read presets directory at {}: {e}",
                presets_dir.display()
            )
        });
        for dir_entry in read {
            let dir_entry = dir_entry.expect("readable preset directory entry");
            let path = dir_entry.path();
            // Skip directories, hidden files, and non-.toml entries.
            if !path.is_file() {
                continue;
            }
            let file_name = match path.file_name().and_then(|n| n.to_str()) {
                Some(name) => name,
                None => continue,
            };
            if file_name.starts_with('.') {
                continue;
            }
            if path.extension().and_then(|e| e.to_str()) != Some("toml") {
                continue;
            }
            // Track each preset file individually for incremental rebuilds.
            println!("cargo:rerun-if-changed={}", path.display());
            let name = file_name
                .strip_suffix(".toml")
                .expect("filtered by extension check above")
                .to_string();
            let toml_body = fs::read_to_string(&path).unwrap_or_else(|e| {
                panic!("failed to read preset {}: {e}", path.display())
            });
            entries.push((name, toml_body));
        }
    }

    // Sort by preset name so the generated slice ordering is stable
    // across rebuilds. Lookup is by linear scan today; if the set
    // grows beyond ~50 entries, switch to phf or a sorted-binary-search
    // helper. Linear scan dominates only at LintsConfig construction,
    // not on the hot dispatch path.
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let dest = out_dir.join("embedded_presets.rs");

    let mut generated = String::new();
    generated.push_str("// Generated by mockspace-rs/build.rs. Do not edit.\n");
    generated.push_str("pub static EMBEDDED_PRESET_TOML: &[(&str, &str)] = &[\n");
    for (name, body) in &entries {
        // `r#"..."#` raw strings are robust against arbitrary TOML
        // content. Bump the `#` count if a preset legitimately needs
        // a `"#` sequence (unlikely; TOML strings would escape it).
        generated.push_str(&format!("    (\"{name}\", r##\"{body}\"##),\n"));
    }
    generated.push_str("];\n");

    fs::write(&dest, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}
