//--------------------------------------------------------------------------------------------------
// Copyright (c) 2026                   orgrinrt                 ort@hiisi.digital
// SPDX-License-Identifier: MPL-2.0     https://mozilla.org/MPL/2.0        contact@hiisi.digital
//--------------------------------------------------------------------------------------------------

//! One pipeline for every generated document.
//!
//! Documents used to be generated by five paths: the design document, the
//! per-crate overviews and deep dives, the root passthroughs, the registry
//! tables, and the structure artifacts. Each decided its own output filename
//! and chose for itself which transformations to run, and that produced one bug
//! class over and over.
//!
//! Two shapes of it. A path forgot a step, so references in per-crate documents
//! and in the design document rendered literally, and nothing reported it. Or
//! two places computed the same filename independently and drifted, so a link
//! pointed at `LAW.md` while the file was written as `902_LAW.md`, and the
//! overview links went dead when a prefix scheme changed under one of them.
//!
//! Both are structural rather than careless, so the fix is structural:
//!
//! - **[`DocId`] is the only thing that names a document.** A writer and a
//!   link builder cannot disagree, because neither computes a name.
//! - **Every document is planned before any is rendered.** The index of what
//!   will exist is complete before the first reference resolves, so a reference
//!   from a document written early to one written later is not a special case.
//! - **[`render`] is the only way content becomes output.** A step cannot be
//!   skipped by a path that forgot it, because paths do not run steps.

use std::path::{Path, PathBuf};

use crate::config::Config;

/// What a document is, which is what decides where it sorts and what it is
/// called.
///
/// The variants are the reading order a docs directory should have. Without one
/// a reader meeting thirty files alphabetically starts wherever the alphabet
/// happens to put them.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DocId {
    /// A document a reader should start with. Sorts first.
    Primary {
        stem: String,
        ext:  String,
    },
    /// One crate's overview, or one of its deep dives. Sorts by dependency
    /// depth, so the listing reads bottom-up: what everything rests on first.
    Crate {
        upper:   String,
        subject: String,
        depth:   usize,
    },
    /// A registry namespace's table. Sorts by declaration order, which is the
    /// order the project chose to present its own vocabulary in.
    Registry {
        page:  String,
        index: usize,
    },
    /// Everything else. Sorts last, as supplementary material.
    Supplementary {
        stem: String,
        ext:  String,
    },
}

impl DocId {
    /// Classify a root-level document by name, which is the only place the
    /// primary-versus-supplementary distinction is decided.
    pub fn root(file_name: &str, cfg: &Config) -> Self {
        let (stem, ext) = split_ext(file_name);
        if cfg
            .primary_docs
            .iter()
            .any(|p| p.eq_ignore_ascii_case(stem))
        {
            DocId::Primary {
                stem: stem.to_string(),
                ext:  ext.to_string(),
            }
        } else {
            DocId::Supplementary {
                stem: stem.to_string(),
                ext:  ext.to_string(),
            }
        }
    }

    /// The file this document is written to, and the file a link to it targets.
    ///
    /// The single naming authority. Everything that writes a document and
    /// everything that links to one asks this, so the two cannot drift.
    pub fn file_name(&self, cfg: &Config) -> String {
        match self {
            DocId::Primary {
                stem,
                ext,
            } => {
                if cfg.ordered_docs {
                    format!("000_{stem}.{ext}")
                } else {
                    format!("{stem}.{ext}")
                }
            },
            DocId::Crate {
                upper,
                subject,
                depth,
            } => {
                // An overview carries the crate's name alone. Naming it
                // `_OVERVIEW` would put the least specific document under the
                // longest name, and a crate with no deep dives would carry a
                // suffix distinguishing it from nothing.
                let stem = if subject == "OVERVIEW" {
                    upper.clone()
                } else {
                    format!("{upper}_{subject}")
                };
                if cfg.ordered_docs {
                    // Ten per band leaves room to insert a layer without
                    // renumbering the ones above it. Crates at one depth share
                    // a prefix, because nothing orders them against each other.
                    format!("{:03}_{stem}.md", 100 + depth * 10)
                } else {
                    format!("{stem}.md")
                }
            },
            DocId::Registry {
                page,
                index,
            } => {
                let (stem, ext) = split_ext(page);
                if !cfg.ordered_docs {
                    return page.clone();
                }
                if cfg
                    .primary_docs
                    .iter()
                    .any(|p| p.eq_ignore_ascii_case(stem))
                {
                    return format!("000_{stem}.{ext}");
                }
                // Three digits leave the registry band room for as many
                // namespaces as a project declares, without spilling into the
                // supplementary one.
                format!("{}_{stem}.{ext}", 900 + (*index).min(98))
            },
            DocId::Supplementary {
                stem,
                ext,
            } => {
                if cfg.ordered_docs {
                    format!("999_{stem}.{ext}")
                } else {
                    format!("{stem}.{ext}")
                }
            },
        }
    }

    /// How a reference names this document, when one can.
    ///
    /// `Some` for the things a project links to by name: a crate and a registry
    /// namespace. `None` for a document nothing refers to symbolically.
    fn link_key(&self) -> Option<LinkKey> {
        match self {
            DocId::Crate {
                upper,
                subject,
                depth: _,
            } if subject == "OVERVIEW" => Some(LinkKey::Crate(normalize_crate_key(upper))),
            DocId::Registry {
                page,
                ..
            } => {
                let (stem, _) = split_ext(page);
                Some(LinkKey::Registry(stem.to_lowercase().replace('-', "_")))
            },
            _ => None,
        }
    }
}

/// What a reference selects, as opposed to what a document is called.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
enum LinkKey {
    Crate(String),
    Registry(String),
}

/// Where a document's content comes from.
#[derive(Debug, Clone)]
pub enum Source {
    /// A template on disk.
    Template(PathBuf),
    /// Content computed during this run.
    Computed(String),
}

/// A document that will exist, before it is rendered.
#[derive(Debug, Clone)]
pub struct Planned {
    pub id:     DocId,
    pub source: Source,
}

impl Planned {
    pub fn template(id: DocId, path: PathBuf) -> Self {
        Self {
            id,
            source: Source::Template(path),
        }
    }

    pub fn computed(id: DocId, content: String) -> Self {
        Self {
            id,
            source: Source::Computed(content),
        }
    }
}

/// What every document will be called, keyed by what a reference calls it.
///
/// Built from the planned set before anything renders, which is what makes a
/// forward reference ordinary rather than a special case. The alternative, and
/// what this replaces, was globbing the output directory: that directory is
/// cleaned at the start of a run and refilled during it, so a glob answered
/// "has this been written yet" rather than "what is this called".
#[derive(Debug, Default, Clone)]
pub struct DocIndex {
    entries: std::collections::BTreeMap<LinkKey, String>,
}

impl DocIndex {
    pub fn build(planned: &[Planned], cfg: &Config) -> Self {
        let mut entries = std::collections::BTreeMap::new();
        for p in planned {
            if let Some(key) = p.id.link_key() {
                entries.insert(key, p.id.file_name(cfg));
            }
        }
        Self {
            entries,
        }
    }

    /// The document for a crate, by its short name.
    pub fn crate_doc(&self, short: &str) -> Option<&str> {
        self.entries
            .get(&LinkKey::Crate(normalize_crate_key(short)))
            .map(String::as_str)
    }

    /// The document for a registry namespace, by its key.
    pub fn registry_doc(&self, key: &str) -> Option<&str> {
        self.entries
            .get(&LinkKey::Registry(key.to_string()))
            .map(String::as_str)
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }
}

/// Turn a document's content into what is written.
///
/// Placeholders first, then references. A placeholder expands into text that
/// may itself carry a reference, so resolving first would leave every one of
/// those literal.
///
/// This is the only place either step runs, which is what stops a generation
/// path from skipping one. Two of them did.
pub fn render(
    content: &str,
    ph: &crate::render_design::Placeholders,
    registry: &crate::registry::Registry,
    cfg: &Config,
) -> String {
    crate::registry::resolve_all(
        &ph.apply(content),
        &cfg.registry_namespaces,
        registry,
        &cfg.registry_roots,
        &cfg.repo_root,
        &cfg.docs_dir,
        cfg,
    )
}

/// Render and write every planned document.
///
/// Returns what was written, so a caller can report it and so a later pass can
/// prune whatever was not.
pub fn render_all(
    planned: &[Planned],
    ph: &crate::render_design::Placeholders,
    registry: &crate::registry::Registry,
    cfg: &Config,
) -> Vec<PathBuf> {
    // The single writer owns its output directory rather than assuming a
    // caller made it. A repo generating for the first time has no docs/ yet.
    crate::render_design::ensure_docs_dir(cfg);
    let header = crate::render_design::generation_header_md(cfg);
    let mut written = Vec::new();
    for p in planned {
        let raw = match &p.source {
            Source::Template(path) => {
                match std::fs::read_to_string(path) {
                    Ok(t) => t,
                    Err(e) => {
                        eprintln!("  warning: cannot read {}: {e}", path.display());
                        continue;
                    },
                }
            },
            Source::Computed(text) => text.clone(),
        };
        let body = render(&raw, ph, registry, cfg);
        // Unconditional, and the sweep below depends on it: a text document
        // reaching docs/ without the marker is one the sweep can never remove
        // once it stops being generated. That covers what is written here and
        // the `.dot` and `.svg` written elsewhere, all of which carry a header
        // of their own. It does not cover a rendered image, which has nowhere
        // to put one; those are swept by the stem of the diagram beside them,
        // per `OURS_IN_BYTES`.
        let full = format!("{header}\n{body}");
        let out = cfg.docs_dir.join(p.id.file_name(cfg));
        crate::render_design::write_generated(&out, &full);
        written.push(out);
    }
    written
}

/// Remove documents that were generated once and are not generated any more.
///
/// Nothing else writes those files, so nothing else removes them, and a
/// retired document left behind reads as current for as long as it sits there.
///
/// Two conditions, and the second is what keeps this off other people's work.
/// The file was not written by the run that `kept` describes, **and** it
/// carries the generation header, so some earlier run wrote it. A file failing
/// the second belongs to whoever put it there: a contributing guide, an
/// architecture note, anything a repository keeps in its documents directory
/// beside what is rendered into it. Sweeping on the first condition alone
/// removed every one of those, on every run, without saying so.
///
/// A rendered image cannot carry the marker, so it goes with the diagram it was
/// rendered from: an image whose stem matches a **diagram** this call is
/// sweeping, and whose extension is one this tool renders, is swept alongside
/// it.
///
/// The stem comes off a swept `.dot` and off nothing else, and that is the
/// whole of what keeps this off other people's images. Reading it off any
/// swept file instead reaches much further than the sentence above describes:
/// a generated `DESIGN.md` retiring, which happens the moment a repository
/// turns document ordering on, would take a hand-drawn `DESIGN.png` with it.
/// Every image this tool writes is rendered from a `.dot` of the same stem, so
/// the narrower rule loses nothing.
///
/// Only the top level is read. A subdirectory is somebody's to organise.
pub fn sweep_retired(docs_dir: &Path, kept: &[PathBuf]) -> usize {
    let kept: std::collections::HashSet<&Path> = kept.iter().map(|p| p.as_path()).collect();
    let Ok(entries) = std::fs::read_dir(docs_dir) else {
        return 0;
    };
    let candidates: Vec<PathBuf> = entries
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.is_file() && !kept.contains(p.as_path()))
        .collect();

    // The text half first, because what it sweeps is what the byte half reads
    // its stems from.
    let mut swept = 0usize;
    let mut swept_stems: std::collections::HashSet<std::ffi::OsString> =
        std::collections::HashSet::new();
    for path in &candidates {
        // Unreadable is not ours. A file whose bytes cannot be read is one
        // that cannot be shown to carry the marker, and the safe reading of
        // that is to leave it where it is.
        let ours = std::fs::read_to_string(path)
            .map(|t| crate::render_design::is_generated(&t))
            .unwrap_or(false);
        if ours && std::fs::remove_file(path).is_ok() {
            swept += 1;
            let is_a_diagram = path.extension().and_then(|e| e.to_str()) == Some("dot");
            if is_a_diagram {
                if let Some(stem) = path.file_stem() {
                    swept_stems.insert(stem.to_os_string());
                }
            }
        }
    }

    for path in &candidates {
        let is_ours_in_bytes = path
            .extension()
            .and_then(|e| e.to_str())
            .is_some_and(|e| OURS_IN_BYTES.contains(&e));
        let follows_a_swept_file = path
            .file_stem()
            .is_some_and(|stem| swept_stems.contains(stem));
        if is_ours_in_bytes && follows_a_swept_file && std::fs::remove_file(path).is_ok() {
            swept += 1;
        }
    }
    swept
}

/// Extensions this tool writes into the documents directory as bytes rather
/// than as text, so nothing in the file itself can say who wrote it.
///
/// Every other artifact answers for itself: `.md`, `.dot` and `.svg` all carry
/// the generation header. This list exists for the two images rendered from a
/// `.dot` beside them, and it stays this short on purpose. An extension here
/// is one [`sweep_retired`] may delete on a name match rather than on
/// something the file says, so adding one widens what this tool claims to own.
const OURS_IN_BYTES: &[&str] = &["png"];

/// One spelling for a crate key, so the two sides of the lookup agree.
///
/// A key is built from the document stem, which is uppercase and underscored,
/// while a reference is written with the crate's own name, which is lowercase
/// and usually hyphenated. Normalising both means a crate whose name carries an
/// underscore is not addressable only by the spelling one side happened to
/// produce.
fn normalize_crate_key(s: &str) -> String {
    s.to_lowercase().replace('_', "-")
}

/// Split `NAME.ext` into its parts, treating a name with no dot as extensionless.
fn split_ext(file_name: &str) -> (&str, &str) {
    match file_name.rsplit_once('.') {
        Some((stem, ext)) => (stem, ext),
        None => (file_name, ""),
    }
}

/// Prepend `path`'s extension chain, so `STRUCTURE.GRAPH.dot` keeps both parts.
pub fn stem_of(file_name: &str) -> String {
    split_ext(file_name).0.to_string()
}

/// Whether a path is inside the docs directory and generated by this run.
pub fn is_generated(path: &Path, written: &[PathBuf]) -> bool {
    written.iter().any(|w| w == path)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg_ordered() -> Config {
        let mut cfg = Config::from_dir(Path::new("/nonexistent"));
        cfg.ordered_docs = true;
        cfg.primary_docs = vec!["DESIGN".into()];
        cfg
    }

    fn generated(body: &str) -> String {
        // The shape every generation header opens with. Built from the
        // constant rather than typed out, so a header that changes spelling
        // fails here rather than quietly stopping the sweep.
        format!(
            "<!--\n  {}\n-->\n\n{body}\n",
            crate::render_design::GENERATED_MARKER
        )
    }

    #[test]
    fn the_sweep_removes_a_retired_document_and_leaves_a_hand_written_one() {
        let d = tempfile::tempdir().unwrap();
        let docs = d.path();

        // Written by an earlier run, not written by this one: retired.
        let retired = docs.join("DESIGN-old.md");
        std::fs::write(&retired, generated("what this used to say")).unwrap();

        // Written by this run: kept, and not because of its contents.
        let current = docs.join("DESIGN.md");
        std::fs::write(&current, generated("what it says now")).unwrap();

        // Somebody's, and the whole point. No header, so nothing in it says
        // mockspace wrote it, because mockspace did not.
        let theirs = docs.join("CONTRIBUTING.md");
        std::fs::write(&theirs, "# Contributing\n\nOpen a pull request.\n").unwrap();

        // A directory, which is somebody's to organise either way.
        std::fs::create_dir(docs.join("research")).unwrap();
        std::fs::write(docs.join("research/note.md"), generated("nested")).unwrap();

        let swept = sweep_retired(docs, &[current.clone()]);

        assert_eq!(swept, 1, "only the retired document");
        assert!(!retired.exists(), "the retired document is gone");
        assert!(current.exists(), "this run's output stays");
        assert!(
            theirs.exists(),
            "a hand-written document is not mockspace's to delete"
        );
        assert!(
            docs.join("research/note.md").exists(),
            "a subdirectory is untouched"
        );
    }

    /// The first eight bytes of any PNG, which is enough to make the file
    /// invalid UTF-8 and so unreadable as text.
    const PNG: &[u8] = b"\x89PNG\r\n\x1a\n";

    #[test]
    fn a_retired_document_does_not_take_an_image_that_shares_its_name() {
        let d = tempfile::tempdir().unwrap();
        let docs = d.path();

        // The case that made the rule too wide. A generated document retires,
        // which happens to any repository the moment it turns document
        // ordering on and every name gains its `000_` prefix. A hand-drawn
        // image happens to share its stem.
        let retired_doc = docs.join("DESIGN.md");
        let theirs = docs.join("DESIGN.png");
        std::fs::write(&retired_doc, generated("# design")).unwrap();
        std::fs::write(&theirs, PNG).unwrap();

        let swept = sweep_retired(docs, &[]);

        assert!(
            !retired_doc.exists(),
            "the document was ours and stays swept"
        );
        assert!(
            theirs.exists(),
            "a hand-made image was deleted because a generated document shared its stem \
             (sweep removed {swept})"
        );
        assert_eq!(swept, 1, "only the document was ours");
    }

    #[test]
    fn a_retired_diagram_takes_its_rendered_image_with_it() {
        let d = tempfile::tempdir().unwrap();
        let docs = d.path();

        // A diagram this run no longer generates. The `.dot` carries the
        // marker and answers for itself; the `.png` is bytes and can never
        // carry one, so without the companion rule it sits in docs/ reading as
        // current for the life of the repository.
        let retired_dot = docs.join("STRUCTURE.GRAPH.dot");
        let retired_png = docs.join("STRUCTURE.GRAPH.png");
        std::fs::write(&retired_dot, generated("digraph {}")).unwrap();
        std::fs::write(&retired_png, PNG).unwrap();

        // The same pair, still generated. Named in `kept`, so neither half
        // goes, and the `.png` must not be taken by its own sibling's stem.
        let live_dot = docs.join("BENCHES.parse.dot");
        let live_png = docs.join("BENCHES.parse.png");
        std::fs::write(&live_dot, generated("digraph {}")).unwrap();
        std::fs::write(&live_png, PNG).unwrap();

        // Somebody's image, with nothing of ours sharing its stem.
        let theirs = docs.join("architecture.png");
        std::fs::write(&theirs, PNG).unwrap();

        // Somebody's image that happens to share a stem with a document this
        // run still generates. The stem is only ever read off a file being
        // swept, so a live sibling reaches nothing.
        let theirs_beside_live = docs.join("BENCHES.parse.jpg");
        std::fs::write(&theirs_beside_live, PNG).unwrap();

        let swept = sweep_retired(docs, &[live_dot.clone(), live_png.clone()]);

        assert_eq!(swept, 2, "the retired diagram and its image");
        assert!(!retired_dot.exists());
        assert!(!retired_png.exists(), "the image outlived the diagram");
        assert!(live_dot.exists());
        assert!(live_png.exists());
        assert!(theirs.exists(), "an image of somebody's own is not ours");
        assert!(
            theirs_beside_live.exists(),
            "a live sibling's stem swept nothing, and an extension we do not \
             write is not ours whatever it sits beside"
        );
    }

    #[test]
    fn an_image_whose_diagram_is_hand_written_stays() {
        // The control for the rule above. The companion goes because the file
        // it belongs to was swept, so a stem whose text half is somebody's
        // must reach nothing: otherwise the rule is "delete images", written
        // in a way that looks narrower than it is.
        let d = tempfile::tempdir().unwrap();
        let docs = d.path();
        let theirs_dot = docs.join("sketch.dot");
        let theirs_png = docs.join("sketch.png");
        std::fs::write(&theirs_dot, "digraph { a -> b }\n").unwrap();
        std::fs::write(&theirs_png, PNG).unwrap();

        assert_eq!(sweep_retired(docs, &[]), 0);
        assert!(theirs_dot.exists());
        assert!(theirs_png.exists());
    }

    #[test]
    fn the_sweep_reads_the_header_and_not_a_mention_of_it() {
        let d = tempfile::tempdir().unwrap();
        let docs = d.path();

        // The control for the check above, and the reason the marker is looked
        // for in the first few lines rather than anywhere: a document that
        // explains the header is a document about the header, not one of ours.
        // This crate's own documentation is exactly that.
        let prose = docs.join("USAGE_GUIDE.md");
        std::fs::write(
            &prose,
            format!(
                "# Usage\n\nEvery generated file opens with `{}`, so you can tell them apart.\n",
                crate::render_design::GENERATED_MARKER
            ),
        )
        .unwrap();

        // An empty file, which has no header and is nobody's to guess about.
        let empty = docs.join("EMPTY.md");
        std::fs::write(&empty, "").unwrap();

        assert_eq!(sweep_retired(docs, &[]), 0);
        assert!(prose.exists());
        assert!(empty.exists());
    }

    #[test]
    fn a_document_reaches_the_output_carrying_the_marker() {
        // The sweep can only ever remove what it recognises, so a rendering
        // path that stopped emitting the header would leave every document it
        // writes permanently unsweepable, and nothing else would notice. This
        // is the other end of that contract.
        let d = tempfile::tempdir().unwrap();
        let mut cfg = Config::from_dir(d.path());
        cfg.docs_dir = d.path().join("docs");

        let planned = vec![Planned::computed(DocId::root("DESIGN.md", &cfg), "the body".into())];
        let written = render_all(
            &planned,
            &crate::render_design::Placeholders::compute(&Default::default(), &cfg),
            &crate::registry::Registry::default(),
            &cfg,
        );

        assert_eq!(written.len(), 1);
        let text = std::fs::read_to_string(&written[0]).unwrap();
        assert!(
            crate::render_design::is_generated(&text),
            "rendered document does not carry the marker:\n{text}"
        );
        assert!(text.contains("the body"));
    }

    #[test]
    fn one_function_names_a_document_and_a_link_to_it() {
        // The drift this replaces: a writer and a link builder each computing
        // the name, and disagreeing. A link said LAW.md while the file was
        // 902_LAW.md, so every reference into the registry pointed at nothing.
        let cfg = cfg_ordered();
        let reg = DocId::Registry {
            page:  "LAW.md".into(),
            index: 2,
        };
        let planned = vec![Planned::computed(reg.clone(), String::new())];
        let index = DocIndex::build(&planned, &cfg);

        assert_eq!(reg.file_name(&cfg), "902_LAW.md");
        assert_eq!(index.registry_doc("law"), Some("902_LAW.md"));
    }

    #[test]
    fn a_crate_overview_is_named_for_the_crate_alone() {
        let cfg = cfg_ordered();
        let overview = DocId::Crate {
            upper:   "PLAN_VALIDATE".into(),
            subject: "OVERVIEW".into(),
            depth:   4,
        };
        let dive = DocId::Crate {
            upper:   "PLAN_VALIDATE".into(),
            subject: "COMBAT".into(),
            depth:   4,
        };
        assert_eq!(overview.file_name(&cfg), "140_PLAN_VALIDATE.md");
        assert_eq!(dive.file_name(&cfg), "140_PLAN_VALIDATE_COMBAT.md");
    }

    #[test]
    fn crates_at_one_depth_share_a_prefix() {
        // Nothing orders siblings against each other, so a rolling index would
        // be inventing an order and would shift when one is added.
        let cfg = cfg_ordered();
        let a = DocId::Crate {
            upper:   "SEAM".into(),
            subject: "OVERVIEW".into(),
            depth:   1,
        };
        let b = DocId::Crate {
            upper:   "REGISTER".into(),
            subject: "OVERVIEW".into(),
            depth:   1,
        };
        assert!(a.file_name(&cfg).starts_with("110_"));
        assert!(b.file_name(&cfg).starts_with("110_"));
    }

    #[test]
    fn the_bands_read_in_order() {
        let cfg = cfg_ordered();
        let primary = DocId::root("DESIGN.md", &cfg).file_name(&cfg);
        let crate_doc = DocId::Crate {
            upper:   "STORE".into(),
            subject: "OVERVIEW".into(),
            depth:   0,
        }
        .file_name(&cfg);
        let registry = DocId::Registry {
            page:  "LAW.md".into(),
            index: 0,
        }
        .file_name(&cfg);
        let supplementary = DocId::root("NOTES.md", &cfg).file_name(&cfg);

        let mut order = vec![&supplementary, &registry, &crate_doc, &primary];
        order.sort();
        assert_eq!(order, vec![&primary, &crate_doc, &registry, &supplementary]);
    }

    #[test]
    fn an_unordered_project_gets_plain_names() {
        let mut cfg = cfg_ordered();
        cfg.ordered_docs = false;
        assert_eq!(DocId::root("DESIGN.md", &cfg).file_name(&cfg), "DESIGN.md");
        assert_eq!(
            DocId::Registry {
                page:  "LAW.md".into(),
                index: 2,
            }
            .file_name(&cfg),
            "LAW.md"
        );
    }

    #[test]
    fn the_index_knows_a_document_that_does_not_exist_yet() {
        // The property that makes a forward reference ordinary: the index is
        // built from what will exist, not from what has been written.
        let cfg = cfg_ordered();
        let planned = vec![Planned::template(
            DocId::Crate {
                upper:   "PLAN_VALIDATE".into(),
                subject: "OVERVIEW".into(),
                depth:   4,
            },
            PathBuf::from("/nowhere/DESIGN.md.tmpl"),
        )];
        let index = DocIndex::build(&planned, &cfg);
        assert_eq!(
            index.crate_doc("plan-validate"),
            Some("140_PLAN_VALIDATE.md")
        );
    }

    #[test]
    fn a_deep_dive_is_not_a_link_target() {
        // `crates::x` means the crate, which is its overview. A deep dive is
        // reached from there rather than named directly.
        let cfg = cfg_ordered();
        let planned = vec![Planned::computed(
            DocId::Crate {
                upper:   "STORE".into(),
                subject: "KEYS".into(),
                depth:   1,
            },
            String::new(),
        )];
        assert!(DocIndex::build(&planned, &cfg).is_empty());
    }
}

/// Every markdown document a run will produce, before any is rendered.
///
/// One function enumerates them all, which is what makes the index complete
/// before the first reference resolves and what stops a document from being
/// generated by a path that forgot a step.
pub fn plan(cfg: &Config, crates: &crate::model::CrateMap) -> Vec<Planned> {
    let mut out = Vec::new();

    // Root templates. `DESIGN.md.tmpl` is one of these rather than a special
    // case: it differs only in the placeholder it expands, and a placeholder is
    // not a reason for a second code path.
    if let Ok(entries) = std::fs::read_dir(&cfg.mock_dir) {
        let mut roots: Vec<_> = entries
            .flatten()
            .filter(|e| e.file_name().to_string_lossy().ends_with(".md.tmpl"))
            .collect();
        roots.sort_by_key(|e| e.file_name());
        for entry in roots {
            let name = entry.file_name().to_string_lossy().to_string();
            let out_name = name.trim_end_matches(".tmpl").to_string();
            out.push(Planned::template(DocId::root(&out_name, cfg), entry.path()));
        }
    }

    // Per-crate overviews and deep dives.
    // Across every source directory. Planning from one group would leave every
    // crate in the others with no generated document at all, and the run would
    // report success.
    {
        let mut depth_cache = std::collections::BTreeMap::new();
        {
            let dirs = crate::parse::package_dirs_in(&cfg.src_dirs);
            for dir in dirs {
                let crate_name = dir
                    .file_name()
                    .map(|n| n.to_string_lossy().to_string())
                    .unwrap_or_default();
                let upper = crate::render_design::crate_doc_stem(&crate_name, &cfg.crate_prefix);
                let depth = crate::graph::compute_depth(&crate_name, crates, &mut depth_cache);

                let design = dir.join("DESIGN.md.tmpl");
                if design.is_file() {
                    out.push(Planned::template(
                        DocId::Crate {
                            upper: upper.clone(),
                            subject: "OVERVIEW".into(),
                            depth,
                        },
                        design,
                    ));
                }
                for (subject, path) in crate::render_design::find_deep_dives(&dir) {
                    out.push(Planned::template(
                        DocId::Crate {
                            upper: upper.clone(),
                            subject: subject.to_uppercase(),
                            depth,
                        },
                        path,
                    ));
                }
            }
        }
    }

    out
}

/// Add the registry tables to a plan.
///
/// Separate from [`plan`] only because the registry is loaded later; the pages
/// are documents like any other and go through the same render.
pub fn plan_registry_pages(
    plan: &mut Vec<Planned>,
    namespaces: &[crate::registry::RegistryNamespace],
    reg: &crate::registry::Registry,
    mock_dir: &Path,
    cfg: &Config,
) {
    for (index, ns) in namespaces
        .iter()
        .filter(|n| n.render.has_page())
        .enumerate()
    {
        if reg.by_namespace.get(&ns.key).is_none() {
            continue;
        }
        // A namespace named `catalogue` would otherwise generate over the
        // document rendered from a hand-authored `CATALOGUE.md.tmpl`, silently.
        // The template is what claims the name, so its presence is the
        // collision.
        let claimed = mock_dir.join(format!("{}.tmpl", ns.page_name()));
        if claimed.is_file() {
            eprintln!(
                "  ERROR: namespace `{}` would generate {} over the document rendered from {}. Rename the namespace or the template.",
                ns.key,
                ns.page_name(),
                claimed.display()
            );
            continue;
        }
        plan.push(Planned::computed(
            DocId::Registry {
                page: ns.page_name(),
                index,
            },
            crate::registry::registry_page_body(ns, reg, cfg),
        ));
    }
}
