use std::collections::BTreeMap;
use std::fmt::Write;
use std::fs;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

use crate::config::Config;
use crate::model::*;
use crate::render_design;

/// Platform-specific hook helpers injected into {{HOOK_HELPERS}} for Claude.
///
/// - _extract: reads fields from tool_input (Claude's input format)
/// - deny: outputs hookSpecificOutput JSON wrapper with deny decision
/// - context: outputs hookSpecificOutput JSON wrapper with additionalContext
const CLAUDE_HOOK_HELPERS: &str = r##"# --- Platform helpers (Claude) — generated by xtask ---
_extract() {
    echo "$__INPUT" | jq -r ".tool_input.$1 // \"\"" 2>/dev/null || echo ""
}

allow() {
    printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse"}}\n'
    exit 0
}

deny() {
    printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' "$1"
    exit 0
}

context() {
    printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","additionalContext":"%s"}}\n' "$1"
}

# Absolute path of the repo this hook belongs to; baked at generation time.
readonly __HOOK_REPO_ROOT="{{REPO_ROOT}}"

# Exit with `allow` if the current tool invocation doesn't target this repo.
# Reads FILE_PATH and COMMAND from the environment (callers must set them
# first via _extract). A tool call targets this repo if:
#   * FILE_PATH is under __HOOK_REPO_ROOT (absolute path match), OR
#   * COMMAND mentions __HOOK_REPO_ROOT by absolute path, OR
#   * The process cwd is __HOOK_REPO_ROOT or a descendant (relative-path
#     shell commands like `git mv mock/foo bar` count via cwd).
_scope_or_allow() {
    if [[ -n "$FILE_PATH" ]]; then
        case "$FILE_PATH" in
            "$__HOOK_REPO_ROOT"/*) return 0 ;;
            *) allow ;;
        esac
    fi
    if [[ -n "$COMMAND" ]]; then
        if echo "$COMMAND" | grep -qF "$__HOOK_REPO_ROOT"; then
            return 0
        fi
        case "$(pwd)" in
            "$__HOOK_REPO_ROOT"|"$__HOOK_REPO_ROOT"/*) return 0 ;;
        esac
        allow
    fi
    allow
}
# --- End platform helpers ---"##;

/// Platform-specific hook helpers injected into {{HOOK_HELPERS}} for Copilot.
///
/// - _extract: reads fields from toolArgs (Copilot's stringified JSON format)
/// - deny: outputs flat JSON deny decision
/// - context: outputs plain text (non-blocking)
const COPILOT_HOOK_HELPERS: &str = r##"# --- Platform helpers (Copilot) — generated by xtask ---
_extract() {
    echo "$__INPUT" | jq -r "if .toolArgs then (.toolArgs | fromjson? | .$1 // \"\") else \"\" end" 2>/dev/null || echo ""
}

allow() {
    exit 0
}

deny() {
    printf '{"permissionDecision":"deny","permissionDecisionReason":"%s"}\n' "$1"
    exit 0
}

context() {
    printf '%s\n' "$1"
}

# Absolute path of the repo this hook belongs to; baked at generation time.
readonly __HOOK_REPO_ROOT="{{REPO_ROOT}}"

# Exit with `allow` if the current tool invocation doesn't target this repo.
# Mirrors the Claude variant; see that one for detailed semantics.
_scope_or_allow() {
    if [[ -n "$FILE_PATH" ]]; then
        case "$FILE_PATH" in
            "$__HOOK_REPO_ROOT"/*) return 0 ;;
            *) allow ;;
        esac
    fi
    if [[ -n "$COMMAND" ]]; then
        if echo "$COMMAND" | grep -qF "$__HOOK_REPO_ROOT"; then
            return 0
        fi
        case "$(pwd)" in
            "$__HOOK_REPO_ROOT"|"$__HOOK_REPO_ROOT"/*) return 0 ;;
        esac
        allow
    fi
    allow
}
# --- End platform helpers ---"##;

/// Set the executable bit on a file.
#[cfg(unix)]
fn set_executable(path: &Path) {
    if let Ok(meta) = fs::metadata(path) {
        let mut perms = meta.permissions();
        perms.set_mode(0o755);
        let _ = fs::set_permissions(path, perms);
    }
}

// ---------------------------------------------------------------------------
// Hook metadata for settings generation (Phase 7)
// ---------------------------------------------------------------------------

/// Metadata collected from each hook for settings generation.
struct HookMeta {
    /// Output file name (e.g. "check-byline.sh").
    name: String,
    /// Tool matchers this hook should fire on (e.g. ["Bash", "Write", "Edit"]).
    matchers: Vec<String>,
}

/// Derive tool matchers from a hook file name using naming conventions.
fn matchers_from_name(name: &str) -> Vec<String> {
    if name.ends_with("-guard.sh") {
        vec!["Bash".into(), "Write".into(), "Edit".into()]
    } else if name.ends_with("-reminder.sh") {
        vec!["Bash".into()]
    } else if name.starts_with("check-") {
        vec!["Bash".into()]
    } else {
        vec!["Bash".into()]
    }
}

/// Parse `# @matchers:` frontmatter from the first 5 lines of a hook template.
fn parse_hook_matchers(template: &str) -> Option<Vec<String>> {
    for line in template.lines().take(5) {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("# @matchers:") {
            let matchers: Vec<String> = rest
                .split(',')
                .map(|s| s.trim().to_string())
                .filter(|s| !s.is_empty())
                .collect();
            if !matchers.is_empty() {
                return Some(matchers);
            }
        }
    }
    None
}

// ---------------------------------------------------------------------------
// Phase 6: Builtin agent hooks
// ---------------------------------------------------------------------------

/// Derive the agent mode env var name from a project name.
///
/// e.g. "saalis" -> "SAALIS_AGENT_MODE", "polka-dots" -> "POLKA_DOTS_AGENT_MODE"
fn agent_mode_var(project_name: &str) -> String {
    let upper = project_name.to_uppercase().replace('-', "_");
    format!("{upper}_AGENT_MODE")
}

/// Quote a string as a bash single-quoted literal, escaping internal quotes.
fn bash_literal(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// Generate the check-byline.sh hook content (without HOOK_HELPERS substitution).
///
/// Enforces the byline policy configured in `mock/agent/config.toml` under
/// `[attribution]`. Both `non_autonomous` and `autonomous` are glob patterns
/// (empty = no byline permitted / autonomous-mode config error).
fn builtin_check_byline(cfg: &Config) -> String {
    let mode_var = agent_mode_var(&cfg.project_name);
    let non_auto = bash_literal(&cfg.attribution.non_autonomous);
    let auto = bash_literal(&cfg.attribution.autonomous);
    format!(
        r##"#!/usr/bin/env bash
# Built-in mockspace hook: enforce commit authorship policy.
# Patterns come from mock/agent/config.toml [attribution]; baked at generation.
set -uo pipefail
__INPUT=$(cat)
{{{{HOOK_HELPERS}}}}
FILE_PATH=""
COMMAND=$(_extract "command")
_scope_or_allow

# Only check git commit commands.
if ! echo "$COMMAND" | grep -q "git commit"; then allow; fi

# Configured byline patterns (baked at generation time).
NON_AUTO_PATTERN={non_auto}
AUTO_PATTERN={auto}

AGENT_MODE="${{{mode_var}:-assistant}}"

# Extract all Co-Authored-By bylines from the command.
# Matches the trailer case-insensitively up to the closing double-quote of the
# git commit -m "..." argument (the typical shape). Trims prefix + whitespace.
# Limitation: if -m uses single quotes or HEREDOC the extraction may over-match;
# the git commit-msg hook catches those at real commit time.
BYLINES=$(printf '%s' "$COMMAND" \
    | grep -oiE 'co-authored-by:[^"]*' \
    | sed -E 's/^[Cc]o-[Aa]uthored-[Bb]y:[[:space:]]*//' \
    | sed -E 's/[[:space:]]+$//')

if [[ "$AGENT_MODE" == "autonomous" ]]; then
    if [[ -z "$AUTO_PATTERN" ]]; then
        deny "Autonomous mode is enabled but mock/agent/config.toml [attribution] autonomous is empty. Configure the expected byline pattern."
    fi
    if [[ -z "$BYLINES" ]]; then
        deny "Autonomous mode requires a Co-Authored-By byline matching: $AUTO_PATTERN"
    fi
    MATCHED=false
    while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        if [[ "$line" == $AUTO_PATTERN ]]; then
            MATCHED=true
            break
        fi
    done <<< "$BYLINES"
    if [[ "$MATCHED" != "true" ]]; then
        deny "No Co-Authored-By byline matched autonomous pattern: $AUTO_PATTERN"
    fi
else
    # Non-autonomous (assistant) mode.
    if [[ -z "$NON_AUTO_PATTERN" ]]; then
        # Empty pattern: no byline permitted.
        if [[ -n "$BYLINES" ]]; then
            deny "Non-autonomous mode forbids Co-Authored-By bylines. Remove the byline, or set {mode_var}=autonomous if this is genuinely autonomous work."
        fi
    else
        # Non-empty pattern: bylines must match it.
        while IFS= read -r line; do
            [[ -z "$line" ]] && continue
            if [[ "$line" != $NON_AUTO_PATTERN ]]; then
                deny "Co-Authored-By byline does not match non-autonomous pattern ($NON_AUTO_PATTERN): $line"
            fi
        done <<< "$BYLINES"
    fi
fi
allow
"##
    )
}

/// Generate the mockspace-write-guard.sh hook content.
fn builtin_write_guard(cfg: &Config) -> String {
    let mock_rel = cfg
        .mock_dir
        .strip_prefix(&cfg.repo_root)
        .unwrap_or(&cfg.mock_dir)
        .to_string_lossy()
        .to_string();
    format!(
        r##"#!/usr/bin/env bash
# Built-in mockspace hook: phase gate enforcement
# Mirrors the lint rules: changelist_doc_gate, changelist_required,
# changelist_lock, changelist_immutability.
set -uo pipefail
__INPUT=$(cat)
MOCK_ROOT="{mock_rel}"
{{{{HOOK_HELPERS}}}}
FILE_PATH=$(_extract file_path)
COMMAND=$(_extract command)
_scope_or_allow
# --- Determine target path ---
TARGET=""
if [[ -n "$FILE_PATH" ]]; then
    TARGET="$FILE_PATH"
elif [[ -n "$COMMAND" ]]; then
    # Mutation-only detection: match commands that write to files. The
    # patterns require either a leading space/start-of-string to avoid
    # matching substrings in unrelated words, or a trailing space to
    # avoid matching word-ending tokens. Shell FD redirects (`2>&1`,
    # `&> file`) are intentionally NOT classified as file writes — they
    # redirect descriptors, not mutate files. Actual file redirection
    # (`> path`, `>> path`) goes through Write/Edit tools in the agent
    # flow, not Bash; we accept the tradeoff.
    WRITE_MARKERS='(^|[[:space:]])(tee|mv|cp|rm|dd|install|sed[[:space:]]+-i|perl[[:space:]]+-i)([[:space:]]|$)'
    if ! echo "$COMMAND" | grep -qE "$WRITE_MARKERS"; then
        allow
    fi
    if echo "$COMMAND" | grep -q "$MOCK_ROOT"; then
        TARGET=$(echo "$COMMAND" | grep -oE "[^ ]*${{MOCK_ROOT}}[^ ]*" | head -1) || true
    fi
fi
# Not targeting the mock subdir? Allow (scope-to-repo already passed).
if [[ -z "$TARGET" ]] || ! echo "$TARGET" | grep -q "$MOCK_ROOT"; then
    allow
fi
REL_PATH=$(echo "$TARGET" | sed "s|.*${{MOCK_ROOT}}/||")
# --- Always allowed: agent templates ---
if echo "$REL_PATH" | grep -qE '^agent/'; then
    allow
fi
# --- Always allowed: root-level mockspace templates ---
if echo "$REL_PATH" | grep -qE '^[^/]+\.md\.tmpl$'; then
    allow
fi
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo "")
if [[ -z "$REPO_ROOT" ]]; then
    allow
fi
# --- Detect phase ---
# All git ls-files queries run with `-C "$REPO_ROOT"` so phase detection is
# cwd-independent. Without it, invocations from a subdir (e.g. `mock/`) would
# resolve `mock/design_rounds/` relative to cwd, return nothing, and fall back
# to TOPIC, blocking legitimate IMPL-phase edits.
DOC_CL_ACTIVE=$(git -C "$REPO_ROOT" ls-files "${{MOCK_ROOT}}/design_rounds/" 2>/dev/null \
    | grep -E "^${{MOCK_ROOT}}/design_rounds/[^/]+_changelist\.doc\.md$" \
    | head -1) || true
DOC_CL_LOCKED=$(git -C "$REPO_ROOT" ls-files "${{MOCK_ROOT}}/design_rounds/" 2>/dev/null \
    | grep -E "^${{MOCK_ROOT}}/design_rounds/[^/]+_changelist\.doc\.lock\.md$" \
    | head -1) || true
SRC_CL_ACTIVE=$(git -C "$REPO_ROOT" ls-files "${{MOCK_ROOT}}/design_rounds/" 2>/dev/null \
    | grep -E "^${{MOCK_ROOT}}/design_rounds/[^/]+_changelist\.src\.md$" \
    | head -1) || true
SRC_CL_LOCKED=$(git -C "$REPO_ROOT" ls-files "${{MOCK_ROOT}}/design_rounds/" 2>/dev/null \
    | grep -E "^${{MOCK_ROOT}}/design_rounds/[^/]+_changelist\.src\.lock\.md$" \
    | head -1) || true
if [[ -n "$SRC_CL_LOCKED" ]]; then
    PHASE="CLOSED"
elif [[ -n "$SRC_CL_ACTIVE" ]]; then
    PHASE="IMPL"
elif [[ -n "$DOC_CL_LOCKED" ]]; then
    PHASE="DRAFT"
elif [[ -n "$DOC_CL_ACTIVE" ]]; then
    PHASE="DOC"
else
    PHASE="TOPIC"
fi
DIRTY_DOCS=$(git -C "$REPO_ROOT" diff --name-only 2>/dev/null \
    | grep -E "^${{MOCK_ROOT}}/crates/.*\.(md\.tmpl|md)$" | head -1) || true
# --- Design round files ---
if echo "$REL_PATH" | grep -qE '^design_rounds/'; then
    FULL_GIT_PATH="${{MOCK_ROOT}}/${{REL_PATH}}"
    BASENAME=$(basename "$REL_PATH")
    if [[ "$BASENAME" == "README.md" ]]; then
        allow
    fi
    if echo "$REL_PATH" | grep -qE '^design_rounds/[^/]+/'; then
        SUBDIR_NAME=$(echo "$REL_PATH" | sed -n 's|^design_rounds/\([^/]*\)/.*|\1|p')
        FLAT_PATH=$(echo "$REL_PATH" | sed 's|^design_rounds/[^/]*/|design_rounds/|')
        deny "BLOCKED: '${{REL_PATH}}' targets a round-archive subdirectory.\\n\\nSubdirectories under design_rounds/ are ARCHIVED closed rounds; they are frozen forever.\\nActive rounds always live FLAT at design_rounds/ root (see design-round skill, File layout section).\\n\\nIf you meant to edit an active round file, the correct path is probably:\\n  ${{FLAT_PATH}}\\n\\nIf that active file does not yet exist, create it at the flat path above.\\nNever mkdir under design_rounds/ for active work; cargo mock close is the only process that creates subdirectories.\\n\\nCurrent phase: ${{PHASE}}"
    fi
    IS_CHANGELIST=false
    IS_DOC_CHANGELIST=false
    IS_SRC_CHANGELIST=false
    IS_LOCKED=false
    IS_DEPRECATED=false
    if echo "$BASENAME" | grep -qE '_changelist\.(doc|src)\.(lock|deprecated)\.md$'; then
        IS_CHANGELIST=true
        echo "$BASENAME" | grep -q '\.doc\.' && IS_DOC_CHANGELIST=true
        echo "$BASENAME" | grep -q '\.src\.' && IS_SRC_CHANGELIST=true
        echo "$BASENAME" | grep -q '\.lock\.' && IS_LOCKED=true
        echo "$BASENAME" | grep -q '\.deprecated\.' && IS_DEPRECATED=true
    elif echo "$BASENAME" | grep -qE '_changelist\.(doc|src)\.md$'; then
        IS_CHANGELIST=true
        echo "$BASENAME" | grep -q '\.doc\.' && IS_DOC_CHANGELIST=true
        echo "$BASENAME" | grep -q '\.src\.' && IS_SRC_CHANGELIST=true
    fi
    if git -C "$REPO_ROOT" ls-files --error-unmatch "$FULL_GIT_PATH" >/dev/null 2>&1; then
        if $IS_CHANGELIST && $IS_LOCKED; then
            deny "BLOCKED: locked changelist '${{BASENAME}}' is FROZEN.\\n\\nCurrent phase: ${{PHASE}}\\nLint: changelist-immutability (HARD_ERROR)"
        fi
        if $IS_CHANGELIST && $IS_DEPRECATED; then
            deny "BLOCKED: deprecated changelist '${{BASENAME}}' is FROZEN.\\n\\nCurrent phase: ${{PHASE}}\\nLint: changelist-immutability (HARD_ERROR)"
        fi
        if $IS_DOC_CHANGELIST && ! $IS_LOCKED && ! $IS_DEPRECATED; then
            if [[ "$PHASE" == "DOC" ]]; then allow; fi
            deny "BLOCKED: cannot edit doc changelist '${{BASENAME}}' -- not in DOC phase.\\n\\nPhase: ${{PHASE}}.\\nLint: changelist-immutability (HARD_ERROR)"
        fi
        if $IS_SRC_CHANGELIST && ! $IS_LOCKED && ! $IS_DEPRECATED; then
            if [[ "$PHASE" == "IMPL" ]]; then allow; fi
            deny "BLOCKED: cannot edit source changelist '${{BASENAME}}' -- not in IMPL phase.\\n\\nPhase: ${{PHASE}}.\\nLint: changelist-immutability (HARD_ERROR)"
        fi
        if ! $IS_CHANGELIST; then
            deny "BLOCKED: topic '${{BASENAME}}' is committed and FROZEN.\\n\\nCurrent phase: ${{PHASE}}"
        fi
    fi
    if ! $IS_CHANGELIST; then
        if [[ "$PHASE" != "TOPIC" ]]; then
            deny "BLOCKED: cannot create topic '${{BASENAME}}' -- not in TOPIC phase.\\n\\nPhase: ${{PHASE}}."
        fi
        allow
    fi
    if $IS_DOC_CHANGELIST && ! $IS_LOCKED && ! $IS_DEPRECATED; then
        if [[ "$PHASE" != "TOPIC" ]]; then
            deny "BLOCKED: cannot create doc changelist '${{BASENAME}}' -- one already exists or phase is wrong.\\n\\nPhase: ${{PHASE}}."
        fi
        allow
    fi
    if $IS_SRC_CHANGELIST && ! $IS_LOCKED && ! $IS_DEPRECATED; then
        if [[ "$PHASE" != "DRAFT" ]]; then
            deny "BLOCKED: cannot create source changelist '${{BASENAME}}' -- not in DRAFT phase.\\n\\nPhase: ${{PHASE}}."
        fi
        allow
    fi
    if $IS_LOCKED || $IS_DEPRECATED; then allow; fi
    allow
fi
# --- Crate files are phase-gated ---
if echo "$REL_PATH" | grep -qE '^crates/'; then
    if echo "$REL_PATH" | grep -qE 'SHAME\.md\.tmpl$'; then allow; fi
    if echo "$REL_PATH" | grep -qE '\.(md\.tmpl|md)$'; then
        if [[ "$PHASE" != "DOC" ]]; then
            deny "BLOCKED: cannot edit '${{REL_PATH}}' -- not in DOC phase.\\n\\nPhase: ${{PHASE}}.\\nLint: changelist-doc-gate (HARD_ERROR)"
        fi
        allow
    fi
    if echo "$REL_PATH" | grep -qE '\.rs$'; then
        if [[ "$PHASE" != "IMPL" ]]; then
            deny "BLOCKED: cannot edit '${{REL_PATH}}' -- not in IMPL phase.\\n\\nPhase: ${{PHASE}}.\\nLint: changelist-required (HARD_ERROR)"
        fi
        allow
    fi
    if [[ "$PHASE" == "TOPIC" ]] || [[ "$PHASE" == "CLOSED" ]]; then
        deny "BLOCKED: cannot edit '${{REL_PATH}}' -- no changelist exists or round is complete.\\n\\nPhase: ${{PHASE}}."
    fi
    allow
fi
# --- Root Cargo.toml ---
if echo "$REL_PATH" | grep -qE '^Cargo\.toml$'; then
    if [[ "$PHASE" == "TOPIC" ]] || [[ "$PHASE" == "CLOSED" ]]; then
        deny "BLOCKED: cannot edit '${{REL_PATH}}' -- no changelist exists or round is complete.\\n\\nPhase: ${{PHASE}}."
    fi
    allow
fi
allow
"##
    )
}

/// Generate the mockspace-reminder.sh hook content.
fn builtin_reminder(cfg: &Config) -> String {
    let mock_rel = cfg
        .mock_dir
        .strip_prefix(&cfg.repo_root)
        .unwrap_or(&cfg.mock_dir)
        .to_string_lossy()
        .to_string();
    format!(
        r##"#!/usr/bin/env bash
# Built-in mockspace hook: print mockspace rules reminder before tool use
# Non-blocking. Only fires when the tool targets mockspace paths.
set -uo pipefail
__INPUT=$(cat)
{{{{HOOK_HELPERS}}}}
FILE_PATH=$(_extract file_path)
COMMAND=$(_extract command)
_scope_or_allow
IS_MOCKSPACE=false
if [[ -n "$FILE_PATH" ]] && echo "$FILE_PATH" | grep -q "{mock_rel}"; then
    IS_MOCKSPACE=true
fi
if [[ -n "$COMMAND" ]] && echo "$COMMAND" | grep -q "{mock_rel}"; then
    IS_MOCKSPACE=true
fi
if [[ "$IS_MOCKSPACE" != "true" ]]; then
    allow
fi
context "MOCKSPACE REMINDER: You are operating on mockspace files. Follow the design round workflow: TOPIC -> DOC -> DRAFT -> IMPL -> CLOSED. Check phase before editing. Use 'cargo mock' commands for phase transitions."
allow
"##
    )
}

/// Generate the no-yagni-guard.sh hook content.
fn builtin_no_yagni() -> String {
    r##"#!/usr/bin/env bash
# Built-in mockspace hook: flag YAGNI reasoning in commit messages
set -uo pipefail
__INPUT=$(cat)
{{HOOK_HELPERS}}
FILE_PATH=""
COMMAND=$(_extract "command")
_scope_or_allow
# Only check git commit commands
if ! echo "$COMMAND" | grep -q "git commit"; then allow; fi
# Check for YAGNI-like keywords in the commit message
YAGNI_PATTERNS="yagni|premature|over-engineer|overkill|good enough for now|not needed yet|too early|unnecessary complexity|keep it simple"
if echo "$COMMAND" | grep -qiE "$YAGNI_PATTERNS"; then
    context "WARNING: YAGNI-flavored reasoning detected in commit message. This project embraces the ideal when designing -- extensible, trait-based, registered. Shortcuts justified by 'you ain't gonna need it' are not welcome. Reconsider the commit message."
fi
allow
"##
    .to_string()
}

/// Write a single builtin hook to both Claude and Copilot directories.
///
/// Returns the hook metadata and increments count by 2 (one per platform).
fn write_builtin_hook(
    name: &str,
    content: &str,
    repo_root: &str,
    claude_hooks_dir: &Path,
    copilot_hooks_dir: &Path,
    count: &mut usize,
) -> HookMeta {
    let claude_content = content
        .replace("{{HOOK_HELPERS}}", CLAUDE_HOOK_HELPERS)
        .replace("{{REPO_ROOT}}", repo_root);
    let claude_path = claude_hooks_dir.join(name);
    fs::write(&claude_path, &claude_content).expect("failed to write builtin claude hook");
    #[cfg(unix)]
    set_executable(&claude_path);
    eprintln!("  {} (builtin)", claude_path.display());
    *count += 1;

    let copilot_content = content
        .replace("{{HOOK_HELPERS}}", COPILOT_HOOK_HELPERS)
        .replace("{{REPO_ROOT}}", repo_root);
    let copilot_path = copilot_hooks_dir.join(name);
    fs::write(&copilot_path, &copilot_content).expect("failed to write builtin copilot hook");
    #[cfg(unix)]
    set_executable(&copilot_path);
    eprintln!("  {} (builtin)", copilot_path.display());
    *count += 1;

    HookMeta {
        name: name.to_string(),
        matchers: matchers_from_name(name),
    }
}

/// Generate all builtin agent hooks.
///
/// Writes 4 hooks to both `.claude/hooks/` and `.github/hooks/`:
/// - check-byline.sh
/// - mockspace-write-guard.sh
/// - mockspace-reminder.sh
/// - no-yagni-guard.sh
fn generate_builtin_hooks(
    cfg: &Config,
    claude_hooks_dir: &Path,
    copilot_hooks_dir: &Path,
    count: &mut usize,
) -> Vec<HookMeta> {
    let mut hooks = Vec::new();

    let repo_root = cfg.repo_root.to_string_lossy().to_string();

    hooks.push(write_builtin_hook(
        "check-byline.sh",
        &builtin_check_byline(cfg),
        &repo_root,
        claude_hooks_dir,
        copilot_hooks_dir,
        count,
    ));

    hooks.push(write_builtin_hook(
        "mockspace-write-guard.sh",
        &builtin_write_guard(cfg),
        &repo_root,
        claude_hooks_dir,
        copilot_hooks_dir,
        count,
    ));

    hooks.push(write_builtin_hook(
        "mockspace-reminder.sh",
        &builtin_reminder(cfg),
        &repo_root,
        claude_hooks_dir,
        copilot_hooks_dir,
        count,
    ));

    hooks.push(write_builtin_hook(
        "no-yagni-guard.sh",
        &builtin_no_yagni(),
        &repo_root,
        claude_hooks_dir,
        copilot_hooks_dir,
        count,
    ));

    hooks
}

// ---------------------------------------------------------------------------
// Phase 7: Auto-generated settings
// ---------------------------------------------------------------------------

/// Generate `settings.json` (Claude) and `hooks.json` (Copilot) from hook metadata.
fn generate_settings(
    repo_root: &Path,
    all_hooks: &[HookMeta],
) -> usize {
    let mut count = 0;

    // Group hooks by matcher
    let mut matcher_to_hooks: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for hook in all_hooks {
        for matcher in &hook.matchers {
            matcher_to_hooks
                .entry(matcher.clone())
                .or_default()
                .push(hook.name.clone());
        }
    }

    // --- Claude settings.json ---
    let claude_dir = repo_root.join(".claude");
    let _ = fs::create_dir_all(&claude_dir);

    let mut claude_hooks_entries = Vec::new();
    for (matcher, hook_names) in &matcher_to_hooks {
        for hook_name in hook_names {
            claude_hooks_entries.push(format!(
                r#"      {{
        "matcher": "{matcher}",
        "hooks": [
          {{
            "type": "command",
            "command": ".claude/hooks/{hook_name}"
          }}
        ]
      }}"#
            ));
        }
    }

    let hooks_json_inner = claude_hooks_entries.join(",\n");

    let claude_settings = format!(
        r#"{{
    "hooks": {{
      "PreToolUse": [
{hooks_json_inner}
      ]
    }}
}}"#
    );

    let claude_settings_path = claude_dir.join("settings.json");
    fs::write(&claude_settings_path, &claude_settings)
        .expect("failed to write claude settings.json");
    eprintln!("  {} (auto-generated)", claude_settings_path.display());
    count += 1;

    // --- Copilot hooks.json ---
    let copilot_hooks_dir = repo_root.join(".github").join("hooks");
    let _ = fs::create_dir_all(&copilot_hooks_dir);

    let mut copilot_entries = Vec::new();
    for (matcher, hook_names) in &matcher_to_hooks {
        for hook_name in hook_names {
            copilot_entries.push(format!(
                r#"    {{
      "name": "{hook_name}",
      "command": ".github/hooks/{hook_name}",
      "event": "pre_tool_use",
      "tool": "{matcher}"
    }}"#
            ));
        }
    }

    let copilot_hooks_inner = copilot_entries.join(",\n");
    let copilot_hooks_json = format!(
        r#"{{
  "hooks": [
{copilot_hooks_inner}
  ]
}}"#
    );

    let copilot_hooks_path = copilot_hooks_dir.join("hooks.json");
    fs::write(&copilot_hooks_path, &copilot_hooks_json)
        .expect("failed to write copilot hooks.json");
    eprintln!("  {} (auto-generated)", copilot_hooks_path.display());
    count += 1;

    count
}

// ---------------------------------------------------------------------------
// Phase 9: Builtin agent templates
// ---------------------------------------------------------------------------

/// A builtin rule with its filename, apply_to patterns, and body content.
struct BuiltinRule {
    /// Output filename without extension (e.g. "generated-agent-rules").
    name: String,
    /// Glob patterns for frontmatter.
    apply_to: Vec<String>,
    /// Body content (already substituted).
    body: String,
}

/// A builtin skill with its directory name, metadata, and body content.
struct BuiltinSkill {
    /// Directory name (e.g. "design-round").
    dir_name: String,
    /// Skill display name.
    skill_name: String,
    /// Skill description.
    skill_description: String,
    /// Body content (already substituted).
    body: String,
}

/// All builtin templates generated by Phase 9.
struct BuiltinTemplates {
    rules: Vec<BuiltinRule>,
    skills: Vec<BuiltinSkill>,
    preamble: String,
    postamble: String,
}

/// Replace `{var}` single-brace placeholders in builtin content.
///
/// Uses single braces to distinguish from the `{{double_brace}}` template
/// system used by consumer templates.
fn substitute_builtin_vars(text: &str, mock_dir: &str, project_name: &str, crate_prefix: &str) -> String {
    text.replace("{mock_dir}", mock_dir)
        .replace("{project_name}", project_name)
        .replace("{crate_prefix}", crate_prefix)
}

/// Generate agent rules and hooks derived from lint configuration.
///
/// For each `forbidden-imports` rule at error/build-gate severity,
/// generates:
/// - An agent rule file per scope (tells the agent what's forbidden)
/// - An agent hook per scope (blocks writes containing forbidden patterns)
fn generate_lint_derived_content(
    cfg: &Config,
    claude_rules_dir: &Path,
    copilot_instructions_dir: &Path,
    claude_hooks_dir: &Path,
    copilot_hooks_dir: &Path,
    header_md: &str,
    preamble: &str,
    postamble: &str,
) -> usize {
    use std::collections::BTreeMap as Map;

    let mut count = 0;

    // Collect forbidden-imports rules grouped by scope
    let mut scope_rules: Map<String, Vec<(String, String)>> = Map::new();

    // Look for forbidden-imports params in lint config
    for (key, value) in &cfg.lint_overrides.params.get("forbidden-imports").cloned().unwrap_or_default() {
        // Keys are like "rule.no-dyn.scope", "rule.no-dyn.forbidden", "rule.no-dyn.reason"
        if !key.starts_with("rule.") { continue; }

        let parts: Vec<&str> = key.splitn(3, '.').collect();
        if parts.len() < 3 { continue; }

        let rule_name = parts[1];
        let field = parts[2];

        if field == "scope" {
            // Pre-populate scope entry
            scope_rules.entry(value.clone()).or_default();
        }
    }

    // Now collect forbidden + reason per scope
    let params = cfg.lint_overrides.params.get("forbidden-imports").cloned().unwrap_or_default();
    let mut rules_by_name: Map<String, (String, String, String)> = Map::new(); // name -> (scope, forbidden, reason)

    for (key, value) in &params {
        if !key.starts_with("rule.") { continue; }
        let parts: Vec<&str> = key.splitn(3, '.').collect();
        if parts.len() < 3 { continue; }

        let rule_name = parts[1].to_string();
        let field = parts[2];

        let entry = rules_by_name.entry(rule_name).or_insert_with(|| (String::new(), String::new(), String::new()));
        match field {
            "scope" => entry.0 = value.clone(),
            "forbidden" => entry.1 = value.clone(),
            "reason" => entry.2 = value.clone(),
            "enabled" if value == "false" => { entry.0 = "__disabled__".to_string(); }
            _ => {}
        }
    }

    // Group by scope
    let mut by_scope: Map<String, Vec<(String, String)>> = Map::new(); // scope -> [(forbidden, reason)]
    for (_name, (scope, forbidden, reason)) in &rules_by_name {
        if scope == "__disabled__" || scope.is_empty() || forbidden.is_empty() { continue; }
        by_scope.entry(scope.clone()).or_default().push((forbidden.clone(), reason.clone()));
    }

    if by_scope.is_empty() {
        return 0;
    }

    let mock_rel = cfg.mock_dir.strip_prefix(&cfg.repo_root)
        .unwrap_or(&cfg.mock_dir)
        .to_string_lossy()
        .replace('\\', "/");

    for (scope, rules) in &by_scope {
        // Convert scope to apply_to glob
        let apply_to_glob = format!("{mock_rel}/crates/{scope}/**");

        // Generate a slug for the filename
        let slug = scope.replace('*', "star").replace(',', "-").replace(' ', "");

        // --- Agent Rule ---
        let mut body = String::new();
        let _ = writeln!(body, "## Forbidden imports — scope `{scope}` (auto-generated from lint config)\n");
        let _ = writeln!(body, "The following are **forbidden** in crates matching `{scope}`.");
        let _ = writeln!(body, "Violations are caught by the `forbidden-imports` lint at error level.\n");
        for (forbidden, reason) in rules {
            let _ = writeln!(body, "- `{forbidden}` — {reason}");
        }
        let _ = writeln!(body, "\nDo NOT write code that uses any of these. Check before writing.");

        let claude_fm = format!("---\napply_to: [\"{apply_to_glob}\"]\n---\n\n");
        let copilot_fm = format!("---\napplyTo: [\"{apply_to_glob}\"]\n---\n\n");

        let rule_name = format!("lint-forbidden-{slug}");
        let claude_content = format!("{claude_fm}{header_md}\n{preamble}\n\n{body}\n{postamble}");
        let copilot_content = format!("{copilot_fm}{header_md}\n{preamble}\n\n{body}\n{postamble}");

        let claude_path = claude_rules_dir.join(format!("{rule_name}.md"));
        fs::write(&claude_path, &claude_content).ok();
        eprintln!("  {} (lint-derived)", claude_path.display());
        count += 1;

        let copilot_path = copilot_instructions_dir.join(format!("{rule_name}.instructions.md"));
        fs::write(&copilot_path, &copilot_content).ok();
        count += 1;

        // --- Agent Hook ---
        // Generate a hook that blocks writes containing forbidden patterns
        let mut forbidden_patterns: Vec<String> = Vec::new();
        for (forbidden, _) in rules {
            for pat in forbidden.split(',') {
                let pat = pat.trim();
                if !pat.is_empty() {
                    // Convert pattern to grep-able regex
                    let grep_pat = pat.replace("::", "::").replace("*", "");
                    forbidden_patterns.push(grep_pat);
                }
            }
        }

        if forbidden_patterns.is_empty() { continue; }

        // Build the scope match pattern for the hook
        let scope_grep = scope.replace('*', ".*").replace(',', "|");
        let patterns_grep = forbidden_patterns.iter()
            .map(|p| format!("\"{}\"", p.replace('"', "\\\"")))
            .collect::<Vec<_>>()
            .join(" ");

        let hook_body = format!(
            "#!/usr/bin/env bash\n\
             # Auto-generated from [lints.forbidden-imports] — scope: {scope}\n\
             set -uo pipefail\n\
             __INPUT=$(cat)\n\
             {{{{HOOK_HELPERS}}}}\n\
             FILE_PATH=$(_extract \"file_path\")\n\
             COMMAND=\"\"\n\
             _scope_or_allow\n\
             TARGET=\"$FILE_PATH\"\n\
             CONTENT=$(_extract \"new_string\")\n\
             if [[ -z \"$CONTENT\" ]]; then CONTENT=$(_extract \"content\"); fi\n\
             # Only check crates matching scope\n\
             if ! echo \"$TARGET\" | grep -qE \"{mock_rel}/crates/({scope_grep})/\"; then allow; fi\n\
             # Check for forbidden patterns\n\
             for PAT in {patterns_grep}; do\n\
                 if echo \"$CONTENT\" | grep -qF \"$PAT\"; then\n\
                     deny \"Forbidden import/type '$PAT' in scope '{scope}'. See lint config.\"\n\
                 fi\n\
             done\n"
        );

        let hook_name = format!("lint-forbidden-{slug}.sh");

        let repo_root_str = cfg.repo_root.to_string_lossy();
        let claude_hook = hook_body
            .replace("{{HOOK_HELPERS}}", CLAUDE_HOOK_HELPERS)
            .replace("{{REPO_ROOT}}", &repo_root_str);
        let copilot_hook = hook_body
            .replace("{{HOOK_HELPERS}}", COPILOT_HOOK_HELPERS)
            .replace("{{REPO_ROOT}}", &repo_root_str);

        let claude_hook_path = claude_hooks_dir.join(&hook_name);
        fs::write(&claude_hook_path, &claude_hook).ok();
        #[cfg(unix)]
        set_executable(&claude_hook_path);

        let copilot_hook_path = copilot_hooks_dir.join(&hook_name);
        fs::write(&copilot_hook_path, &copilot_hook).ok();
        #[cfg(unix)]
        set_executable(&copilot_hook_path);
        count += 2;
    }

    count
}

/// Generate all builtin agent templates (rules, skills, preamble, postamble).
///
/// These are project-agnostic defaults that every mockspace consumer gets
/// automatically. Consumer templates with the same filename OVERRIDE builtins.
fn generate_builtin_templates(cfg: &Config) -> BuiltinTemplates {
    let mock_rel = cfg
        .mock_dir
        .strip_prefix(&cfg.repo_root)
        .unwrap_or(&cfg.mock_dir)
        .to_string_lossy()
        .to_string();
    let project_name = &cfg.project_name;
    let crate_prefix = &cfg.crate_prefix;

    // --- Builtin Rules ---

    let rules = vec![
        BuiltinRule {
            name: "generated-agent-rules".to_string(),
            apply_to: vec![
                ".claude/**".to_string(),
                ".github/copilot-instructions.md".to_string(),
                ".github/instructions/**".to_string(),
                ".github/skills/**".to_string(),
                ".github/hooks/**".to_string(),
            ],
            body: substitute_builtin_vars(
                r#"STOP. Do NOT edit files in `.claude/` or `.github/copilot-instructions.md`, `.github/instructions/`, `.github/skills/`, `.github/hooks/`. These are AUTO-GENERATED by `cargo mock`. Edit the source templates in `{mock_dir}/agent/` instead, then run `cargo mock` to regenerate."#,
                &mock_rel, project_name, crate_prefix,
            ),
        },
        BuiltinRule {
            name: "generated-docs".to_string(),
            apply_to: vec![
                "docs/*.md".to_string(),
                "docs/*.dot".to_string(),
                "docs/*.png".to_string(),
                "docs/*.svg".to_string(),
            ],
            body: substitute_builtin_vars(
                concat!(
                    "STOP. Do NOT edit any file directly under `docs/`. These are AUTO-GENERATED by `cargo mock`. ",
                    "Edit the source templates in `{mock_dir}/` (root DESIGN.md.tmpl, WORKFLOW.md.tmpl, PRINCIPLES.md.tmpl) ",
                    "or per-crate templates (crates/*/DESIGN.md.tmpl, crates/*/README.md.tmpl), then run `cargo mock` to regenerate.",
                ),
                &mock_rel, project_name, crate_prefix,
            ),
        },
        BuiltinRule {
            name: "generated".to_string(),
            apply_to: vec![
                "CLAUDE.md".to_string(),
                ".claude/rules/*.md".to_string(),
                ".github/copilot-instructions.md".to_string(),
                ".github/instructions/*.md".to_string(),
            ],
            body: substitute_builtin_vars(
                "These files are AUTO-GENERATED from templates in `{mock_dir}/agent/`. Do not edit directly. Run `cargo mock` to regenerate from source templates.",
                &mock_rel, project_name, crate_prefix,
            ),
        },
        BuiltinRule {
            name: "mock-workspace".to_string(),
            apply_to: vec![format!("{mock_rel}/**")],
            body: substitute_builtin_vars(
                concat!(
                    "## Mock workspace rules\n",
                    "\n",
                    "The mock workspace at `{mock_dir}/` is the design source of truth for {project_name}'s target architecture.\n",
                    "\n",
                    "### Five documentation layers per crate\n",
                    "1. **README.md.tmpl** (3-10 lines) -- crate summary, inserted into root DESIGN.md\n",
                    "2. **DESIGN.md.tmpl** -- shipping contract. Every backticked type name here is expected to exist in source; the `design-doc-source-mismatch` lint enforces it.\n",
                    "3. **BACKLOG.md.tmpl** -- designed-but-deferred promissory notes. Decisions made, not yet shipped. Keep names UNBACKTICKED so the design-doc lint ignores them. Promote items into DESIGN.md.tmpl when they ship; don't duplicate.\n",
                    "4. **SHAME.md.tmpl** -- known gaps. Escape hatch for lints: a `## <key>` header with 50+ word explanation silences a lint violation keyed by `<key>` (type name, changelist filename, etc.).\n",
                    "5. **DEEPDIVE_*.md.tmpl** -- topic-specific deep dives.\n",
                    "\n",
                    "### Design rounds\n",
                    "No design modification without a completed design round document in `design_rounds/`. Each round has \"Current state\" and \"Changes proposed\" sections. When the round supersedes a deprecated CL, the active CL must carry a `## Comparison to deprecated changelist` section (enforced by the `deprecation-comparison` lint).\n",
                    "\n",
                    "### Validation pipeline\n",
                    "1. `cargo check` -- all mock crates must compile\n",
                    "2. Parse -- tree-sitter extracts pub items from lib.rs\n",
                    "3. Lint -- architecture rules enforced\n",
                    "4. Generate -- docs, graphs, agent rules from templates\n",
                    "\n",
                    "### Rules\n",
                    "- Every crate must have `src/lib.rs` and `README.md.tmpl`\n",
                    "- Dependencies in `Cargo.toml` must match the target architecture layers\n",
                ),
                &mock_rel, project_name, crate_prefix,
            ),
        },
        BuiltinRule {
            name: "readmes".to_string(),
            apply_to: vec![
                "**/README.md".to_string(),
                "**/README.md.tmpl".to_string(),
                format!("{mock_rel}/crates/**/*.md"),
                format!("{mock_rel}/crates/**/*.md.tmpl"),
            ],
            body: "## Per-crate documentation templates\nREADME.md.tmpl files are SHORT (3-10 lines). They contain the crate's purpose, what it depends on, and what depends on it. They are inserted into the generated DESIGN.md via {{crate_summaries}}. Do not put detailed design information here -- that goes in DESIGN.md.tmpl or DEEPDIVE_*.md.tmpl.".to_string(),
        },
    ];

    // --- Builtin Skills ---

    let design_round_body = substitute_builtin_vars(
        concat!(
            "# Design round conversation\n",
            "\n",
            "Design rounds are the only way to change the framework's design. This skill\n",
            "codifies the conversational flow for running a design round with the user.\n",
            "\n",
            "## The flow\n",
            "\n",
            "A design round is a series of topic conversations, followed by a changelist,\n",
            "followed by execution. The conversations happen FIRST. No mockspace edits until\n",
            "the changelist is approved.\n",
            "\n",
            "### Step 1: Topic conversations (TOPIC phase)\n",
            "\n",
            "For each topic in the round:\n",
            "\n",
            "1. **Research.** Gather the complete current state. This means ALL mentions\n",
            "   across ALL docs, not just the immediate or similarly named doc. Search the\n",
            "   entire `docs/` directory for every reference to the types, traits, and\n",
            "   concepts under discussion. Include prior design rounds. Note the\n",
            "   generation timestamp of each doc so we know which ones probably supersede\n",
            "   others. Present older docs too; they may contain context that was lost.\n",
            "\n",
            "   Do not read only the `<CRATE>_OVERVIEW.md`. Search for the type name, the\n",
            "   trait name across every `.md` file. If a concept appears in\n",
            "   a deep dive, a different crate's overview, DESIGN.md, PRINCIPLES.md, or a\n",
            "   prior design round, that context matters and must be included.\n",
            "\n",
            "   The mock source is also read, but separately. Never present source findings\n",
            "   without first presenting what ALL docs say. The docs may already answer the\n",
            "   question; if they do, say so. If they contradict each other, say so.\n",
            "\n",
            "2. **Present.** Show the user the current state and your analysis. Be thorough.\n",
            "   Include relevant code paths, type signatures, and cross-crate dependencies.\n",
            "   Lead with what the docs say (with timestamps and locations). Then show where\n",
            "   the source diverges. Never frame a doc-answered question as an open design\n",
            "   question. Never skip presenting a finding because it seems obvious; the user\n",
            "   makes all decisions, not the agent.\n",
            "\n",
            "3. **Ask.** Use AskUserQuestion with premade options (2-4 choices) plus always\n",
            "   leave a free-text \"Other\" option. The user may want to write freeform thoughts.\n",
            "   One question at a time. Do not batch questions.\n",
            "\n",
            "4. **Record.** After the user decides, record the decision in the design round\n",
            "   topic file. Move to the next subtopic or next topic.\n",
            "\n",
            "5. **Repeat.** Continue until all topics in the round have decisions recorded.\n",
            "\n",
            "### Step 2: Doc changelist (enters DOC phase)\n",
            "\n",
            "Only after ALL topic conversations are complete:\n",
            "\n",
            "1. Write the doc changelist: `design_rounds/{YYYYMMDDHHMM}_changelist.doc.md`.\n",
            "2. Per-crate, per-file, mechanical. Every doc template to create, rewrite, or update.\n",
            "3. Section-level detail: what to add, remove, keep.\n",
            "4. Commit the changelist. It can be iteratively updated and recommitted -- the\n",
            "   doc changelist is a living document during DOC phase.\n",
            "\n",
            "The doc changelist's existence opens the **DOC phase**: `*.md.tmpl` doc template\n",
            "edits are now allowed. Source changes (`src/*.rs`) are still blocked.\n",
            "\n",
            "### Step 3: Doc-only execution (DOC phase)\n",
            "\n",
            "Apply all doc template changes listed in the doc changelist:\n",
            "\n",
            "1. Edit `*.md.tmpl` templates per the changelist.\n",
            "2. Commit doc changes. This is the only window for doc template edits.\n",
            "3. Update the doc changelist if needed (iterate). Recommit.\n",
            "\n",
            "### Step 4: Lock docs, plan source (DRAFT phase)\n",
            "\n",
            "When all doc changes are applied and the doc changelist is finalized:\n",
            "\n",
            "1. **Lock the doc changelist**: `cargo mock lock`. This renames\n",
            "   `{YYYYMMDDHHMM}_changelist.doc.md` to `{YYYYMMDDHHMM}_changelist.doc.lock.md`\n",
            "   and commits. Doc templates are now frozen.\n",
            "2. Write the **source changelist**: `design_rounds/{YYYYMMDDHHMM}_changelist.src.md`.\n",
            "   This is written against the actual locked doc state. Per-crate, per-file,\n",
            "   mechanical. Every source file to create, modify, or update. Commit it.\n",
            "\n",
            "### Step 5: Source execution (IMPL phase)\n",
            "\n",
            "The source changelist's existence opens the **IMPL phase**:\n",
            "\n",
            "1. Execute source changes (`src/*.rs`) per the source changelist, in subsequent\n",
            "   commits.\n",
            "2. Validate with `cargo check`. Regenerate docs with `cargo mock`.\n",
            "3. Update the source changelist if needed (iterate). Recommit.\n",
            "\n",
            "### Step 6: Lock source (CLOSED phase)\n",
            "\n",
            "When all source changes are applied:\n",
            "\n",
            "1. **Lock the source changelist**: `cargo mock lock`. Round complete.\n",
            "2. **Close the round**: `cargo mock close`. Archives all files.\n",
            "\n",
            "## File layout — flat while active, subdir after close\n",
            "\n",
            "**Every active-round file lives FLAT at the `design_rounds/` root.**\n",
            "Never create `design_rounds/<timestamp>/<filename>`-style paths during\n",
            "an open round; that's the ARCHIVE location for closed rounds only.\n",
            "\n",
            "Active-round paths (flat):\n",
            "\n",
            "```\n",
            "design_rounds/{YYYYMMDDHHMM}_topic.{name}.md\n",
            "design_rounds/{YYYYMMDDHHMM}_changelist.doc.md          (DOC phase)\n",
            "design_rounds/{YYYYMMDDHHMM}_changelist.doc.lock.md     (after lock)\n",
            "design_rounds/{YYYYMMDDHHMM}_changelist.src.md          (IMPL phase)\n",
            "design_rounds/{YYYYMMDDHHMM}_changelist.src.lock.md     (after lock)\n",
            "```\n",
            "\n",
            "`cargo mock close` is the ONLY step that creates a subdirectory. It\n",
            "moves the flat files into `design_rounds/{YYYYMMDDHHMM}/` as part of\n",
            "archiving the round. Once a round is closed, every file inside its\n",
            "subdirectory is frozen.\n",
            "\n",
            "The `mockspace-write-guard` hook treats any path matching\n",
            "`design_rounds/[^/]+/` as a closed-round archive and denies writes\n",
            "to it at HARD_ERROR. If you hit that deny, check the target path:\n",
            "you almost certainly meant `design_rounds/{timestamp}_topic.{name}.md`\n",
            "(flat), not `design_rounds/{timestamp}/{timestamp}_topic.{name}.md`\n",
            "(subdir = archived).\n",
            "\n",
            "This rule is absolute. Do not mkdir under `design_rounds/` during an\n",
            "open round for any reason; the state machine owns that layout.\n",
            "\n",
            "## Rules\n",
            "\n",
            "- All conversation first. No mockspace edits during topic discussions.\n",
            "- **Active rounds live FLAT in `design_rounds/`.** See File layout above.\n",
            "  Subdirectories under `design_rounds/` are ALWAYS archived-round storage,\n",
            "  never active work. The write-guard hook enforces this at HARD_ERROR.\n",
            "- One question at a time. Never batch multiple questions.\n",
            "- Always offer free-text input as an option. The user's thoughts may not fit\n",
            "  premade choices.\n",
            "- Record decisions in the topic file as they are made.\n",
            "- The doc changelist covers ALL topics in the round. It is the doc execution plan.\n",
            "- The src changelist is written after docs are locked, against actual doc state.\n",
            "- Do not skip either changelist. Without them, execution is ad hoc.\n",
            "- **Topic files are frozen once committed.** A committed topic is history. It\n",
            "  cannot be edited, regardless of phase. To add corrections, create a new topic\n",
            "  file (only possible during TOPIC phase, before a changelist exists).\n",
            "- **No new topics after changelist.** Once a changelist is committed, the round\n",
            "  is crystallized. No new topic files can be created. To add new topics,\n",
            "  deprecate the changelist (`cargo mock deprecate`) and return to TOPIC phase.\n",
            "- **Doc changelist is living during DOC phase only.** It can be iteratively\n",
            "  updated and recommitted during doc execution. After locking (`cargo mock lock`),\n",
            "  it is frozen forever.\n",
            "- **Src changelist is living during IMPL phase only.** Same rules apply.\n",
            "- **Phase gates are global.** Lints check the entire working tree, not just staged\n",
            "  files. Untracked or unstaged changes to blocked paths will block commits. Revert\n",
            "  disallowed changes before committing.\n",
            "- **Lock before source.** Never start source changes until the doc changelist is\n",
            "  locked (`cargo mock lock`) and the source changelist is written.\n",
            "- **Deprecation replaces addendums.** If a changelist needs revision, deprecate\n",
            "  it with `cargo mock deprecate` (or `cargo mock unlock` for locked CLs). Write\n",
            "  a new changelist with a \"Comparison to deprecated changelist\" section.\n",
            "- **Full context, always.** Before presenting any finding, search ALL docs for\n",
            "  every mention of the relevant types, traits, and concepts. Do not\n",
            "  read only the immediate crate doc. Include timestamps so the user can judge\n",
            "  which docs supersede others. Present older/superseded docs too for context.\n",
            "- **Always present for the user's decision.** Never decide on your own that\n",
            "  something is \"clearly a code bug\" and skip presentation. Every finding gets\n",
            "  presented. Every decision is the user's. Even if the docs unambiguously\n",
            "  answer a question, present the docs' answer and let the user confirm.\n",
            "- **Docs before source.** Always present what the docs say first. Then show\n",
            "  where the source diverges. If the docs already answer the question, say so\n",
            "  explicitly when presenting. Never frame a doc-answered question as an open\n",
            "  design question.\n",
            "\n",
            "## What this is NOT\n",
            "\n",
            "- This is not brainstorming. Design rounds have structure: current state,\n",
            "  proposed changes, per-crate scope.\n",
            "- This is not implementation planning. The changelist is the plan. There is\n",
            "  no separate \"implementation plan\" step.\n",
            "- This is not a rubber stamp. The user makes the design decisions. You\n",
            "  research, present options, and record.\n",
        ),
        &mock_rel, project_name, crate_prefix,
    );

    let mockup_workflow_body = substitute_builtin_vars(
        concat!(
            "# Mockup-first workflow\n",
            "\n",
            "All design, documentation, and API changes flow through the mock workspace first.\n",
            "This is the only way to change the framework's design. No exceptions.\n",
            "\n",
            "## Documentation structure\n",
            "\n",
            "DOCUMENTATION LIVES WITH ITS DOMAIN CRATE. Three layers:\n",
            "\n",
            "```\n",
            "{mock_dir}/crates/<crate>/\n",
            "  README.md.tmpl                <- SHORTEST (3-10 lines, for root DESIGN.md)\n",
            "  DESIGN.md.tmpl                <- MIDDLE-LENGTH overview (-> <CRATE>_OVERVIEW.md)\n",
            "  DEEPDIVE_<SUBJECT>.md.tmpl    <- FULL deep dive (-> <CRATE>_<SUBJECT>.md)\n",
            "```\n",
            "\n",
            "The root `DESIGN.md.tmpl` is SHORT: principles + per-crate summaries + links.\n",
            "Domain-specific documentation NEVER goes in root templates.\n",
            "\n",
            "## When this applies\n",
            "\n",
            "- Adding a new trait, type, or extension contract\n",
            "- Changing existing type signatures\n",
            "- Adding a new crate\n",
            "- Updating design documentation\n",
            "- Implementing a feature in a real crate (mock first, then implement)\n",
            "\n",
            "## Steps\n",
            "\n",
            "### 0. Design round (for design changes)\n",
            "\n",
            "If you are changing the framework's design (new types, renamed traits, changed\n",
            "access patterns, new crate, restructured concepts), you MUST create a design\n",
            "round FIRST. See the `design-round` skill for the full conversational flow.\n",
            "\n",
            "The round follows five phases with lint-enforced gates:\n",
            "\n",
            "| Phase | Gate | Docs | Source | CL |\n",
            "|-------|------|------|--------|----|",
            "\n",
            "| TOPIC | no changelists | no | no | n/a |\n",
            "| DOC | `*_changelist.doc.md` | yes | no | doc CL (iterate) |\n",
            "| DRAFT | `*_changelist.doc.lock.md` | no (SHAME ok) | no | src CL creation |\n",
            "| IMPL | `*_changelist.src.md` | no (SHAME ok) | yes | src CL (iterate) |\n",
            "| CLOSED | `*_changelist.src.lock.md` | no | no | no |\n",
            "\n",
            "1. Create topic files in `design_rounds/`. Get them approved. (TOPIC)\n",
            "2. Write doc changelist: `design_rounds/{YYYYMMDDHHMM}_changelist.doc.md`. Commit. (DOC)\n",
            "3. Apply doc template changes per the doc changelist. Commit them. (DOC)\n",
            "4. Lock doc CL: `cargo mock lock`. (DRAFT)\n",
            "5. Write src changelist: `design_rounds/{YYYYMMDDHHMM}_changelist.src.md`. Commit. (IMPL)\n",
            "6. Apply source changes per the src changelist. (IMPL)\n",
            "7. Lock src CL: `cargo mock lock`. (CLOSED)\n",
            "8. Archive: `cargo mock close`.\n",
            "\n",
            "To revise a changelist, deprecate it with `cargo mock deprecate` (unlocked) or\n",
            "`cargo mock unlock` (locked). New CL must include \"Comparison to deprecated\n",
            "changelist\" section.\n",
            "\n",
            "Enforcement is global: lints check the entire working tree (staged + unstaged +\n",
            "untracked). Disallowed changes in any category block commits entirely.\n",
            "\n",
            "If you are only fixing a bug, updating wording, or making a non-design change\n",
            "(implementation in real crates that matches existing mock), skip this step.\n",
            "\n",
            "### 1. Edit the mock workspace\n",
            "\n",
            "```bash\n",
            "cd {mock_dir}\n",
            "```\n",
            "\n",
            "- **Crate design overview**: edit `crates/<crate>/DESIGN.md.tmpl`\n",
            "- **Deep dives**: edit or create `crates/<crate>/DEEPDIVE_<SUBJECT>.md.tmpl`\n",
            "- **Crate summary**: edit `crates/<crate>/README.md.tmpl`\n",
            "- **Types/traits**: edit mock crate sources in `crates/*/src/*.rs`\n",
            "- **Framework-wide docs**: edit root `*.md.tmpl` files\n",
            "- **Agent rules/skills**: edit templates in `agent/` directory\n",
            "- **New crates**: add to `crates/` and `Cargo.toml` members list\n",
            "\n",
            "### 2. Validate\n",
            "\n",
            "```bash\n",
            "cd {mock_dir}\n",
            "cargo check\n",
            "```\n",
            "\n",
            "The mock workspace must compile. Fix errors before proceeding.\n",
            "\n",
            "### 3. Regenerate docs\n",
            "\n",
            "```bash\n",
            "cargo mock\n",
            "```\n",
            "\n",
            "This runs:\n",
            "1. `cargo check` (safety net)\n",
            "2. Lint pass (naming, exports, consistency)\n",
            "3. Clean `docs/` (deletes ALL top-level files; subdirectories untouched)\n",
            "4. Doc generation -> DESIGN.md, STRUCTURE.md, per-crate overviews, deep dives, passthrough templates\n",
            "5. Agent rule generation -> .claude/ (CLAUDE.md, rules, skills, hooks, settings.json) and .github/ (copilot-instructions.md, instructions, skills, hooks)\n",
            "\n",
            "If any step fails, fix the mock and retry.\n",
            "\n",
            "### 4. Real crates (future phase)\n",
            "\n",
            "Real crates do not exist during the design phase. This step applies only after\n",
            "the mockspace is locked and immutable. Until then, your work is done after step 3.\n",
            "\n",
            "When the time comes: match mock signatures in real crate implementations. The\n",
            "mock is the source of truth; real code conforms to it.\n",
            "\n",
            "### 5. Test (future phase)\n",
            "\n",
            "```bash\n",
            "cargo test --workspace\n",
            "cargo clippy --workspace\n",
            "```\n",
            "\n",
            "## What NOT to do\n",
            "\n",
            "- Never edit files in `docs/` directly. They are ALL generated. Changes WILL be lost.\n",
            "- Never edit anything in `.claude/` or `.github/` directly. They are generated from `agent/` templates.\n",
            "- Never add types/traits to real crates without first defining them in the mock.\n",
            "- Never put domain-specific documentation in root `DESIGN.md.tmpl`. Use the crate.\n",
            "- Never skip the `cargo check` validation step.\n",
            "- Never skip the `cargo mock` regeneration step after mock changes.\n",
            "- Never modify doc templates (README.md.tmpl, DESIGN.md.tmpl, DEEPDIVE_*.md.tmpl)\n",
            "  without an unlocked doc changelist in `design_rounds/` (DOC phase).\n",
            "- Never modify source files without a source changelist (`*_changelist.src.md`)\n",
            "  in `design_rounds/` (IMPL phase).\n",
            "- Never create new topic files after a changelist exists. The changelist\n",
            "  crystallizes the round. Deprecate the changelist to return to TOPIC phase.\n",
            "- Never edit a committed topic file. Topics are frozen once committed, always.\n",
            "- Never reference or reason about real crate code during the design phase.\n",
            "  Real crates do not exist. The mock is the only codebase.\n",
            "- Never write discovered rules into memory files, plan files, or session notes.\n",
            "  Write them into mockspace templates (the only persistent documentation).\n",
            "\n",
            "## Generated file headers\n",
            "\n",
            "All generated docs and agent rules start with:\n",
            "\n",
            "```\n",
            "<!--\n",
            "  AUTO-GENERATED -- DO NOT EDIT DIRECTLY\n",
            "  Generated by: mockspace (tools/mockspace)\n",
            "  ...\n",
            "-->\n",
            "```\n",
            "\n",
            "If you see this header, do not edit the file.\n",
        ),
        &mock_rel, project_name, crate_prefix,
    );

    let real_code_guard_body = substitute_builtin_vars(
        concat!(
            "# Real code guard\n",
            "\n",
            "**STOP. Real crates do not exist during the design phase.**\n",
            "\n",
            "The mock workspace is the only codebase. Real crates (`crates/` at the repo root)\n",
            "are not maintained, not referenced, and not part of the current workflow. They may\n",
            "contain legacy code; it is irrelevant.\n",
            "\n",
            "No real code is written until the mockspace is locked and immutable. If you are\n",
            "about to modify a file in `crates/`, `examples/`, or any Rust source outside\n",
            "`{mock_dir}/`: stop. You are in the wrong place.\n",
            "\n",
            "## When this skill applies (future phase)\n",
            "\n",
            "After mockspace lockdown, when implementation begins, the mock workspace MUST\n",
            "reflect the intended design. This is non-negotiable.\n",
            "\n",
            "## Documentation structure reminder\n",
            "\n",
            "Documentation lives with its domain crate in the mock workspace:\n",
            "\n",
            "```\n",
            "{mock_dir}/crates/<crate>/\n",
            "  README.md.tmpl                <- shortest summary (inserted into DESIGN.md)\n",
            "  DESIGN.md.tmpl                <- middle-length overview (-> <CRATE>_OVERVIEW.md)\n",
            "  DEEPDIVE_<SUBJECT>.md.tmpl    <- deep dives (-> <CRATE>_<SUBJECT>.md)\n",
            "```\n",
            "\n",
            "## Checklist before touching real code\n",
            "\n",
            "1. **Mock crate exists?** Check `{mock_dir}/crates/<crate>/src/lib.rs`\n",
            "   has the type, trait, or contract you want to implement.\n",
            "\n",
            "2. **Mock compiles?** Run `cargo check` in `{mock_dir}/`.\n",
            "\n",
            "3. **Docs regenerated?** Run `cargo mock`.\n",
            "   Check generated docs reflect the change.\n",
            "\n",
            "4. **Lints pass?** The `cargo mock` lint pass must complete with zero violations.\n",
            "\n",
            "Only after all four pass should you begin implementing in `crates/`.\n",
            "\n",
            "## What implementation looks like\n",
            "\n",
            "Match the mock signatures. The mock defines the public API contract:\n",
            "- Same type names\n",
            "- Same trait definitions\n",
            "- Same extension contracts\n",
            "\n",
            "The implementation adds:\n",
            "- Real data structures (not `PhantomData` placeholders)\n",
            "- Actual logic (not `todo!()`)\n",
            "- Platform-specific code\n",
            "- Performance optimizations\n",
            "- Tests\n",
            "\n",
            "## What to do if the mock is wrong\n",
            "\n",
            "If the mock has a design flaw discovered during implementation:\n",
            "\n",
            "1. Stop implementing\n",
            "2. Create a design round topic file (`design_rounds/{YYYYMMDDHHMM}_topic.{name}.md`)\n",
            "3. Get the topic approved, write a doc changelist (`*_changelist.doc.md`)\n",
            "4. Apply doc fixes (DOC phase)\n",
            "5. Lock the doc changelist (`cargo mock lock`)\n",
            "6. Write a source changelist (`*_changelist.src.md`) in DRAFT phase\n",
            "7. Apply source fixes (IMPL phase)\n",
            "8. Lock the source changelist (`cargo mock lock`)\n",
            "9. Regenerate docs, then continue implementation\n",
            "\n",
            "Never diverge from the mock \"because it's faster.\" The mock IS the spec.\n",
            "Never modify mock docs without an unlocked doc changelist (DOC phase).\n",
            "Never modify source without a source changelist (IMPL phase).\n",
            "\n",
            "## Exceptions\n",
            "\n",
            "None. If you think you need an exception, you are wrong. Fix the mock.\n",
        ),
        &mock_rel, project_name, crate_prefix,
    );

    let skills = vec![
        BuiltinSkill {
            dir_name: "design-round".to_string(),
            skill_name: "design-round".to_string(),
            skill_description: "Guide for running design round conversations. Use this when starting a new design round, discussing design topics with the user, or when the user asks to brainstorm or design a new subsystem, feature, or architectural change.".to_string(),
            body: design_round_body,
        },
        BuiltinSkill {
            dir_name: "mockup-workflow".to_string(),
            skill_name: "mockup-workflow".to_string(),
            skill_description: "Guide for the mockup-first design and documentation workflow. Use this skill whenever changing framework design, adding or modifying traits, types, crate structure, or regenerating documentation. Also use when asked to implement features in real crates -- the mock must be updated first.".to_string(),
            body: mockup_workflow_body,
        },
        BuiltinSkill {
            dir_name: "real-code-guard".to_string(),
            skill_name: "real-code-guard".to_string(),
            skill_description: "Enforces mock-first workflow when implementing features in real crates. Use this whenever modifying, creating, or refactoring code in the crates/ directory, examples/ directory, or any Rust source file outside the mock workspace. Also use when asked to implement a feature or make a change to the framework.".to_string(),
            body: real_code_guard_body,
        },
    ];

    // --- Builtin Preamble ---
    //
    // Hard-rooted reminders re-stamped on every rule load. Budget enforced by
    // `validate_bookend_size` + the unit test at the bottom of this module.

    let preamble = BUILTIN_PREAMBLE.to_string();

    // --- Builtin Postamble ---

    let postamble = BUILTIN_POSTAMBLE.to_string();

    BuiltinTemplates {
        rules,
        skills,
        preamble,
        postamble,
    }
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

/// Generate agent rules, skills, hooks, and settings from templates in agent/ directory.
///
/// Reads templates from `mock_dir/agent/`, substitutes template variables,
/// and writes dual outputs:
/// - Claude: CLAUDE.md, .claude/rules/*.md, .claude/skills/*/SKILL.md,
///           .claude/hooks/*.sh, .claude/settings.json
/// - Copilot: .github/copilot-instructions.md, .github/instructions/*.instructions.md,
///            .github/skills/*/SKILL.md, .github/hooks/*.sh, .github/hooks/hooks.json
pub fn generate_agent_rules(crates: &CrateMap, cfg: &Config) -> usize {
    let repo_root = &cfg.repo_root;
    let agent_dir = cfg.mock_dir.join("agent");

    // Phase 9: generate builtin templates (always, even without agent/ directory)
    let builtins = generate_builtin_templates(cfg);

    // Collect consumer rule/skill names to determine overrides
    let consumer_rule_names = collect_consumer_rule_names(&agent_dir);
    let consumer_skill_names = collect_consumer_skill_names(&agent_dir);

    let mut vars = compute_template_vars(crates, cfg);
    let header_md = render_design::generation_header_md(cfg);

    // Phase 9: Merge preamble — builtin + consumer (concatenated)
    let consumer_preamble = read_optional_template(&agent_dir.join("PREAMBLE.md.tmpl"));
    validate_bookend_size(&consumer_preamble, "PREAMBLE.md.tmpl");
    let preamble = if consumer_preamble.is_empty() {
        builtins.preamble.clone()
    } else {
        format!("{}\n\n{}", builtins.preamble, consumer_preamble)
    };

    // Phase 9: Merge postamble — builtin + consumer (concatenated)
    let consumer_postamble = read_optional_template(&agent_dir.join("POSTAMBLE.md.tmpl"));
    validate_bookend_size(&consumer_postamble, "POSTAMBLE.md.tmpl");
    let postamble = if consumer_postamble.is_empty() {
        builtins.postamble.clone()
    } else {
        format!("{}\n\n{}", builtins.postamble, consumer_postamble)
    };

    vars.push(("PREAMBLE".to_string(), preamble.clone()));
    vars.push(("POSTAMBLE".to_string(), postamble.clone()));
    let mut count = 0;

    // --- MAIN.md.tmpl -> .claude/CLAUDE.md + .github/copilot-instructions.md ---
    let main_tmpl = agent_dir.join("MAIN.md.tmpl");
    if main_tmpl.is_file() {
        let body = read_and_substitute(&main_tmpl, &vars);

        // Claude: .claude/CLAUDE.md (discovered from .claude/ directory)
        let claude_dir = repo_root.join(".claude");
        let _ = fs::create_dir_all(&claude_dir);
        let claude_content = format_with_bookends(&header_md, &preamble, &body, &postamble);
        let claude_path = claude_dir.join("CLAUDE.md");
        fs::write(&claude_path, &claude_content).expect("failed to write CLAUDE.md");
        eprintln!("  {}", claude_path.display());
        count += 1;

        // Clean up legacy root CLAUDE.md if it exists
        let legacy_path = repo_root.join("CLAUDE.md");
        if legacy_path.is_file() {
            let _ = fs::remove_file(&legacy_path);
            eprintln!("  removed legacy {}", legacy_path.display());
        }

        // Copilot: .github/copilot-instructions.md
        let copilot_dir = repo_root.join(".github");
        let _ = fs::create_dir_all(&copilot_dir);
        let copilot_content = format_with_bookends(&header_md, &preamble, &body, &postamble);
        let copilot_path = copilot_dir.join("copilot-instructions.md");
        fs::write(&copilot_path, copilot_content).expect("failed to write copilot-instructions.md");
        eprintln!("  {}", copilot_path.display());
        count += 1;
    }

    // --- Phase 9: Builtin rules (written first, consumer overrides) ---
    let claude_rules_dir = repo_root.join(".claude").join("rules");
    let copilot_instructions_dir = repo_root.join(".github").join("instructions");
    let _ = fs::create_dir_all(&claude_rules_dir);
    let _ = fs::create_dir_all(&copilot_instructions_dir);

    for builtin_rule in &builtins.rules {
        // Skip if consumer has a template with the same name
        if consumer_rule_names.contains(&builtin_rule.name) {
            eprintln!("  {} (builtin, overridden by consumer)", builtin_rule.name);
            continue;
        }

        // Claude: .claude/rules/<name>.md with paths: frontmatter
        let claude_fm = format_claude_paths(&builtin_rule.apply_to);
        let claude_content = format!(
            "{claude_fm}\n{}",
            format_with_bookends(&header_md, &preamble, &builtin_rule.body, &postamble)
        );
        let claude_path = claude_rules_dir.join(format!("{}.md", builtin_rule.name));
        fs::write(&claude_path, &claude_content).expect("failed to write builtin claude rule");
        eprintln!("  {} (builtin)", claude_path.display());
        count += 1;

        // Copilot: .github/instructions/<name>.instructions.md
        let copilot_fm = format_copilot_apply_to(&builtin_rule.apply_to);
        let copilot_content = format!(
            "{copilot_fm}\n{}",
            format_with_bookends(&header_md, &preamble, &builtin_rule.body, &postamble)
        );
        let copilot_path = copilot_instructions_dir.join(format!("{}.instructions.md", builtin_rule.name));
        fs::write(&copilot_path, &copilot_content)
            .expect("failed to write builtin copilot instruction");
        eprintln!("  {} (builtin)", copilot_path.display());
        count += 1;
    }

    // --- Lint-derived rules and hooks (from forbidden-imports config) ---
    let claude_hooks_dir = repo_root.join(".claude").join("hooks");
    let copilot_hooks_dir = repo_root.join(".github").join("hooks");
    count += generate_lint_derived_content(
        cfg,
        &claude_rules_dir,
        &copilot_instructions_dir,
        &claude_hooks_dir,
        &copilot_hooks_dir,
        &header_md,
        &preamble,
        &postamble,
    );

    // --- Consumer rules/*.md.tmpl -> .claude/rules/*.md + .github/instructions/*.instructions.md ---
    let rules_dir = agent_dir.join("rules");
    if rules_dir.is_dir() {
        let mut entries: Vec<_> = fs::read_dir(&rules_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| {
                e.path()
                    .extension()
                    .map(|x| x == "tmpl")
                    .unwrap_or(false)
            })
            .collect();
        entries.sort_by_key(|e| e.file_name());

        for entry in entries {
            let path = entry.path();
            let raw = fs::read_to_string(&path).expect("failed to read rule template");
            let raw = substitute_vars(&raw, &vars);
            let (frontmatter, body) = split_frontmatter(&raw);
            let apply_to = parse_apply_to(&frontmatter);

            let stem = path
                .file_stem()
                .unwrap()
                .to_string_lossy()
                .trim_end_matches(".md")
                .to_string();

            // Claude: .claude/rules/<name>.md with paths: frontmatter
            let claude_fm = format_claude_paths(&apply_to);
            let claude_content = format!(
                "{claude_fm}\n{}",
                format_with_bookends(&header_md, &preamble, &body, &postamble)
            );
            let claude_path = claude_rules_dir.join(format!("{stem}.md"));
            fs::write(&claude_path, &claude_content).expect("failed to write claude rule");
            eprintln!("  {}", claude_path.display());
            count += 1;

            // Copilot: .github/instructions/<name>.instructions.md with applyTo: frontmatter
            let copilot_fm = format_copilot_apply_to(&apply_to);
            let copilot_content = format!(
                "{copilot_fm}\n{}",
                format_with_bookends(&header_md, &preamble, &body, &postamble)
            );
            let copilot_path = copilot_instructions_dir.join(format!("{stem}.instructions.md"));
            fs::write(&copilot_path, &copilot_content)
                .expect("failed to write copilot instruction");
            eprintln!("  {}", copilot_path.display());
            count += 1;
        }
    }

    // --- Phase 9: Builtin skills (written first, consumer overrides) ---
    let claude_skills_dir = repo_root.join(".claude").join("skills");
    let copilot_skills_dir = repo_root.join(".github").join("skills");

    for builtin_skill in &builtins.skills {
        // Skip if consumer has a skill with the same directory name
        if consumer_skill_names.contains(&builtin_skill.dir_name) {
            eprintln!("  {} (builtin skill, overridden by consumer)", builtin_skill.dir_name);
            continue;
        }

        let skill_fm = format!(
            "---\nname: {}\ndescription: {}\n---",
            builtin_skill.skill_name, builtin_skill.skill_description
        );

        // Claude: .claude/skills/<name>/SKILL.md
        let claude_skill_dir = claude_skills_dir.join(&builtin_skill.dir_name);
        let _ = fs::create_dir_all(&claude_skill_dir);
        let claude_content = format!(
            "{skill_fm}\n{}",
            format_with_bookends(&header_md, &preamble, &builtin_skill.body, &postamble)
        );
        let claude_path = claude_skill_dir.join("SKILL.md");
        fs::write(&claude_path, &claude_content).expect("failed to write builtin claude skill");
        eprintln!("  {} (builtin)", claude_path.display());
        count += 1;

        // Copilot: .github/skills/<name>/SKILL.md
        let copilot_skill_dir = copilot_skills_dir.join(&builtin_skill.dir_name);
        let _ = fs::create_dir_all(&copilot_skill_dir);
        let copilot_content = format!(
            "{skill_fm}\n{}",
            format_with_bookends(&header_md, &preamble, &builtin_skill.body, &postamble)
        );
        let copilot_path = copilot_skill_dir.join("SKILL.md");
        fs::write(&copilot_path, &copilot_content).expect("failed to write builtin copilot skill");
        eprintln!("  {} (builtin)", copilot_path.display());
        count += 1;
    }

    // --- Consumer skills/*/SKILL.md.tmpl -> .claude/skills/*/SKILL.md + .github/skills/*/SKILL.md ---
    let skills_dir = agent_dir.join("skills");
    if skills_dir.is_dir() {
        let mut skill_dirs: Vec<_> = fs::read_dir(&skills_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .collect();
        skill_dirs.sort_by_key(|e| e.file_name());

        for skill_entry in skill_dirs {
            let skill_path = skill_entry.path().join("SKILL.md.tmpl");
            if !skill_path.is_file() {
                continue;
            }

            let skill_name = skill_entry
                .file_name()
                .to_string_lossy()
                .to_string();

            let raw = fs::read_to_string(&skill_path).expect("failed to read skill template");
            let (frontmatter, body) = split_frontmatter(&raw);
            let body = substitute_vars(&body, &vars);
            let name = parse_field(&frontmatter, "skill_name").unwrap_or(skill_name.clone());
            let desc = parse_field(&frontmatter, "skill_description").unwrap_or_default();

            // Both Claude and Copilot use the same skill frontmatter format
            let skill_fm = format!("---\nname: {name}\ndescription: {desc}\n---");

            // Claude: .claude/skills/<name>/SKILL.md
            let claude_skill_dir = claude_skills_dir.join(&skill_name);
            let _ = fs::create_dir_all(&claude_skill_dir);
            let claude_content = format!(
                "{skill_fm}\n{}",
                format_with_bookends(&header_md, &preamble, &body, &postamble)
            );
            let claude_path = claude_skill_dir.join("SKILL.md");
            fs::write(&claude_path, &claude_content).expect("failed to write claude skill");
            eprintln!("  {}", claude_path.display());
            count += 1;

            // Copilot: .github/skills/<name>/SKILL.md
            let copilot_skill_dir = copilot_skills_dir.join(&skill_name);
            let _ = fs::create_dir_all(&copilot_skill_dir);
            let copilot_content = format!(
                "{skill_fm}\n{}",
                format_with_bookends(&header_md, &preamble, &body, &postamble)
            );
            let copilot_path = copilot_skill_dir.join("SKILL.md");
            fs::write(&copilot_path, &copilot_content).expect("failed to write copilot skill");
            eprintln!("  {}", copilot_path.display());
            count += 1;
        }
    }

    // --- Phase 6: Builtin hooks (generated BEFORE consumer hooks) ---
    let claude_hooks_dir = repo_root.join(".claude").join("hooks");
    let copilot_hooks_dir = repo_root.join(".github").join("hooks");
    let _ = fs::create_dir_all(&claude_hooks_dir);
    let _ = fs::create_dir_all(&copilot_hooks_dir);

    let mut all_hooks: Vec<HookMeta> =
        generate_builtin_hooks(cfg, &claude_hooks_dir, &copilot_hooks_dir, &mut count);

    // --- Consumer hooks: hooks/*.sh.tmpl -> .claude/hooks/*.sh + .github/hooks/*.sh ---
    let hooks_dir = agent_dir.join("hooks");
    if hooks_dir.is_dir() {
        let mut entries: Vec<_> = fs::read_dir(&hooks_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| {
                let name = e.file_name().to_string_lossy().to_string();
                name.ends_with(".sh.tmpl")
            })
            .collect();
        entries.sort_by_key(|e| e.file_name());

        for entry in entries {
            let path = entry.path();
            let tmpl_name = entry.file_name().to_string_lossy().to_string();
            // Strip .tmpl suffix: "check-byline.sh.tmpl" -> "check-byline.sh"
            let out_name = tmpl_name.trim_end_matches(".tmpl");

            let template = fs::read_to_string(&path).expect("failed to read hook template");

            // Parse matchers from frontmatter or fall back to naming convention
            let matchers = parse_hook_matchers(&template)
                .unwrap_or_else(|| matchers_from_name(out_name));

            // substitute general template variables first
            let template = substitute_vars(&template, &vars);

            let repo_root_str = cfg.repo_root.to_string_lossy();

            // Claude: tool_input.field, hookSpecificOutput wrapper
            let claude_content = template
                .replace("{{HOOK_HELPERS}}", CLAUDE_HOOK_HELPERS)
                .replace("{{REPO_ROOT}}", &repo_root_str);
            let claude_path = claude_hooks_dir.join(out_name);
            fs::write(&claude_path, &claude_content).expect("failed to write claude hook");
            #[cfg(unix)]
            set_executable(&claude_path);
            eprintln!("  {}", claude_path.display());
            count += 1;

            // Copilot: toolArgs (stringified JSON), flat output
            let copilot_content = template
                .replace("{{HOOK_HELPERS}}", COPILOT_HOOK_HELPERS)
                .replace("{{REPO_ROOT}}", &repo_root_str);
            let copilot_path = copilot_hooks_dir.join(out_name);
            fs::write(&copilot_path, &copilot_content).expect("failed to write copilot hook");
            #[cfg(unix)]
            set_executable(&copilot_path);
            eprintln!("  {}", copilot_path.display());
            count += 1;

            all_hooks.push(HookMeta {
                name: out_name.to_string(),
                matchers,
            });
        }
    }

    // --- Phase 7: Auto-generate settings from discovered hooks ---
    count += generate_settings(repo_root, &all_hooks);

    count
}

/// Collect consumer rule template names (stems without .md.tmpl extension).
fn collect_consumer_rule_names(agent_dir: &Path) -> std::collections::HashSet<String> {
    let mut names = std::collections::HashSet::new();
    let rules_dir = agent_dir.join("rules");
    if rules_dir.is_dir() {
        if let Ok(entries) = fs::read_dir(&rules_dir) {
            for entry in entries.filter_map(|e| e.ok()) {
                let path = entry.path();
                if path.extension().map(|x| x == "tmpl").unwrap_or(false) {
                    if let Some(stem) = path.file_stem() {
                        let name = stem.to_string_lossy()
                            .trim_end_matches(".md")
                            .to_string();
                        names.insert(name);
                    }
                }
            }
        }
    }
    names
}

/// Collect consumer skill directory names.
fn collect_consumer_skill_names(agent_dir: &Path) -> std::collections::HashSet<String> {
    let mut names = std::collections::HashSet::new();
    let skills_dir = agent_dir.join("skills");
    if skills_dir.is_dir() {
        if let Ok(entries) = fs::read_dir(&skills_dir) {
            for entry in entries.filter_map(|e| e.ok()) {
                let path = entry.path();
                if path.is_dir() && path.join("SKILL.md.tmpl").is_file() {
                    if let Some(name) = path.file_name() {
                        names.insert(name.to_string_lossy().to_string());
                    }
                }
            }
        }
    }
    names
}

/// Compute template variables from parsed crate data.
fn compute_template_vars(crates: &CrateMap, cfg: &Config) -> Vec<(String, String)> {
    let mut vars = Vec::new();

    // {{project_name}}
    vars.push(("project_name".to_string(), cfg.project_name.clone()));

    // {{mock_dir}} — relative path from repo root to mock workspace
    let mock_rel = cfg.mock_dir
        .strip_prefix(&cfg.repo_root)
        .unwrap_or(&cfg.mock_dir)
        .to_string_lossy()
        .to_string();
    vars.push(("mock_dir".to_string(), mock_rel));

    // {{crate_count}}
    let crate_count = crates
        .values()
        .filter(|c| c.short_name != cfg.project_name)
        .count();
    vars.push(("crate_count".to_string(), crate_count.to_string()));

    // {{crate_table}}
    vars.push(("crate_table".to_string(), compute_crate_table(crates, cfg)));

    // {{macro_table}}
    vars.push(("macro_table".to_string(), compute_macro_table(crates, cfg)));

    vars
}

/// Build a markdown table of crates.
fn compute_crate_table(crates: &CrateMap, cfg: &Config) -> String {
    let mut table = String::new();
    writeln!(table, "| Crate | Purpose |").unwrap();
    writeln!(table, "|-------|---------|").unwrap();

    let mut sorted: Vec<_> = crates.iter().collect();
    sorted.sort_by_key(|(_, c)| &c.short_name);

    let prefix = &cfg.crate_prefix;
    let prefix_dash = format!("{prefix}-");
    for (dir_name, info) in sorted {
        if info.short_name == cfg.project_name {
            continue;
        }
        let display_name = if dir_name.starts_with(&prefix_dash) {
            format!("{prefix}-{}", info.short_name)
        } else {
            // crate name doesn't have the workspace prefix — use as-is
            dir_name.clone()
        };
        let purpose = infer_crate_purpose(info);
        writeln!(table, "| {display_name} | {purpose} |").unwrap();
    }

    table.trim_end().to_string()
}

/// Infer a one-line purpose from a crate's items.
fn infer_crate_purpose(info: &CrateInfo) -> String {
    let mut types: Vec<String> = Vec::new();
    for item in &info.items {
        match item {
            Item::Trait(t) => types.push(t.name.clone()),
            Item::Struct(s) => types.push(s.name.clone()),
            _ => {}
        }
    }
    if types.is_empty() {
        return format!("{} subsystem", info.short_name);
    }
    let max = 3.min(types.len());
    let shown: Vec<_> = types[..max].iter().map(|t| format!("`{t}`")).collect();
    let suffix = if types.len() > max {
        format!(" +{}", types.len() - max)
    } else {
        String::new()
    };
    format!("{}{suffix}", shown.join(", "))
}

/// Build the macros table for agent instructions from config.
fn compute_macro_table(crates: &CrateMap, cfg: &Config) -> String {
    let macros = cfg.effective_agent_macros();

    // Check which macros actually exist
    let mut found = std::collections::BTreeSet::new();
    for info in crates.values() {
        for item in &info.items {
            if let Item::Macro(m) = item {
                if m.name.starts_with("define_") {
                    found.insert(m.name.clone());
                }
            }
        }
    }

    let mut table = String::new();
    writeln!(table, "| Macro | Purpose | Usage |").unwrap();
    writeln!(table, "|-------|---------|-------|").unwrap();

    for (name, purpose, usage) in macros {
        if found.contains(name.as_str()) {
            writeln!(table, "| `{name}!` | {purpose} | {usage} |").unwrap();
        }
    }

    // Any extra macros not in config
    for name in &found {
        if !macros.iter().any(|(n, _, _)| n == name) {
            writeln!(table, "| `{name}!` | Custom | `{name}!(...)` |").unwrap();
        }
    }

    table.trim_end().to_string()
}

/// Read a template file and substitute variables.
fn read_and_substitute(path: &Path, vars: &[(String, String)]) -> String {
    let raw = fs::read_to_string(path).expect("failed to read template");
    let (_frontmatter, body) = split_frontmatter(&raw);
    substitute_vars(&body, vars)
}

/// Replace {{var}} placeholders in text.
fn substitute_vars(text: &str, vars: &[(String, String)]) -> String {
    let mut result = text.to_string();
    for (key, value) in vars {
        result = result.replace(&format!("{{{{{key}}}}}"), value);
    }
    result
}

/// Split YAML frontmatter from body content.
fn split_frontmatter(text: &str) -> (String, String) {
    let trimmed = text.trim_start();
    if !trimmed.starts_with("---") {
        return (String::new(), text.to_string());
    }

    let after_first = &trimmed[3..];
    if let Some(end) = after_first.find("\n---") {
        let fm = after_first[..end].to_string();
        let body = after_first[end + 4..].to_string();
        (fm, body)
    } else {
        (String::new(), text.to_string())
    }
}

/// Parse apply_to field from frontmatter YAML.
fn parse_apply_to(frontmatter: &str) -> Vec<String> {
    let mut patterns = Vec::new();
    let mut in_list = false;

    for line in frontmatter.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("apply_to:") {
            let value = trimmed.trim_start_matches("apply_to:").trim();
            if value.starts_with('[') {
                // Inline array: ["pattern1", "pattern2"]
                let inner = value.trim_start_matches('[').trim_end_matches(']');
                for item in inner.split(',') {
                    let p = item.trim().trim_matches('"').trim_matches('\'');
                    if !p.is_empty() {
                        patterns.push(p.to_string());
                    }
                }
            } else if value.is_empty() {
                in_list = true;
            } else {
                patterns.push(value.trim_matches('"').trim_matches('\'').to_string());
            }
        } else if in_list && trimmed.starts_with("- ") {
            let p = trimmed[2..].trim().trim_matches('"').trim_matches('\'');
            if !p.is_empty() {
                patterns.push(p.to_string());
            }
        } else if in_list && !trimmed.is_empty() && !trimmed.starts_with('#') {
            in_list = false;
        }
    }

    patterns
}

/// Parse a simple key: value field from frontmatter.
fn parse_field(frontmatter: &str, key: &str) -> Option<String> {
    let prefix = format!("{key}:");
    for line in frontmatter.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with(&prefix) {
            let value = trimmed[prefix.len()..].trim();
            return Some(value.trim_matches('"').trim_matches('\'').to_string());
        }
    }
    None
}

/// Format glob patterns as Claude's paths: YAML list.
fn format_claude_paths(patterns: &[String]) -> String {
    if patterns.is_empty() {
        return String::new();
    }
    let mut fm = String::from("---\npaths:\n");
    for p in patterns {
        writeln!(fm, "  - \"{p}\"").unwrap();
    }
    fm.push_str("---");
    fm
}

/// Format glob patterns as Copilot's applyTo: string.
fn format_copilot_apply_to(patterns: &[String]) -> String {
    if patterns.is_empty() {
        return String::new();
    }
    let joined = patterns.join(",");
    format!("---\napplyTo: \"{joined}\"\n---")
}

/// Read an optional template file, returning empty string if missing.
fn read_optional_template(path: &Path) -> String {
    if path.is_file() {
        let raw = fs::read_to_string(path).unwrap_or_default();
        let (_fm, body) = split_frontmatter(&raw);
        body.trim().to_string()
    } else {
        String::new()
    }
}

/// Assemble content with preamble before body and postamble after.
/// Maximum word count for each of the built-in and consumer-authored
/// preamble/postamble bookends. Bookends are re-stamped on every rule
/// file and every skill body, so keeping them under this budget prevents
/// context bloat when multiple rules load simultaneously.
pub const BOOKEND_MAX_WORDS: usize = 25;

/// Built-in preamble stamped before every rule body and MAIN instructions.
/// Must stay within `BOOKEND_MAX_WORDS` — enforced by unit test below.
pub const BUILTIN_PREAMBLE: &str = concat!(
    "> **MOCKSPACE:** docs=design. source=untrusted. ",
    "Lints never exempt — stop if blocked. ",
    "Flow: topic → doc CL → lock → src CL → lock → close. ",
    "No shortcuts.",
);

/// Built-in postamble stamped after every rule body and MAIN instructions.
/// Must stay within `BOOKEND_MAX_WORDS` — enforced by unit test below.
pub const BUILTIN_POSTAMBLE: &str = concat!(
    "---\n",
    "> **VERIFY:** lint-only --commit green? src CL covers it? ",
    "Never edit `.claude/`/`.github/` directly. ",
    "Deprecate, never addendum.",
);

/// Count words in a markdown fragment, ignoring markdown syntax, HTML
/// comments, and frontmatter. A "word" is any run of non-whitespace
/// separated by whitespace, minus tokens that are purely punctuation.
fn count_bookend_words(text: &str) -> usize {
    let mut clean = String::with_capacity(text.len());
    let mut in_html_comment = false;
    let mut chars = text.chars().peekable();
    while let Some(c) = chars.next() {
        if !in_html_comment && c == '<' {
            let rest: String = chars.clone().take(3).collect();
            if rest.starts_with("!--") {
                in_html_comment = true;
                continue;
            }
        }
        if in_html_comment {
            if c == '-' {
                let rest: String = chars.clone().take(2).collect();
                if rest.starts_with("->") {
                    chars.next();
                    chars.next();
                    in_html_comment = false;
                }
            }
            continue;
        }
        clean.push(c);
    }
    clean
        .split_whitespace()
        .filter(|w| w.chars().any(|c| c.is_alphanumeric()))
        .count()
}

/// Validate a consumer-authored preamble/postamble template against the
/// word budget. Prints a cargo::warning on overflow — non-fatal so
/// existing consumers aren't broken, but visible every `cargo mock` run.
fn validate_bookend_size(content: &str, filename: &str) {
    if content.is_empty() {
        return;
    }
    let words = count_bookend_words(content);
    if words > BOOKEND_MAX_WORDS {
        eprintln!(
            "cargo::warning=mockspace: {filename} is {words} words ({} over budget). \
             Bookends are re-stamped on every rule/skill load; tight constant \
             reminders only. Move longer invariants into MAIN.md.tmpl.",
            words - BOOKEND_MAX_WORDS
        );
    }
}

fn format_with_bookends(header: &str, preamble: &str, body: &str, postamble: &str) -> String {
    let mut out = String::new();
    out.push_str(header);
    out.push('\n');
    if !preamble.is_empty() {
        out.push('\n');
        out.push_str(preamble);
        out.push('\n');
    }
    out.push('\n');
    out.push_str(body);
    if !postamble.is_empty() {
        out.push('\n');
        out.push_str(postamble);
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtin_preamble_within_budget() {
        let words = count_bookend_words(BUILTIN_PREAMBLE);
        assert!(
            words <= BOOKEND_MAX_WORDS,
            "BUILTIN_PREAMBLE is {words} words; budget is {BOOKEND_MAX_WORDS}. \
             Tight constant reminders only — longer content belongs in MAIN.md.tmpl."
        );
    }

    #[test]
    fn builtin_postamble_within_budget() {
        let words = count_bookend_words(BUILTIN_POSTAMBLE);
        assert!(
            words <= BOOKEND_MAX_WORDS,
            "BUILTIN_POSTAMBLE is {words} words; budget is {BOOKEND_MAX_WORDS}."
        );
    }

    #[test]
    fn word_count_strips_html_comments() {
        let text = "real words <!-- this block of ignored words --> more real";
        assert_eq!(count_bookend_words(text), 4);
    }

    #[test]
    fn word_count_ignores_pure_punctuation() {
        let text = "one two -- three --- four";
        assert_eq!(count_bookend_words(text), 4);
    }

    #[test]
    fn phase_labels_lock_down_user_visible_strings() {
        use mockspace_lint_rules::changelist_helpers::Phase;
        // These five strings flow into deny messages, status output,
        // README and USAGE_GUIDE tables, and the generated agent skill
        // text. Treat them as a public contract; #227 renamed
        // SRC-PLAN/SRC/DONE to DRAFT/IMPL/CLOSED so the verb `lock` in
        // `cargo mock lock` reads consistently with file-suffix state.
        assert_eq!(Phase::Topic.label(), "TOPIC");
        assert_eq!(Phase::Doc.label(), "DOC");
        assert_eq!(Phase::SrcPlan.label(), "DRAFT");
        assert_eq!(Phase::Src.label(), "IMPL");
        assert_eq!(Phase::Done.label(), "CLOSED");
    }

    #[test]
    fn write_guard_uses_new_phase_labels() {
        // Regression check for #227: bash hook PHASE values must match
        // the new user-visible labels. If a stray "SRC-PLAN" / "SRC" /
        // "DONE" survives the rename, the rendered deny messages will
        // contradict the docs and Phase::label().
        let tmp = tempfile::tempdir().expect("tempdir");
        let mock_dir = tmp.path().join("mock");
        std::fs::create_dir(&mock_dir).expect("create mock dir");
        let cfg = Config::from_dir(&mock_dir);
        let hook = builtin_write_guard(&cfg);

        for new_label in ["DRAFT", "IMPL", "CLOSED"] {
            assert!(
                hook.contains(new_label),
                "rendered hook must reference new phase label `{new_label}`"
            );
        }
        for old_label in ["SRC-PLAN", "\"SRC\"", "\"DONE\""] {
            assert!(
                !hook.contains(old_label),
                "rendered hook still contains old phase token `{old_label}`"
            );
        }
    }

    #[test]
    fn write_guard_phase_detection_is_cwd_independent() {
        // Regression test for #257: phase-detection git invocations must
        // run with `git -C "$REPO_ROOT"` so they resolve repo-relative
        // pathspecs regardless of the caller's cwd.
        let tmp = tempfile::tempdir().expect("tempdir");
        let mock_dir = tmp.path().join("mock");
        std::fs::create_dir(&mock_dir).expect("create mock dir");
        let cfg = Config::from_dir(&mock_dir);
        let hook = builtin_write_guard(&cfg);

        // Phase-detection ls-files calls (4) and the dirty-docs diff and
        // the per-file --error-unmatch lookup all need the -C form.
        let phase_marker = "git -C \"$REPO_ROOT\" ls-files \"${MOCK_ROOT}/design_rounds/\"";
        let phase_calls = hook.matches(phase_marker).count();
        assert_eq!(
            phase_calls, 4,
            "expected 4 phase-detection ls-files calls with `-C \"$REPO_ROOT\"`, got {phase_calls}"
        );

        assert!(
            hook.contains("git -C \"$REPO_ROOT\" diff --name-only"),
            "DIRTY_DOCS query must use -C \"$REPO_ROOT\" so cwd-relative paths in the diff don't bypass the regex"
        );
        assert!(
            hook.contains("git -C \"$REPO_ROOT\" ls-files --error-unmatch \"$FULL_GIT_PATH\""),
            "FULL_GIT_PATH lookup must use -C \"$REPO_ROOT\" since the path is repo-rooted"
        );

        // Negative: no remaining bare ls-files / diff invocations slipped through.
        assert!(
            !hook.contains("\ngit ls-files "),
            "found bare `git ls-files` (cwd-sensitive); switch to `git -C \"$REPO_ROOT\" ls-files`"
        );
        assert!(
            !hook.contains("\ngit diff "),
            "found bare `git diff` (cwd-sensitive); switch to `git -C \"$REPO_ROOT\" diff`"
        );
    }
}
