use std::collections::BTreeMap;
use std::fmt::Write;
use std::fs;
use std::path::Path;

use crate::config::Config;
use crate::graph;
use crate::model::*;

/// Generate a markdown generation header with timestamp.
pub fn generation_header_md(cfg: &Config) -> String {
    let mock_rel = cfg.mock_dir.strip_prefix(&cfg.repo_root)
        .map(|p| p.display().to_string())
        .unwrap_or_else(|_| cfg.mock_dir.display().to_string());
    let mut hdr = String::new();
    let timestamp = now_rfc3339();

    writeln!(hdr, "<!--").unwrap();
    writeln!(hdr, "  AUTO-GENERATED — DO NOT EDIT DIRECTLY").unwrap();
    writeln!(hdr, "").unwrap();
    writeln!(hdr, "  Generated by: mockspace ({mock_rel})").unwrap();
    writeln!(hdr, "  Generated at: {timestamp}").unwrap();
    writeln!(hdr, "  Source: {mock_rel}/").unwrap();
    writeln!(hdr, "  To regenerate: cargo mock").unwrap();
    writeln!(hdr, "-->").unwrap();

    hdr
}

/// Generate a DOT comment header with timestamp.
pub fn generation_header_dot(cfg: &Config) -> String {
    let mock_rel = cfg.mock_dir.strip_prefix(&cfg.repo_root)
        .map(|p| p.display().to_string())
        .unwrap_or_else(|_| cfg.mock_dir.display().to_string());
    let mut hdr = String::new();
    let timestamp = now_rfc3339();

    writeln!(hdr, "// AUTO-GENERATED — DO NOT EDIT DIRECTLY").unwrap();
    writeln!(hdr, "//").unwrap();
    writeln!(hdr, "// Generated by: mockspace ({mock_rel})").unwrap();
    writeln!(hdr, "// Generated at: {timestamp}").unwrap();
    writeln!(hdr, "// Source: {mock_rel}/").unwrap();
    writeln!(hdr, "// To regenerate: cargo mock").unwrap();
    writeln!(hdr).unwrap();

    hdr
}

/// Generate an SVG comment to prepend before the SVG content.
pub fn generation_header_svg(cfg: &Config) -> String {
    let mock_rel = cfg.mock_dir.strip_prefix(&cfg.repo_root)
        .map(|p| p.display().to_string())
        .unwrap_or_else(|_| cfg.mock_dir.display().to_string());
    let mut hdr = String::new();
    let timestamp = now_rfc3339();

    writeln!(hdr, "<!--").unwrap();
    writeln!(hdr, "  AUTO-GENERATED — DO NOT EDIT DIRECTLY").unwrap();
    writeln!(hdr, "").unwrap();
    writeln!(hdr, "  Generated by: mockspace ({mock_rel})").unwrap();
    writeln!(hdr, "  Generated at: {timestamp}").unwrap();
    writeln!(hdr, "  Source: {mock_rel}/").unwrap();
    writeln!(hdr, "  To regenerate: cargo mock").unwrap();
    writeln!(hdr, "-->").unwrap();

    hdr
}

/// Generate DESIGN.md from DESIGN.md.tmpl + parsed crate data.
pub fn generate_design_md(crates: &CrateMap, cfg: &Config) -> Option<String> {
    let tmpl_path = cfg.mock_dir.join("DESIGN.md.tmpl");
    let template = match fs::read_to_string(&tmpl_path) {
        Ok(t) => t,
        Err(e) => {
            eprintln!("  warning: no DESIGN.md.tmpl found: {e}");
            return None;
        }
    };

    let header = generation_header_md(cfg);
    let crate_count = crates.len().to_string();
    let macros_table = compute_macros_table(crates, cfg);
    let primary_items = compute_primary_items_per_crate(crates, cfg);
    let crate_layers = compute_crate_layers(crates, cfg);
    let deep_dives = collect_deep_dives(&cfg.mock_dir);
    let crate_summaries = compute_crate_summaries(&cfg.mock_dir);

    let mock_rel = cfg.mock_dir
        .strip_prefix(&cfg.repo_root)
        .unwrap_or(&cfg.mock_dir)
        .to_string_lossy()
        .to_string();

    let mut result = template.clone();
    result = result.replace("{{project_name}}", &cfg.project_name);
    result = result.replace("{{mock_dir}}", &mock_rel);
    result = result.replace("{{crate_count}}", &crate_count);
    result = result.replace("{{macros_table}}", &macros_table);
    // Provide both generic and legacy variable names
    result = result.replace("{{signals_per_crate}}", &primary_items);
    result = result.replace("{{primary_items_per_crate}}", &primary_items);
    result = result.replace("{{crate_layers}}", &crate_layers);
    result = result.replace("{{deep_dives}}", &deep_dives);
    result = result.replace("{{crate_summaries}}", &crate_summaries);

    Some(format!("{header}\n{result}"))
}

/// Compute the macros table from config + crate scan.
fn compute_macros_table(crates: &CrateMap, cfg: &Config) -> String {
    // Scan for actually-present macros
    let mut found: BTreeMap<String, bool> = BTreeMap::new();
    for info in crates.values() {
        for item in &info.items {
            if let Item::Macro(m) = item {
                if m.name.starts_with("define_") {
                    found.insert(m.name.clone(), true);
                }
            }
        }
    }

    let mut table = String::new();
    writeln!(table, "| Need | Macro |").unwrap();
    writeln!(table, "|------|-------|").unwrap();

    // Configured macros first (preserves config order)
    for (name, desc, usage) in &cfg.known_macros {
        if found.contains_key(name.as_str()) {
            writeln!(table, "| {desc} | {usage} |").unwrap();
            found.remove(name.as_str());
        }
    }

    // Any extra macros not in config
    for name in found.keys() {
        writeln!(table, "| Custom | `{name}!(...)` |").unwrap();
    }

    table.trim_end().to_string()
}

/// Compute per-crate table for the primary domain macro.
fn compute_primary_items_per_crate(crates: &CrateMap, cfg: &Config) -> String {
    let primary = match &cfg.primary_domain_macro {
        Some(m) => m.as_str(),
        None => return format!("*No primary domain macro configured.*"),
    };
    let label = &cfg.primary_domain_label;

    let mut items_by_crate: BTreeMap<String, Vec<String>> = BTreeMap::new();

    for info in crates.values() {
        let short = &info.short_name;
        if short == &cfg.project_name { continue; }
        for mg in &info.macro_generated {
            if mg.macro_name == primary {
                items_by_crate
                    .entry(short.clone())
                    .or_default()
                    .push(mg.generated_name.clone());
            }
        }
    }

    if items_by_crate.is_empty() {
        return format!("*No {} found in any crate.*", label.to_lowercase());
    }

    let mut table = String::new();
    writeln!(table, "| Crate | {label} |").unwrap();
    writeln!(table, "|-------|{}|", "-".repeat(label.len() + 2)).unwrap();

    for (crate_name, mut items) in items_by_crate {
        items.sort();
        let formatted = items.iter().map(|s| format!("`{s}`")).collect::<Vec<_>>().join(", ");
        writeln!(table, "| {crate_name} | {formatted} |").unwrap();
    }

    table.trim_end().to_string()
}

/// Compute the crate layers section.
fn compute_crate_layers(crates: &CrateMap, cfg: &Config) -> String {
    let mut depth_cache = BTreeMap::new();
    let mut depths = BTreeMap::new();
    for name in crates.keys() {
        depths.insert(name.clone(), graph::compute_depth(name, crates, &mut depth_cache));
    }
    let max_depth = depths.values().copied().max().unwrap_or(0);

    let mut by_depth: Vec<Vec<String>> = vec![Vec::new(); max_depth + 1];
    for (name, &d) in &depths {
        let short = &crates[name.as_str()].short_name;
        if short == &cfg.project_name { continue; }
        by_depth[d].push(short.clone());
    }

    let mut layers = String::new();
    writeln!(layers, "```").unwrap();
    for (d, names) in by_depth.iter().enumerate() {
        if names.is_empty() { continue; }
        let label = cfg.layer_label(d);
        let mut sorted = names.clone();
        sorted.sort();
        let joined = sorted.join(", ");
        let pad = if d < 10 { " " } else { "" };
        writeln!(layers, "Layer {d}{pad}({label:14}): {joined}").unwrap();
    }
    writeln!(layers, "```").unwrap();

    layers.trim_end().to_string()
}

/// Collect deep-dive markdown files from per-crate DEEPDIVE_*.md.tmpl files.
fn collect_deep_dives(mock_dir: &Path) -> String {
    let crates_dir = mock_dir.join("crates");
    if !crates_dir.is_dir() {
        return String::new();
    }

    let mut all_dives = Vec::new();

    let mut crate_dirs: Vec<_> = fs::read_dir(&crates_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .collect();
    crate_dirs.sort_by_key(|e| e.file_name());

    for crate_entry in crate_dirs {
        let crate_path = crate_entry.path();
        let mut entries: Vec<_> = fs::read_dir(&crate_path)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| {
                let name = e.file_name().to_string_lossy().to_string();
                name.starts_with("DEEPDIVE_") && name.ends_with(".md.tmpl")
            })
            .collect();
        entries.sort_by_key(|e| e.file_name());

        for entry in entries {
            if let Ok(content) = fs::read_to_string(entry.path()) {
                all_dives.push(content.trim().to_string());
            }
        }
    }

    all_dives.join("\n\n")
}

/// Get current timestamp as RFC 3339.
fn now_rfc3339() -> String {
    use std::process::Command;
    let output = Command::new("date")
        .arg("-u")
        .arg("+%Y-%m-%dT%H:%M:%SZ")
        .output();
    match output {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout).trim().to_string(),
        _ => "unknown".to_string(),
    }
}

/// Generate standalone DESIGN-DEEP-DIVES.md from per-crate DEEPDIVE_*.md.tmpl files.
pub fn generate_deep_dives_md(cfg: &Config) -> String {
    let header = generation_header_md(cfg);
    let dives = collect_deep_dives(&cfg.mock_dir);
    if dives.is_empty() {
        return String::new();
    }

    let name = &cfg.project_name;
    let mut md = String::new();
    writeln!(md, "{header}").unwrap();
    writeln!(md, "# {name} — Deep Dives").unwrap();
    writeln!(md).unwrap();
    writeln!(md, "> Detailed technical deep dives into {name} subsystems.").unwrap();
    writeln!(md, "> See also: [DESIGN.md](DESIGN.md) for the high-level design.").unwrap();
    writeln!(md).unwrap();
    writeln!(md, "---").unwrap();
    writeln!(md).unwrap();
    writeln!(md, "{dives}").unwrap();

    md
}

/// Compute crate summaries from per-crate README.md.tmpl files.
fn compute_crate_summaries(mock_dir: &Path) -> String {
    let crates_dir = mock_dir.join("crates");
    if !crates_dir.is_dir() {
        return String::new();
    }

    let mut crate_dirs: Vec<_> = fs::read_dir(&crates_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .collect();
    crate_dirs.sort_by_key(|e| e.file_name());

    let mut summaries = String::new();

    for crate_entry in crate_dirs {
        let crate_path = crate_entry.path();
        let crate_name = crate_entry.file_name().to_string_lossy().to_string();
        let readme_path = crate_path.join("README.md.tmpl");

        if let Ok(content) = fs::read_to_string(&readme_path) {
            writeln!(summaries, "{}", content.trim()).unwrap();

            let has_design = crate_path.join("DESIGN.md.tmpl").exists();
            let deep_dives = find_deep_dives(&crate_path);

            if has_design || !deep_dives.is_empty() {
                writeln!(summaries).unwrap();
                let crate_upper = crate_name.to_uppercase().replace('-', "_");
                if has_design {
                    writeln!(summaries, "- [Overview]({crate_upper}_OVERVIEW.md)").unwrap();
                }
                for (subject, _) in &deep_dives {
                    let subject_upper = subject.to_uppercase();
                    writeln!(summaries, "- [{subject} deep dive]({crate_upper}_{subject_upper}.md)").unwrap();
                }
            }

            writeln!(summaries).unwrap();
        }
    }

    summaries.trim_end().to_string()
}

/// Find DEEPDIVE_*.md.tmpl files in a crate directory.
fn find_deep_dives(crate_path: &Path) -> Vec<(String, std::path::PathBuf)> {
    let mut dives = Vec::new();
    if let Ok(entries) = fs::read_dir(crate_path) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.starts_with("DEEPDIVE_") && name.ends_with(".md.tmpl") {
                let subject = name
                    .trim_start_matches("DEEPDIVE_")
                    .trim_end_matches(".md.tmpl")
                    .to_string();
                dives.push((subject, entry.path()));
            }
        }
    }
    dives.sort_by(|a, b| a.0.cmp(&b.0));
    dives
}

/// Generate per-crate overview and deep dive files in docs/.
pub fn generate_per_crate_docs(cfg: &Config) {
    if !cfg.crates_dir.is_dir() {
        return;
    }

    let header = generation_header_md(cfg);

    let mut crate_dirs: Vec<_> = fs::read_dir(&cfg.crates_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .collect();
    crate_dirs.sort_by_key(|e| e.file_name());

    let mut count = 0;

    for crate_entry in crate_dirs {
        let crate_path = crate_entry.path();
        let crate_name = crate_entry.file_name().to_string_lossy().to_string();
        let crate_upper = crate_name.to_uppercase().replace('-', "_");

        let design_path = crate_path.join("DESIGN.md.tmpl");
        if let Ok(content) = fs::read_to_string(&design_path) {
            let out_name = format!("{crate_upper}_OVERVIEW.md");
            let out_path = cfg.docs_dir.join(&out_name);
            let full = format!("{header}\n{content}");
            fs::write(&out_path, &full).expect("failed to write overview");
            count += 1;
        }

        for (subject, dd_path) in find_deep_dives(&crate_path) {
            if let Ok(content) = fs::read_to_string(&dd_path) {
                let subject_upper = subject.to_uppercase();
                let out_name = format!("{crate_upper}_{subject_upper}.md");
                let out_path = cfg.docs_dir.join(&out_name);
                let full = format!("{header}\n{content}");
                fs::write(&out_path, &full).expect("failed to write deep dive");
                count += 1;
            }
        }
    }

    eprintln!("  generated {count} per-crate doc files");
}
