use std::collections::BTreeMap;
use std::fmt::Write;
use std::fs;
use std::path::{Path, PathBuf};

use crate::config::Config;
use crate::graph;
use crate::model::*;

/// Write a generated file, skipping the write when the only difference is the
/// generation timestamp.
///
/// Every generated file carries a `Generated at:` line, so a regeneration that
/// produces otherwise identical content still rewrites the file and leaves it
/// modified in the consumer's working tree. That noise is worse than untidy: a
/// timestamp-only diff is indistinguishable at a glance from a real one, so it
/// trains readers to skip generated-file diffs, and it dirties a tree that the
/// run should have left alone. Running `cargo mock` must be safe on a clean
/// tree.
///
/// Skipping leaves the previous timestamp in place, which makes the field mean
/// "when this content last changed" rather than "when a generator last ran".
/// That is the more useful of the two readings and the only one a reader can
/// act on.
///
/// Returns true when the file was written.
pub fn write_generated(path: &Path, content: &str) -> bool {
    let previous = fs::read_to_string(path).ok();
    write_generated_vs(path, content, previous.as_deref())
}

/// [`write_generated`] against a caller-supplied previous version.
///
/// Needed when something else writes the target before the header goes on:
/// graphviz renders the SVG straight to its final path, so by the time the
/// header is prepended the previous version is already gone and there is
/// nothing left on disk to compare against. The caller snapshots it first and
/// passes it here.
///
/// Returns true when the file was written.
pub fn write_generated_vs(path: &Path, content: &str, previous: Option<&str>) -> bool {
    if let Some(prev) = previous {
        if same_modulo_timestamp(prev, content) {
            // Put the previous bytes back. For a file this module owns end to
            // end that is a no-op and is skipped; for one an external tool has
            // already clobbered, it is what actually undoes the churn.
            if fs::read_to_string(path).ok().as_deref() != Some(prev) {
                fs::write(path, prev)
                    .unwrap_or_else(|e| panic!("failed to restore {}: {e}", path.display()));
            }
            return false;
        }
    }
    fs::write(path, content)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", path.display()));
    true
}

/// Best-effort [`write_generated`]: same timestamp-skip, but a write
/// failure is ignored rather than a panic.
///
/// For generated files a caller deliberately writes with `.ok()` (a
/// failure there is tolerated, not fatal). Returns true when written.
pub fn write_generated_ok(path: &Path, content: &str) -> bool {
    if let Ok(existing) = fs::read_to_string(path) {
        if same_modulo_timestamp(&existing, content) {
            return false;
        }
    }
    fs::write(path, content).is_ok()
}

/// Compare two generated files ignoring the header `Generated at:` line.
///
/// Only the FIRST timestamp line in each file is dropped, which is the
/// header the generator emits. A body line that happens to start with
/// `Generated at:` is a real content line and stays in the comparison,
/// so a change touching only such a line is not false-skipped.
fn same_modulo_timestamp(a: &str, b: &str) -> bool {
    without_header_timestamp(a).eq(without_header_timestamp(b))
}

/// The file's lines with the first `Generated at:` line removed.
fn without_header_timestamp(s: &str) -> impl Iterator<Item = &str> {
    let mut dropped = false;
    s.lines().filter(move |l| {
        if !dropped && is_timestamp_line(l) {
            dropped = true;
            return false;
        }
        true
    })
}

/// True for the `Generated at:` line in any header form this module emits
/// (markdown and SVG indent it inside a comment; DOT prefixes it with `//`).
fn is_timestamp_line(line: &str) -> bool {
    line.trim_start()
        .trim_start_matches("//")
        .trim_start()
        .starts_with("Generated at:")
}

/// Generate a markdown generation header with timestamp.
pub fn generation_header_md(cfg: &Config) -> String {
    let mock_rel = cfg.mock_dir.strip_prefix(&cfg.repo_root)
        .map(|p| p.display().to_string())
        .unwrap_or_else(|_| cfg.mock_dir.display().to_string());
    let mut hdr = String::new();
    let timestamp = now_rfc3339();

    writeln!(hdr, "<!--").unwrap();
    writeln!(hdr, "  AUTO-GENERATED: DO NOT EDIT DIRECTLY").unwrap();
    writeln!(hdr, "").unwrap();
    writeln!(hdr, "  Generated by: mockspace ({mock_rel})").unwrap();
    writeln!(hdr, "  Generated at: {timestamp}").unwrap();
    writeln!(hdr, "  Source: {mock_rel}/").unwrap();
    writeln!(hdr, "  To regenerate: cargo mock").unwrap();
    writeln!(hdr, "-->").unwrap();

    hdr
}

/// Generate a DOT comment header with timestamp.
pub fn generation_header_dot(cfg: &Config) -> String {
    let mock_rel = cfg.mock_dir.strip_prefix(&cfg.repo_root)
        .map(|p| p.display().to_string())
        .unwrap_or_else(|_| cfg.mock_dir.display().to_string());
    let mut hdr = String::new();
    let timestamp = now_rfc3339();

    writeln!(hdr, "// AUTO-GENERATED: DO NOT EDIT DIRECTLY").unwrap();
    writeln!(hdr, "//").unwrap();
    writeln!(hdr, "// Generated by: mockspace ({mock_rel})").unwrap();
    writeln!(hdr, "// Generated at: {timestamp}").unwrap();
    writeln!(hdr, "// Source: {mock_rel}/").unwrap();
    writeln!(hdr, "// To regenerate: cargo mock").unwrap();
    writeln!(hdr).unwrap();

    hdr
}

/// Generate an SVG comment to prepend before the SVG content.
pub fn generation_header_svg(cfg: &Config) -> String {
    let mock_rel = cfg.mock_dir.strip_prefix(&cfg.repo_root)
        .map(|p| p.display().to_string())
        .unwrap_or_else(|_| cfg.mock_dir.display().to_string());
    let mut hdr = String::new();
    let timestamp = now_rfc3339();

    writeln!(hdr, "<!--").unwrap();
    writeln!(hdr, "  AUTO-GENERATED: DO NOT EDIT DIRECTLY").unwrap();
    writeln!(hdr, "").unwrap();
    writeln!(hdr, "  Generated by: mockspace ({mock_rel})").unwrap();
    writeln!(hdr, "  Generated at: {timestamp}").unwrap();
    writeln!(hdr, "  Source: {mock_rel}/").unwrap();
    writeln!(hdr, "  To regenerate: cargo mock").unwrap();
    writeln!(hdr, "-->").unwrap();

    hdr
}


/// The document-name stem for a crate, with the project's own crate prefix
/// stripped.
///
/// A document already lives in one project's docs directory, so repeating the
/// project name in every filename says nothing: `NUMERIC.md` carries exactly
/// the information `IKIUNI_RENDERER_NUMERIC_OVERVIEW.md` did, and a
/// directory listing of thirty crates becomes readable.
///
/// A crate that does not carry the prefix keeps its whole name, which is the
/// only case where two crates could produce one stem. That collision is
/// reported by the caller rather than silently resolved.
fn crate_doc_stem(crate_name: &str, crate_prefix: &str) -> String {
    let stripped = if crate_prefix.is_empty() {
        crate_name
    } else {
        crate_name
            .strip_prefix(&format!("{crate_prefix}-"))
            .unwrap_or(crate_name)
    };
    stripped.to_uppercase().replace('-', "_")
}

/// The sort prefix for a document generated from a crate.
///
/// Dependency depth is the number, so the listing reads bottom-up: the
/// contract layer before the store, the store before the planner, the planner
/// before the lanes. Crates sharing a depth share a prefix and fall
/// alphabetically among themselves, which keeps a crate's own documents
/// adjacent.
///
/// Depths start at 10 rather than 0 so project-level documents can sort ahead
/// of every crate without negative numbers, and supplementary material can
/// sort behind everything without colliding with a deep tree.
fn crate_doc_prefix(depth: usize) -> String {
    // Depth only, shared by every crate at that depth.
    //
    // Siblings with no inherent order between them share a prefix rather than
    // taking a running index, because a running index renumbers every sibling
    // after the one you add. Alphabetical order sorts them among themselves,
    // which is as much order as actually exists.
    //
    // Overview-before-deep-dives is handled by naming rather than numbering:
    // a crate's overview is named for the crate alone, so `NUMERIC.md` sorts
    // ahead of `NUMERIC_STRATEGY.md` because `.` precedes `_`. Nothing has to
    // be renumbered when a deep dive appears.
    //
    // Steps of ten, not a hundred. A level is a real and fairly stable axis, so
    // it deserves visible granularity: 100, 110, 120 reads as successive layers
    // where 100, 200, 300 reads as unrelated bands. The units digit is left
    // free for an ordering within a level, should one ever turn out to exist.
    format!("{:03}", 100 + depth * 10)
}

/// Apply the standalone prefix to a document name, or leave it alone when the
/// project has not opted into ordering.
///
/// Four bands, in reading order: `00` the documents to start with, `10` upward
/// the crates by dependency depth, `90` the registry tables, and `99`
/// everything else. Registries get their own band because a lookup table is a
/// different kind of thing from a document read start to finish, and burying
/// one among the other supplementary documents loses that.
pub fn ordered_doc_name(base: &str, cfg: &Config) -> String {
    ordered_doc_name_banded(base, cfg, false)
}

/// The name for a registry table's page, ordered within the registry band by
/// the namespace's declaration order.
///
/// Alphabetical is the wrong order for these. Benches assume the constants,
/// laws, and vocabulary they measure against, so sorting them first hands a
/// reader the tables in reverse dependency order. Declaration order in the
/// project's config is the reading order, which means reordering the
/// declarations reorders the documents and no second list has to be kept in
/// step.
pub fn registry_doc_name(base: &str, cfg: &Config, index: usize) -> String {
    if !cfg.ordered_docs {
        return base.to_string();
    }
    let stem = base.split('.').next().unwrap_or(base);
    if cfg.primary_docs.iter().any(|p| p.eq_ignore_ascii_case(stem)) {
        return format!("000_{base}");
    }
    // Three digits leave the registry band room for as many namespaces as a
    // project cares to declare, without spilling into the supplementary one.
    format!("{}_{base}", 900 + index.min(98))
}

/// As [`ordered_doc_name`], naming whether this document is a registry table.
pub fn ordered_doc_name_banded(base: &str, cfg: &Config, is_registry: bool) -> String {
    if !cfg.ordered_docs {
        return base.to_string();
    }
    let stem = base.split('.').next().unwrap_or(base);
    // A project may still promote a registry into the primary band: a glossary
    // is sometimes the first thing to read.
    let band = if cfg.primary_docs.iter().any(|p| p.eq_ignore_ascii_case(stem)) {
        "000"
    } else if is_registry {
        "900"
    } else {
        "999"
    };
    format!("{band}_{base}")
}

/// The filename for a crate's generated document.
///
/// The single place this is constructed. It previously existed twice, once in
/// the writer and once in the link builder, and the two drifted the moment the
/// naming changed: every Overview link in every repo pointed at a file that no
/// longer existed.
pub fn crate_doc_file(crate_upper: &str, subject: &str, depth: usize, cfg: &Config) -> String {
    let stem = if subject == "OVERVIEW" {
        crate_upper.to_string()
    } else {
        format!("{crate_upper}_{subject}")
    };
    if cfg.ordered_docs {
        format!("{}_{stem}.md", crate_doc_prefix(depth))
    } else {
        format!("{stem}.md")
    }
}

/// Generate DESIGN.md from DESIGN.md.tmpl + parsed crate data.
pub fn generate_design_md(
    ph: &Placeholders,
    cfg: &Config,
    registry: &crate::registry::Registry,
) -> Option<String> {
    let tmpl_path = cfg.mock_dir.join("DESIGN.md.tmpl");
    let template = match fs::read_to_string(&tmpl_path) {
        Ok(t) => t,
        Err(e) => {
            eprintln!("  warning: no DESIGN.md.tmpl found: {e}");
            return None;
        }
    };

    let header = generation_header_md(cfg);
    // Placeholders first, then references. `{{crate_summaries}}` expands into
    // the per-crate summaries, which carry references of their own, so
    // resolving before the expansion would leave every one of those literal.
    let result = crate::registry::resolve_all(
        &ph.apply(&template),
        &cfg.registry_namespaces,
        registry,
        &cfg.registry_roots,
        &cfg.repo_root,
        &cfg.docs_dir,
        cfg,
    );

    Some(format!("{header}\n{result}"))
}

/// Render every `*.md.tmpl` in the mock dir except `DESIGN.md.tmpl`, which
/// has its own richer path.
///
/// These carry the generation header and the same placeholder vocabulary
/// every other template gets. Returns the paths written or left in place.
pub fn render_passthrough_templates(
    ph: &Placeholders,
    cfg: &Config,
    registry: &crate::registry::Registry,
) -> Vec<PathBuf> {
    let mut written = Vec::new();
    let Ok(entries) = fs::read_dir(&cfg.mock_dir) else {
        return written;
    };
    // This function owns its output directory rather than assuming a caller
    // made it: a repo generating for the first time has no docs/ yet.
    ensure_docs_dir(cfg);

    let mut templates: Vec<_> = entries
        .flatten()
        .filter(|e| {
            let name = e.file_name().to_string_lossy().to_string();
            name.ends_with(".md.tmpl") && name != "DESIGN.md.tmpl"
        })
        .collect();
    // Deterministic order, matching the per-crate docs path.
    templates.sort_by_key(|e| e.file_name());

    for entry in templates {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();
        let out_name = ordered_doc_name(name.trim_end_matches(".tmpl"), cfg);
        let header = generation_header_md(cfg);
        let body = fs::read_to_string(&path).expect("failed to read template");
        let body = ph.apply(&body);
        // Registry references resolve after placeholder substitution, so a
        // placeholder may expand into a reference and still be linked.
        let body = crate::registry::resolve_all(
            &body,
            &cfg.registry_namespaces,
            registry,
            &cfg.registry_roots,
            &cfg.repo_root,
            &cfg.docs_dir,
            cfg,
        );
        let content = format!("{header}\n{body}");
        let out_path = cfg.docs_dir.join(&out_name);
        write_generated(&out_path, &content);
        written.push(out_path);
    }
    written
}

/// Create the docs output directory if it is not there yet.
///
/// Every generated file lands in it, and a repo generating for the first time
/// has none.
pub fn ensure_docs_dir(cfg: &Config) {
    if let Err(e) = fs::create_dir_all(&cfg.docs_dir) {
        panic!("failed to create {}: {e}", cfg.docs_dir.display());
    }
}

/// The `{{...}}` placeholder vocabulary, computed once per run.
///
/// One vocabulary for every template: a placeholder means the same thing
/// wherever it appears, so `{{project_name}}` in `WORKFLOW.md.tmpl` or in a
/// crate's own `DESIGN.md.tmpl` expands exactly as it does in the top-level
/// `DESIGN.md.tmpl`. Templates that use no placeholder pass through unchanged.
///
/// Computed once because several members scan the mock tree (the deep-dive
/// list and the crate summaries read directories and files), and the values
/// are identical for every template in a run.
///
/// There is deliberately no escape for a literal `{{name}}`: no template needs
/// to write one today. Add an escape when one does, rather than carrying an
/// unused mechanism.
pub struct Placeholders {
    project_name: String,
    mock_dir: String,
    crate_count: String,
    macros_table: String,
    primary_items: String,
    crate_layers: String,
    deep_dives: String,
    crate_summaries: String,
}

impl Placeholders {
    /// Compute the vocabulary for one generation run.
    pub fn compute(crates: &CrateMap, cfg: &Config) -> Self {
        let mock_dir = cfg
            .mock_dir
            .strip_prefix(&cfg.repo_root)
            .unwrap_or(&cfg.mock_dir)
            .to_string_lossy()
            .to_string();

        Self {
            project_name: cfg.project_name.clone(),
            mock_dir,
            crate_count: crates.len().to_string(),
            macros_table: compute_macros_table(crates, cfg),
            primary_items: compute_primary_items_per_crate(crates, cfg),
            crate_layers: compute_crate_layers(crates, cfg),
            deep_dives: collect_deep_dives(&cfg.mock_dir),
            crate_summaries: compute_crate_summaries(&cfg.mock_dir, &cfg.crate_prefix, cfg, crates),
        }
    }

    /// Expand every placeholder in a template body.
    pub fn apply(&self, template: &str) -> String {
        let mut result = template.to_string();
        result = result.replace("{{project_name}}", &self.project_name);
        result = result.replace("{{mock_dir}}", &self.mock_dir);
        result = result.replace("{{crate_count}}", &self.crate_count);
        result = result.replace("{{macros_table}}", &self.macros_table);
        // Provide both generic and legacy variable names
        result = result.replace("{{signals_per_crate}}", &self.primary_items);
        result = result.replace("{{primary_items_per_crate}}", &self.primary_items);
        result = result.replace("{{crate_layers}}", &self.crate_layers);
        result = result.replace("{{deep_dives}}", &self.deep_dives);
        result = result.replace("{{crate_summaries}}", &self.crate_summaries);
        result
    }
}

/// Compute the macros table from config + crate scan.
fn compute_macros_table(crates: &CrateMap, cfg: &Config) -> String {
    // Scan for actually-present macros
    let mut found: BTreeMap<String, bool> = BTreeMap::new();
    for info in crates.values() {
        for item in &info.items {
            if let Item::Macro(m) = item {
                if m.name.starts_with("define_") {
                    found.insert(m.name.clone(), true);
                }
            }
        }
    }

    let mut table = String::new();
    writeln!(table, "| Need | Macro |").unwrap();
    writeln!(table, "|------|-------|").unwrap();

    // Configured macros first (preserves config order)
    for (name, desc, usage) in &cfg.known_macros {
        if found.contains_key(name.as_str()) {
            writeln!(table, "| {desc} | {usage} |").unwrap();
            found.remove(name.as_str());
        }
    }

    // Any extra macros not in config
    for name in found.keys() {
        writeln!(table, "| Custom | `{name}!(...)` |").unwrap();
    }

    table.trim_end().to_string()
}

/// Compute per-crate table for the primary domain macro.
fn compute_primary_items_per_crate(crates: &CrateMap, cfg: &Config) -> String {
    let primary = match &cfg.primary_domain_macro {
        Some(m) => m.as_str(),
        None => return format!("*No primary domain macro configured.*"),
    };
    let label = &cfg.primary_domain_label;

    let mut items_by_crate: BTreeMap<String, Vec<String>> = BTreeMap::new();

    for info in crates.values() {
        let short = &info.short_name;
        if short == &cfg.project_name { continue; }
        for mg in &info.macro_generated {
            if mg.macro_name == primary {
                items_by_crate
                    .entry(short.clone())
                    .or_default()
                    .push(mg.generated_name.clone());
            }
        }
    }

    if items_by_crate.is_empty() {
        return format!("*No {} found in any crate.*", label.to_lowercase());
    }

    let mut table = String::new();
    writeln!(table, "| Crate | {label} |").unwrap();
    writeln!(table, "|-------|{}|", "-".repeat(label.len() + 2)).unwrap();

    for (crate_name, mut items) in items_by_crate {
        items.sort();
        let formatted = items.iter().map(|s| format!("`{s}`")).collect::<Vec<_>>().join(", ");
        writeln!(table, "| {crate_name} | {formatted} |").unwrap();
    }

    table.trim_end().to_string()
}

/// Compute the crate layers section.
fn compute_crate_layers(crates: &CrateMap, cfg: &Config) -> String {
    let mut depth_cache = BTreeMap::new();
    let mut depths = BTreeMap::new();
    for name in crates.keys() {
        depths.insert(name.clone(), graph::compute_depth(name, crates, &mut depth_cache));
    }
    let max_depth = depths.values().copied().max().unwrap_or(0);

    let mut by_depth: Vec<Vec<String>> = vec![Vec::new(); max_depth + 1];
    for (name, &d) in &depths {
        let short = &crates[name.as_str()].short_name;
        if short == &cfg.project_name { continue; }
        by_depth[d].push(short.clone());
    }

    let mut layers = String::new();
    writeln!(layers, "```").unwrap();
    for (d, names) in by_depth.iter().enumerate() {
        if names.is_empty() { continue; }
        let label = cfg.layer_label(d);
        let mut sorted = names.clone();
        sorted.sort();
        let joined = sorted.join(", ");
        let pad = if d < 10 { " " } else { "" };
        writeln!(layers, "Layer {d}{pad}({label:14}): {joined}").unwrap();
    }
    writeln!(layers, "```").unwrap();

    layers.trim_end().to_string()
}

/// Collect deep-dive markdown files from per-crate DEEPDIVE_*.md.tmpl files.
fn collect_deep_dives(mock_dir: &Path) -> String {
    let crates_dir = mock_dir.join("crates");
    if !crates_dir.is_dir() {
        return String::new();
    }

    let mut all_dives = Vec::new();

    let mut crate_dirs: Vec<_> = fs::read_dir(&crates_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .collect();
    crate_dirs.sort_by_key(|e| e.file_name());

    for crate_entry in crate_dirs {
        let crate_path = crate_entry.path();
        let mut entries: Vec<_> = fs::read_dir(&crate_path)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| {
                let name = e.file_name().to_string_lossy().to_string();
                name.starts_with("DEEPDIVE_") && name.ends_with(".md.tmpl")
            })
            .collect();
        entries.sort_by_key(|e| e.file_name());

        for entry in entries {
            if let Ok(content) = fs::read_to_string(entry.path()) {
                all_dives.push(content.trim().to_string());
            }
        }
    }

    all_dives.join("\n\n")
}

/// Get current timestamp as RFC 3339.
fn now_rfc3339() -> String {
    use std::process::Command;
    let output = Command::new("date")
        .arg("-u")
        .arg("+%Y-%m-%dT%H:%M:%SZ")
        .output();
    match output {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout).trim().to_string(),
        _ => "unknown".to_string(),
    }
}

/// Generate standalone DESIGN-DEEP-DIVES.md from per-crate DEEPDIVE_*.md.tmpl files.
pub fn generate_deep_dives_md(cfg: &Config) -> String {
    let header = generation_header_md(cfg);
    let dives = collect_deep_dives(&cfg.mock_dir);
    if dives.is_empty() {
        return String::new();
    }

    let name = &cfg.project_name;
    let mut md = String::new();
    writeln!(md, "{header}").unwrap();
    writeln!(md, "# {name}: Deep Dives").unwrap();
    writeln!(md).unwrap();
    writeln!(md, "> Detailed technical deep dives into {name} subsystems.").unwrap();
    writeln!(md, "> See also: [DESIGN.md](DESIGN.md) for the high-level design.").unwrap();
    writeln!(md).unwrap();
    writeln!(md, "---").unwrap();
    writeln!(md).unwrap();
    writeln!(md, "{dives}").unwrap();

    md
}

/// Compute crate summaries from per-crate README.md.tmpl files.
fn compute_crate_summaries(mock_dir: &Path, crate_prefix: &str, cfg: &Config, crates: &CrateMap) -> String {
    let mut depth_cache = BTreeMap::new();
    let crates_dir = mock_dir.join("crates");
    if !crates_dir.is_dir() {
        return String::new();
    }

    let mut crate_dirs: Vec<_> = fs::read_dir(&crates_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .collect();
    crate_dirs.sort_by_key(|e| e.file_name());

    let mut summaries = String::new();

    for crate_entry in crate_dirs {
        let crate_path = crate_entry.path();
        let crate_name = crate_entry.file_name().to_string_lossy().to_string();
        let readme_path = crate_path.join("README.md.tmpl");

        if let Ok(content) = fs::read_to_string(&readme_path) {
            writeln!(summaries, "{}", content.trim()).unwrap();

            let has_design = crate_path.join("DESIGN.md.tmpl").exists();
            let deep_dives = find_deep_dives(&crate_path);

            if has_design || !deep_dives.is_empty() {
                writeln!(summaries).unwrap();
                let crate_upper = crate_doc_stem(&crate_name, crate_prefix);
                // Built the same way the writer builds them. These links were
                // constructed independently and silently went dead the moment
                // the naming changed, in every repo at once.
                let depth = graph::compute_depth(&crate_name, crates, &mut depth_cache);
                if has_design {
                    let f = crate_doc_file(&crate_upper, "OVERVIEW", depth, cfg);
                    writeln!(summaries, "- [Overview]({f})").unwrap();
                }
                for (subject, _) in &deep_dives {
                    let f = crate_doc_file(&crate_upper, &subject.to_uppercase(), depth, cfg);
                    writeln!(summaries, "- [{subject} deep dive]({f})").unwrap();
                }
            }

            writeln!(summaries).unwrap();
        }
    }

    summaries.trim_end().to_string()
}

/// Find DEEPDIVE_*.md.tmpl files in a crate directory.
fn find_deep_dives(crate_path: &Path) -> Vec<(String, std::path::PathBuf)> {
    let mut dives = Vec::new();
    if let Ok(entries) = fs::read_dir(crate_path) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.starts_with("DEEPDIVE_") && name.ends_with(".md.tmpl") {
                let subject = name
                    .trim_start_matches("DEEPDIVE_")
                    .trim_end_matches(".md.tmpl")
                    .to_string();
                dives.push((subject, entry.path()));
            }
        }
    }
    dives.sort_by(|a, b| a.0.cmp(&b.0));
    dives
}

/// Each crate's short name mapped to the document it generates.
///
/// The same `crate_doc_file` the writer uses, so the two cannot drift. That
/// drift already happened once, when a link builder and a writer each
/// constructed the filename their own way and the overview links went dead.
pub fn crate_doc_name_map(cfg: &Config, crates: &CrateMap) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    if !cfg.crates_dir.is_dir() {
        return out;
    }
    let mut depth_cache = BTreeMap::new();
    let Ok(entries) = fs::read_dir(&cfg.crates_dir) else {
        return out;
    };
    for entry in entries.filter_map(|e| e.ok()) {
        if !entry.path().is_dir() {
            continue;
        }
        let crate_name = entry.file_name().to_string_lossy().to_string();
        if !entry.path().join("DESIGN.md.tmpl").is_file() {
            continue;
        }
        let crate_upper = crate_doc_stem(&crate_name, &cfg.crate_prefix);
        let depth = graph::compute_depth(&crate_name, crates, &mut depth_cache);
        let short = crate_name
            .strip_prefix(&format!("{}-", cfg.crate_prefix))
            .unwrap_or(&crate_name)
            .to_string();
        out.insert(short, crate_doc_file(&crate_upper, "OVERVIEW", depth, cfg));
    }
    out
}

/// Generate per-crate overview and deep dive files in docs/.
///
/// Registry references resolve here exactly as they do for a root document. A
/// crate document is where most references naturally live, since it is where a
/// crate states which laws bind it and which constants it depends on, so
/// leaving them unresolved would have made the reference syntax useless in the
/// place it is most wanted, and silently: a literal `{{ reg::law::x }}` in a
/// rendered document reads as a templating bug rather than as a missing check.
pub fn generate_per_crate_docs(
    ph: &Placeholders,
    cfg: &Config,
    crates: &CrateMap,
    registry: &crate::registry::Registry,
) {
    if !cfg.crates_dir.is_dir() {
        return;
    }
    let mut depth_cache = BTreeMap::new();

    let header = generation_header_md(cfg);

    let mut crate_dirs: Vec<_> = fs::read_dir(&cfg.crates_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .collect();
    crate_dirs.sort_by_key(|e| e.file_name());

    let mut count = 0;

    // Collected first so each depth band can be numbered as one sequence. The
    // order within a band is crate name, then the overview, then that crate's
    // deep dives alphabetically.
    let mut planned: Vec<(usize, String, String, std::path::PathBuf)> = Vec::new();
    for crate_entry in crate_dirs {
        let crate_path = crate_entry.path();
        let crate_name = crate_entry.file_name().to_string_lossy().to_string();
        let crate_upper = crate_doc_stem(&crate_name, &cfg.crate_prefix);
        let depth = graph::compute_depth(&crate_name, crates, &mut depth_cache);

        let design_path = crate_path.join("DESIGN.md.tmpl");
        if design_path.is_file() {
            planned.push((depth, crate_upper.clone(), "OVERVIEW".to_string(), design_path));
        }
        for (subject, dd_path) in find_deep_dives(&crate_path) {
            planned.push((depth, crate_upper.clone(), subject.to_uppercase(), dd_path));
        }
    }
    planned.sort_by(|a, b| {
        // OVERVIEW first within a crate, then deep dives by subject.
        let key = |x: &(usize, String, String, std::path::PathBuf)| {
            (x.0, x.1.clone(), x.2 != "OVERVIEW", x.2.clone())
        };
        key(a).cmp(&key(b))
    });

    for (depth, crate_upper, subject, src) in planned {
        let Ok(content) = fs::read_to_string(&src) else { continue };
        let out_name = crate_doc_file(&crate_upper, &subject, depth, cfg);
        let out_path = cfg.docs_dir.join(&out_name);
        // Placeholders first, then references, so a placeholder may expand
        // into a reference and still be linked. Same order as the root path.
        let body = crate::registry::resolve_all(
            &ph.apply(&content),
            &cfg.registry_namespaces,
            registry,
            &cfg.registry_roots,
            &cfg.repo_root,
            &cfg.docs_dir,
            cfg,
        );
        let full = format!("{header}\n{body}");
        write_generated(&out_path, &full);
        count += 1;
    }

    eprintln!("  generated {count} per-crate doc files");
}

#[cfg(test)]
mod tests {
    use super::*;

    const HDR_A: &str = "<!--\n  Generated at: 2026-07-16T10:30:43Z\n  Source: mock/\n-->\nbody line one\nbody line two\n";
    const HDR_B: &str = "<!--\n  Generated at: 2026-07-17T13:34:56Z\n  Source: mock/\n-->\nbody line one\nbody line two\n";

    #[test]
    fn timestamp_only_change_is_equal() {
        assert!(same_modulo_timestamp(HDR_A, HDR_B));
    }

    #[test]
    fn body_change_is_not_equal() {
        let changed = HDR_B.replace("body line two", "body line TWO");
        assert!(!same_modulo_timestamp(HDR_A, &changed));
    }

    #[test]
    fn non_timestamp_header_change_is_not_equal() {
        let changed = HDR_B.replace("Source: mock/", "Source: elsewhere/");
        assert!(!same_modulo_timestamp(HDR_A, &changed));
    }

    #[test]
    fn a_body_line_starting_with_generated_at_is_not_false_skipped() {
        // The header timestamp is the FIRST such line; a body line that
        // happens to start with "Generated at:" is real content and must
        // stay in the comparison. Change only the body occurrence.
        let a = "<!--\n  Generated at: 2026-01-01T00:00:00Z\n-->\nprose\nGenerated at: build 7\n";
        let b = "<!--\n  Generated at: 2026-09-09T00:00:00Z\n-->\nprose\nGenerated at: build 8\n";
        assert!(
            !same_modulo_timestamp(a, b),
            "a real change on a second Generated-at line must not be skipped"
        );
    }

    #[test]
    fn dot_comment_timestamp_line_is_recognised() {
        assert!(is_timestamp_line("// Generated at: 2026-07-17T13:34:56Z"));
        assert!(is_timestamp_line("  Generated at: 2026-07-17T13:34:56Z"));
        assert!(!is_timestamp_line("  Source: mock/"));
        assert!(!is_timestamp_line("body Generated at: not a header line"));
    }

    #[test]
    fn write_generated_skips_timestamp_only_and_restores_previous() {
        let dir = std::env::temp_dir().join(format!("mockspace_wg_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("gen.md");

        assert!(write_generated(&path, HDR_A), "first write must land");
        // Simulate an external clobber (graphviz) plus a timestamp-only regen:
        // the previous is HDR_A, the target on disk is headerless junk, the new
        // content is HDR_B. Must skip AND restore HDR_A, not leave the junk.
        std::fs::write(&path, "clobbered by an external tool").unwrap();
        assert!(!write_generated_vs(&path, HDR_B, Some(HDR_A)), "timestamp-only must skip");
        assert_eq!(std::fs::read_to_string(&path).unwrap(), HDR_A, "previous must be restored");

        // A real body change writes.
        let changed = HDR_B.replace("body line two", "body line THREE");
        assert!(write_generated(&path, &changed), "body change must write");
        assert_eq!(std::fs::read_to_string(&path).unwrap(), changed);

        std::fs::remove_dir_all(&dir).ok();
    }
}
