use std::fmt::Write;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

use crate::config::Config;
use crate::model::*;
use crate::render_design;

/// Platform-specific hook helpers injected into {{HOOK_HELPERS}} for Claude.
///
/// - _extract: reads fields from tool_input (Claude's input format)
/// - deny: outputs hookSpecificOutput JSON wrapper with deny decision
/// - context: outputs hookSpecificOutput JSON wrapper with additionalContext
const CLAUDE_HOOK_HELPERS: &str = r##"# --- Platform helpers (Claude) — generated by xtask ---
_extract() {
    echo "$__INPUT" | jq -r ".tool_input.$1 // \"\"" 2>/dev/null || echo ""
}

deny() {
    printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' "$1"
    exit 0
}

context() {
    printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","additionalContext":"%s"}}\n' "$1"
}
# --- End platform helpers ---"##;

/// Platform-specific hook helpers injected into {{HOOK_HELPERS}} for Copilot.
///
/// - _extract: reads fields from toolArgs (Copilot's stringified JSON format)
/// - deny: outputs flat JSON deny decision
/// - context: outputs plain text (non-blocking)
const COPILOT_HOOK_HELPERS: &str = r##"# --- Platform helpers (Copilot) — generated by xtask ---
_extract() {
    echo "$__INPUT" | jq -r "if .toolArgs then (.toolArgs | fromjson? | .$1 // \"\") else \"\" end" 2>/dev/null || echo ""
}

deny() {
    printf '{"permissionDecision":"deny","permissionDecisionReason":"%s"}\n' "$1"
    exit 0
}

context() {
    printf '%s\n' "$1"
}
# --- End platform helpers ---"##;

/// Set the executable bit on a file.
fn set_executable(path: &Path) {
    if let Ok(meta) = fs::metadata(path) {
        let mut perms = meta.permissions();
        perms.set_mode(0o755);
        let _ = fs::set_permissions(path, perms);
    }
}

/// Generate agent rules, skills, hooks, and settings from templates in agent/ directory.
///
/// Reads templates from `mock_dir/agent/`, substitutes template variables,
/// and writes dual outputs:
/// - Claude: CLAUDE.md, .claude/rules/*.md, .claude/skills/*/SKILL.md,
///           .claude/hooks/*.sh, .claude/settings.json
/// - Copilot: .github/copilot-instructions.md, .github/instructions/*.instructions.md,
///            .github/skills/*/SKILL.md, .github/hooks/*.sh, .github/hooks/hooks.json
pub fn generate_agent_rules(crates: &CrateMap, cfg: &Config) -> usize {
    let repo_root = &cfg.repo_root;
    let agent_dir = cfg.mock_dir.join("agent");

    if !agent_dir.is_dir() {
        eprintln!("  no agent/ directory found, skipping");
        return 0;
    }

    let vars = compute_template_vars(crates, cfg);
    let header_md = render_design::generation_header_md(cfg);
    let preamble = read_optional_template(&agent_dir.join("PREAMBLE.md.tmpl"));
    let postamble = read_optional_template(&agent_dir.join("POSTAMBLE.md.tmpl"));
    let mut count = 0;

    // --- MAIN.md.tmpl → .claude/CLAUDE.md + .github/copilot-instructions.md ---
    let main_tmpl = agent_dir.join("MAIN.md.tmpl");
    if main_tmpl.is_file() {
        let body = read_and_substitute(&main_tmpl, &vars);

        // Claude: .claude/CLAUDE.md (discovered from .claude/ directory)
        let claude_dir = repo_root.join(".claude");
        let _ = fs::create_dir_all(&claude_dir);
        let claude_content = format_with_bookends(&header_md, &preamble, &body, &postamble);
        let claude_path = claude_dir.join("CLAUDE.md");
        fs::write(&claude_path, &claude_content).expect("failed to write CLAUDE.md");
        eprintln!("  {}", claude_path.display());
        count += 1;

        // Clean up legacy root CLAUDE.md if it exists
        let legacy_path = repo_root.join("CLAUDE.md");
        if legacy_path.is_file() {
            let _ = fs::remove_file(&legacy_path);
            eprintln!("  removed legacy {}", legacy_path.display());
        }

        // Copilot: .github/copilot-instructions.md
        let copilot_dir = repo_root.join(".github");
        let _ = fs::create_dir_all(&copilot_dir);
        let copilot_content = format_with_bookends(&header_md, &preamble, &body, &postamble);
        let copilot_path = copilot_dir.join("copilot-instructions.md");
        fs::write(&copilot_path, copilot_content).expect("failed to write copilot-instructions.md");
        eprintln!("  {}", copilot_path.display());
        count += 1;
    }

    // --- rules/*.md.tmpl → .claude/rules/*.md + .github/instructions/*.instructions.md ---
    let rules_dir = agent_dir.join("rules");
    if rules_dir.is_dir() {
        let claude_rules_dir = repo_root.join(".claude").join("rules");
        let copilot_instructions_dir = repo_root.join(".github").join("instructions");
        let _ = fs::create_dir_all(&claude_rules_dir);
        let _ = fs::create_dir_all(&copilot_instructions_dir);

        let mut entries: Vec<_> = fs::read_dir(&rules_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| {
                e.path()
                    .extension()
                    .map(|x| x == "tmpl")
                    .unwrap_or(false)
            })
            .collect();
        entries.sort_by_key(|e| e.file_name());

        for entry in entries {
            let path = entry.path();
            let raw = fs::read_to_string(&path).expect("failed to read rule template");
            let raw = substitute_vars(&raw, &vars);
            let (frontmatter, body) = split_frontmatter(&raw);
            let apply_to = parse_apply_to(&frontmatter);

            let stem = path
                .file_stem()
                .unwrap()
                .to_string_lossy()
                .trim_end_matches(".md")
                .to_string();

            // Claude: .claude/rules/<name>.md with paths: frontmatter
            let claude_fm = format_claude_paths(&apply_to);
            let claude_content = format!(
                "{claude_fm}\n{}",
                format_with_bookends(&header_md, &preamble, &body, &postamble)
            );
            let claude_path = claude_rules_dir.join(format!("{stem}.md"));
            fs::write(&claude_path, &claude_content).expect("failed to write claude rule");
            eprintln!("  {}", claude_path.display());
            count += 1;

            // Copilot: .github/instructions/<name>.instructions.md with applyTo: frontmatter
            let copilot_fm = format_copilot_apply_to(&apply_to);
            let copilot_content = format!(
                "{copilot_fm}\n{}",
                format_with_bookends(&header_md, &preamble, &body, &postamble)
            );
            let copilot_path = copilot_instructions_dir.join(format!("{stem}.instructions.md"));
            fs::write(&copilot_path, &copilot_content)
                .expect("failed to write copilot instruction");
            eprintln!("  {}", copilot_path.display());
            count += 1;
        }
    }

    // --- skills/*/SKILL.md.tmpl → .claude/skills/*/SKILL.md + .github/skills/*/SKILL.md ---
    let skills_dir = agent_dir.join("skills");
    if skills_dir.is_dir() {
        let claude_skills_dir = repo_root.join(".claude").join("skills");
        let copilot_skills_dir = repo_root.join(".github").join("skills");

        let mut skill_dirs: Vec<_> = fs::read_dir(&skills_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .collect();
        skill_dirs.sort_by_key(|e| e.file_name());

        for skill_entry in skill_dirs {
            let skill_path = skill_entry.path().join("SKILL.md.tmpl");
            if !skill_path.is_file() {
                continue;
            }

            let skill_name = skill_entry
                .file_name()
                .to_string_lossy()
                .to_string();

            let raw = fs::read_to_string(&skill_path).expect("failed to read skill template");
            let (frontmatter, body) = split_frontmatter(&raw);
            let body = substitute_vars(&body, &vars);
            let name = parse_field(&frontmatter, "skill_name").unwrap_or(skill_name.clone());
            let desc = parse_field(&frontmatter, "skill_description").unwrap_or_default();

            // Both Claude and Copilot use the same skill frontmatter format
            let skill_fm = format!("---\nname: {name}\ndescription: {desc}\n---");

            // Claude: .claude/skills/<name>/SKILL.md
            let claude_skill_dir = claude_skills_dir.join(&skill_name);
            let _ = fs::create_dir_all(&claude_skill_dir);
            let claude_content = format!(
                "{skill_fm}\n{}",
                format_with_bookends(&header_md, &preamble, &body, &postamble)
            );
            let claude_path = claude_skill_dir.join("SKILL.md");
            fs::write(&claude_path, &claude_content).expect("failed to write claude skill");
            eprintln!("  {}", claude_path.display());
            count += 1;

            // Copilot: .github/skills/<name>/SKILL.md
            let copilot_skill_dir = copilot_skills_dir.join(&skill_name);
            let _ = fs::create_dir_all(&copilot_skill_dir);
            let copilot_content = format!(
                "{skill_fm}\n{}",
                format_with_bookends(&header_md, &preamble, &body, &postamble)
            );
            let copilot_path = copilot_skill_dir.join("SKILL.md");
            fs::write(&copilot_path, &copilot_content).expect("failed to write copilot skill");
            eprintln!("  {}", copilot_path.display());
            count += 1;
        }
    }

    // --- hooks/*.sh.tmpl → .claude/hooks/*.sh + .github/hooks/*.sh ---
    // Hook templates use {{HOOK_HELPERS}} placeholder, which xtask replaces
    // with platform-specific functions: _extract(), deny(), context().
    let hooks_dir = agent_dir.join("hooks");
    if hooks_dir.is_dir() {
        let claude_hooks_dir = repo_root.join(".claude").join("hooks");
        let copilot_hooks_dir = repo_root.join(".github").join("hooks");
        let _ = fs::create_dir_all(&claude_hooks_dir);
        let _ = fs::create_dir_all(&copilot_hooks_dir);

        let mut entries: Vec<_> = fs::read_dir(&hooks_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| {
                let name = e.file_name().to_string_lossy().to_string();
                name.ends_with(".sh.tmpl")
            })
            .collect();
        entries.sort_by_key(|e| e.file_name());

        for entry in entries {
            let path = entry.path();
            let tmpl_name = entry.file_name().to_string_lossy().to_string();
            // Strip .tmpl suffix: "check-byline.sh.tmpl" → "check-byline.sh"
            let out_name = tmpl_name.trim_end_matches(".tmpl");

            let template = fs::read_to_string(&path).expect("failed to read hook template");

            // Claude: tool_input.field, hookSpecificOutput wrapper
            let claude_content = template.replace("{{HOOK_HELPERS}}", CLAUDE_HOOK_HELPERS);
            let claude_path = claude_hooks_dir.join(out_name);
            fs::write(&claude_path, &claude_content).expect("failed to write claude hook");
            set_executable(&claude_path);
            eprintln!("  {}", claude_path.display());
            count += 1;

            // Copilot: toolArgs (stringified JSON), flat output
            let copilot_content = template.replace("{{HOOK_HELPERS}}", COPILOT_HOOK_HELPERS);
            let copilot_path = copilot_hooks_dir.join(out_name);
            fs::write(&copilot_path, &copilot_content).expect("failed to write copilot hook");
            set_executable(&copilot_path);
            eprintln!("  {}", copilot_path.display());
            count += 1;
        }
    }

    // --- settings/ → .claude/settings.json + .github/hooks/*.json ---
    let settings_dir = agent_dir.join("settings");
    if settings_dir.is_dir() {
        let repo_root_str = repo_root.to_string_lossy();

        // Claude settings (template: substitute {{REPO_ROOT}} with actual path)
        let claude_settings_src = settings_dir.join("claude.json");
        if claude_settings_src.is_file() {
            let claude_settings_dst = repo_root.join(".claude").join("settings.json");
            let _ = fs::create_dir_all(claude_settings_dst.parent().unwrap());
            let content = fs::read_to_string(&claude_settings_src)
                .expect("failed to read claude settings template");
            let content = content.replace("{{REPO_ROOT}}", &repo_root_str);
            fs::write(&claude_settings_dst, content)
                .expect("failed to write claude settings");
            eprintln!("  {}", claude_settings_dst.display());
            count += 1;
        }

        // Copilot hooks config (template: substitute {{REPO_ROOT}} with actual path)
        let copilot_hooks_src = settings_dir.join("copilot-hooks.json");
        if copilot_hooks_src.is_file() {
            let copilot_hooks_dir = repo_root.join(".github").join("hooks");
            let _ = fs::create_dir_all(&copilot_hooks_dir);
            let copilot_hooks_dst = copilot_hooks_dir.join("hooks.json");
            let content = fs::read_to_string(&copilot_hooks_src)
                .expect("failed to read copilot hooks template");
            let content = content.replace("{{REPO_ROOT}}", &repo_root_str);
            fs::write(&copilot_hooks_dst, content)
                .expect("failed to write copilot hooks config");
            eprintln!("  {}", copilot_hooks_dst.display());
            count += 1;
        }
    }

    count
}

/// Compute template variables from parsed crate data.
fn compute_template_vars(crates: &CrateMap, cfg: &Config) -> Vec<(String, String)> {
    let mut vars = Vec::new();

    // {{project_name}}
    vars.push(("project_name".to_string(), cfg.project_name.clone()));

    // {{mock_dir}} — relative path from repo root to mock workspace
    let mock_rel = cfg.mock_dir
        .strip_prefix(&cfg.repo_root)
        .unwrap_or(&cfg.mock_dir)
        .to_string_lossy()
        .to_string();
    vars.push(("mock_dir".to_string(), mock_rel));

    // {{crate_count}}
    let crate_count = crates
        .values()
        .filter(|c| c.short_name != cfg.project_name)
        .count();
    vars.push(("crate_count".to_string(), crate_count.to_string()));

    // {{crate_table}}
    vars.push(("crate_table".to_string(), compute_crate_table(crates, cfg)));

    // {{macro_table}}
    vars.push(("macro_table".to_string(), compute_macro_table(crates)));

    vars
}

/// Build a markdown table of crates.
fn compute_crate_table(crates: &CrateMap, cfg: &Config) -> String {
    let mut table = String::new();
    writeln!(table, "| Crate | Purpose |").unwrap();
    writeln!(table, "|-------|---------|").unwrap();

    let mut sorted: Vec<_> = crates.values().collect();
    sorted.sort_by_key(|c| &c.short_name);

    let prefix = &cfg.crate_prefix;
    for info in sorted {
        if info.short_name == cfg.project_name {
            continue;
        }
        let name = &info.short_name;
        let purpose = infer_crate_purpose(info);
        writeln!(table, "| {prefix}-{name} | {purpose} |").unwrap();
    }

    table.trim_end().to_string()
}

/// Infer a one-line purpose from a crate's items.
fn infer_crate_purpose(info: &CrateInfo) -> String {
    let mut types: Vec<String> = Vec::new();
    for item in &info.items {
        match item {
            Item::Trait(t) => types.push(t.name.clone()),
            Item::Struct(s) => types.push(s.name.clone()),
            _ => {}
        }
    }
    if types.is_empty() {
        return format!("{} subsystem", info.short_name);
    }
    let max = 3.min(types.len());
    let shown: Vec<_> = types[..max].iter().map(|t| format!("`{t}`")).collect();
    let suffix = if types.len() > max {
        format!(" +{}", types.len() - max)
    } else {
        String::new()
    };
    format!("{}{suffix}", shown.join(", "))
}

/// Build the macros table for agent instructions.
fn compute_macro_table(crates: &CrateMap) -> String {
    let known: Vec<(&str, &str, &str)> = vec![
        ("define_signal", "Signal type", "`define_signal!(Name { fields } buffering: Mode)`"),
        ("define_record", "Record type (data shape)", "`define_record!(Name { field: Type = default })` or `#[derive(Record)]`"),
        ("define_resource", "Resource (singleton record)", "`define_resource!(Name { field: Type = default })`"),
        ("define_behavior", "Behavior (handler DSL)", "`define_behavior!(Name on Signal => handler { read/write/each/emit/bind/dispatch })`"),
        ("define_id", "Typed ID", "`define_id!(Name)`, `define_id!(Name, sequential)`, or `define_id!(Name, uuid)`"),
        ("define_handle", "Generational handle", "`define_handle!(Name)`"),
        ("define_binding", "GPU binding", "`define_binding!(Name { fields } buffering: Double)`"),
        ("define_marker", "Node marker", "`define_marker!(Name)`, `define_marker!(Name: Record)`, or `define_marker!(Name { fields })`"),
        ("define_scope", "Scope", "`define_scope!(Name: DataType = default_value)`"),
        ("define_action", "Action", "`define_action!(Name { fields } category: Cat, description: \"..\")`"),
        ("define_blueprint", "Blueprint", "`define_blueprint!(Name { markers: [..], children: [..] })`"),
        ("define_module", "Module", "`define_module!(Name { behaviors: [..], resources: [..] })`"),
        ("define_error", "Error", "`define_error!(Name(code) { message: \"..\", hint: \"..\" })`"),
    ];

    // Check which macros actually exist
    let mut found = std::collections::BTreeSet::new();
    for info in crates.values() {
        for item in &info.items {
            if let Item::Macro(m) = item {
                if m.name.starts_with("define_") {
                    found.insert(m.name.clone());
                }
            }
        }
    }

    let mut table = String::new();
    writeln!(table, "| Macro | Purpose | Usage |").unwrap();
    writeln!(table, "|-------|---------|-------|").unwrap();

    for (name, purpose, usage) in &known {
        if found.contains(*name) {
            writeln!(table, "| `{name}!` | {purpose} | {usage} |").unwrap();
        }
    }

    table.trim_end().to_string()
}

/// Read a template file and substitute variables.
fn read_and_substitute(path: &Path, vars: &[(String, String)]) -> String {
    let raw = fs::read_to_string(path).expect("failed to read template");
    let (_frontmatter, body) = split_frontmatter(&raw);
    substitute_vars(&body, vars)
}

/// Replace {{var}} placeholders in text.
fn substitute_vars(text: &str, vars: &[(String, String)]) -> String {
    let mut result = text.to_string();
    for (key, value) in vars {
        result = result.replace(&format!("{{{{{key}}}}}"), value);
    }
    result
}

/// Split YAML frontmatter from body content.
fn split_frontmatter(text: &str) -> (String, String) {
    let trimmed = text.trim_start();
    if !trimmed.starts_with("---") {
        return (String::new(), text.to_string());
    }

    let after_first = &trimmed[3..];
    if let Some(end) = after_first.find("\n---") {
        let fm = after_first[..end].to_string();
        let body = after_first[end + 4..].to_string();
        (fm, body)
    } else {
        (String::new(), text.to_string())
    }
}

/// Parse apply_to field from frontmatter YAML.
fn parse_apply_to(frontmatter: &str) -> Vec<String> {
    let mut patterns = Vec::new();
    let mut in_list = false;

    for line in frontmatter.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("apply_to:") {
            let value = trimmed.trim_start_matches("apply_to:").trim();
            if value.starts_with('[') {
                // Inline array: ["pattern1", "pattern2"]
                let inner = value.trim_start_matches('[').trim_end_matches(']');
                for item in inner.split(',') {
                    let p = item.trim().trim_matches('"').trim_matches('\'');
                    if !p.is_empty() {
                        patterns.push(p.to_string());
                    }
                }
            } else if value.is_empty() {
                in_list = true;
            } else {
                patterns.push(value.trim_matches('"').trim_matches('\'').to_string());
            }
        } else if in_list && trimmed.starts_with("- ") {
            let p = trimmed[2..].trim().trim_matches('"').trim_matches('\'');
            if !p.is_empty() {
                patterns.push(p.to_string());
            }
        } else if in_list && !trimmed.is_empty() && !trimmed.starts_with('#') {
            in_list = false;
        }
    }

    patterns
}

/// Parse a simple key: value field from frontmatter.
fn parse_field(frontmatter: &str, key: &str) -> Option<String> {
    let prefix = format!("{key}:");
    for line in frontmatter.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with(&prefix) {
            let value = trimmed[prefix.len()..].trim();
            return Some(value.trim_matches('"').trim_matches('\'').to_string());
        }
    }
    None
}

/// Format glob patterns as Claude's paths: YAML list.
fn format_claude_paths(patterns: &[String]) -> String {
    if patterns.is_empty() {
        return String::new();
    }
    let mut fm = String::from("---\npaths:\n");
    for p in patterns {
        writeln!(fm, "  - \"{p}\"").unwrap();
    }
    fm.push_str("---");
    fm
}

/// Format glob patterns as Copilot's applyTo: string.
fn format_copilot_apply_to(patterns: &[String]) -> String {
    if patterns.is_empty() {
        return String::new();
    }
    let joined = patterns.join(",");
    format!("---\napplyTo: \"{joined}\"\n---")
}

/// Read an optional template file, returning empty string if missing.
fn read_optional_template(path: &Path) -> String {
    if path.is_file() {
        let raw = fs::read_to_string(path).unwrap_or_default();
        let (_fm, body) = split_frontmatter(&raw);
        body.trim().to_string()
    } else {
        String::new()
    }
}

/// Assemble content with preamble before body and postamble after.
fn format_with_bookends(header: &str, preamble: &str, body: &str, postamble: &str) -> String {
    let mut out = String::new();
    out.push_str(header);
    out.push('\n');
    if !preamble.is_empty() {
        out.push('\n');
        out.push_str(preamble);
        out.push('\n');
    }
    out.push('\n');
    out.push_str(body);
    if !postamble.is_empty() {
        out.push('\n');
        out.push_str(postamble);
        out.push('\n');
    }
    out
}
