use std::collections::BTreeMap;
use std::fmt::Write;
use std::fs;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

use crate::config::Config;
use crate::model::*;
use crate::render_design;

/// Platform-specific hook helpers injected into {{HOOK_HELPERS}} for Claude.
///
/// - _extract: reads fields from tool_input (Claude's input format)
/// - deny: outputs hookSpecificOutput JSON wrapper with deny decision
/// - context: outputs hookSpecificOutput JSON wrapper with additionalContext
const CLAUDE_HOOK_HELPERS: &str = r##"# --- Platform helpers (Claude) — generated by xtask ---
_extract() {
    echo "$__INPUT" | jq -r ".tool_input.$1 // \"\"" 2>/dev/null || echo ""
}

deny() {
    printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' "$1"
    exit 0
}

context() {
    printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","additionalContext":"%s"}}\n' "$1"
}
# --- End platform helpers ---"##;

/// Platform-specific hook helpers injected into {{HOOK_HELPERS}} for Copilot.
///
/// - _extract: reads fields from toolArgs (Copilot's stringified JSON format)
/// - deny: outputs flat JSON deny decision
/// - context: outputs plain text (non-blocking)
const COPILOT_HOOK_HELPERS: &str = r##"# --- Platform helpers (Copilot) — generated by xtask ---
_extract() {
    echo "$__INPUT" | jq -r "if .toolArgs then (.toolArgs | fromjson? | .$1 // \"\") else \"\" end" 2>/dev/null || echo ""
}

deny() {
    printf '{"permissionDecision":"deny","permissionDecisionReason":"%s"}\n' "$1"
    exit 0
}

context() {
    printf '%s\n' "$1"
}
# --- End platform helpers ---"##;

/// Set the executable bit on a file.
#[cfg(unix)]
fn set_executable(path: &Path) {
    if let Ok(meta) = fs::metadata(path) {
        let mut perms = meta.permissions();
        perms.set_mode(0o755);
        let _ = fs::set_permissions(path, perms);
    }
}

// ---------------------------------------------------------------------------
// Hook metadata for settings generation (Phase 7)
// ---------------------------------------------------------------------------

/// Metadata collected from each hook for settings generation.
struct HookMeta {
    /// Output file name (e.g. "check-byline.sh").
    name: String,
    /// Tool matchers this hook should fire on (e.g. ["Bash", "Write", "Edit"]).
    matchers: Vec<String>,
}

/// Derive tool matchers from a hook file name using naming conventions.
fn matchers_from_name(name: &str) -> Vec<String> {
    if name.ends_with("-guard.sh") {
        vec!["Bash".into(), "Write".into(), "Edit".into()]
    } else if name.ends_with("-reminder.sh") {
        vec!["Bash".into()]
    } else if name.starts_with("check-") {
        vec!["Bash".into()]
    } else {
        vec!["Bash".into()]
    }
}

/// Parse `# @matchers:` frontmatter from the first 5 lines of a hook template.
fn parse_hook_matchers(template: &str) -> Option<Vec<String>> {
    for line in template.lines().take(5) {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("# @matchers:") {
            let matchers: Vec<String> = rest
                .split(',')
                .map(|s| s.trim().to_string())
                .filter(|s| !s.is_empty())
                .collect();
            if !matchers.is_empty() {
                return Some(matchers);
            }
        }
    }
    None
}

// ---------------------------------------------------------------------------
// Phase 6: Builtin agent hooks
// ---------------------------------------------------------------------------

/// Derive the agent mode env var name from a project name.
///
/// e.g. "saalis" -> "SAALIS_AGENT_MODE", "polka-dots" -> "POLKA_DOTS_AGENT_MODE"
fn agent_mode_var(project_name: &str) -> String {
    let upper = project_name.to_uppercase().replace('-', "_");
    format!("{upper}_AGENT_MODE")
}

/// Generate the check-byline.sh hook content (without HOOK_HELPERS substitution).
fn builtin_check_byline(cfg: &Config) -> String {
    let mode_var = agent_mode_var(&cfg.project_name);
    format!(
        r##"#!/usr/bin/env bash
# Built-in mockspace hook: enforce commit authorship policy
set -uo pipefail
__INPUT=$(cat)
{{{{HOOK_HELPERS}}}}
COMMAND=$(_extract "command")
# Only check git commit commands
if ! echo "$COMMAND" | grep -q "git commit"; then exit 0; fi
# Check for Co-Authored-By
HAS_BYLINE=false
if echo "$COMMAND" | grep -qi "co-authored-by"; then HAS_BYLINE=true; fi
# Check agent mode env var
AGENT_MODE="${{{mode_var}:-assistant}}"
if [[ "$AGENT_MODE" == "autonomous" ]]; then
    if [[ "$HAS_BYLINE" == "false" ]]; then
        deny "Autonomous mode requires Co-Authored-By byline"
    fi
else
    if [[ "$HAS_BYLINE" == "true" ]]; then
        deny "Blocked: Co-Authored-By byline detected in assistant mode. The human is the author. Remove the byline. Set {mode_var}=autonomous if this is genuinely autonomous work."
    fi
fi
exit 0
"##
    )
}

/// Generate the mockspace-write-guard.sh hook content.
fn builtin_write_guard(cfg: &Config) -> String {
    let mock_rel = cfg
        .mock_dir
        .strip_prefix(&cfg.repo_root)
        .unwrap_or(&cfg.mock_dir)
        .to_string_lossy()
        .to_string();
    format!(
        r##"#!/usr/bin/env bash
# Built-in mockspace hook: phase gate enforcement
# Mirrors the lint rules: changelist_doc_gate, changelist_required,
# changelist_lock, changelist_immutability.
set -uo pipefail
__INPUT=$(cat)
MOCK_ROOT="{mock_rel}"
{{{{HOOK_HELPERS}}}}
FILE_PATH=$(_extract file_path)
COMMAND=$(_extract command)
# --- Determine target path ---
TARGET=""
if [[ -n "$FILE_PATH" ]]; then
    TARGET="$FILE_PATH"
elif [[ -n "$COMMAND" ]]; then
    WRITE_MARKERS='(>>?|tee|mv|cp|rm|sed -i|perl -i|dd|install)'
    if ! echo "$COMMAND" | grep -qE "$WRITE_MARKERS"; then
        exit 0
    fi
    if echo "$COMMAND" | grep -q "$MOCK_ROOT"; then
        TARGET=$(echo "$COMMAND" | grep -oE "[^ ]*${{MOCK_ROOT}}[^ ]*" | head -1) || true
    fi
fi
# Not targeting mockspace? Allow.
if [[ -z "$TARGET" ]] || ! echo "$TARGET" | grep -q "$MOCK_ROOT"; then
    exit 0
fi
REL_PATH=$(echo "$TARGET" | sed "s|.*${{MOCK_ROOT}}/||")
# --- Always allowed: agent templates ---
if echo "$REL_PATH" | grep -qE '^agent/'; then
    exit 0
fi
# --- Always allowed: root-level mockspace templates ---
if echo "$REL_PATH" | grep -qE '^[^/]+\.md\.tmpl$'; then
    exit 0
fi
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo "")
if [[ -z "$REPO_ROOT" ]]; then
    exit 0
fi
# --- Detect phase ---
DOC_CL_ACTIVE=$(git ls-files "${{MOCK_ROOT}}/design_rounds/" 2>/dev/null \
    | grep -E "^${{MOCK_ROOT}}/design_rounds/[^/]+_changelist\.doc\.md$" \
    | head -1) || true
DOC_CL_LOCKED=$(git ls-files "${{MOCK_ROOT}}/design_rounds/" 2>/dev/null \
    | grep -E "^${{MOCK_ROOT}}/design_rounds/[^/]+_changelist\.doc\.lock\.md$" \
    | head -1) || true
SRC_CL_ACTIVE=$(git ls-files "${{MOCK_ROOT}}/design_rounds/" 2>/dev/null \
    | grep -E "^${{MOCK_ROOT}}/design_rounds/[^/]+_changelist\.src\.md$" \
    | head -1) || true
SRC_CL_LOCKED=$(git ls-files "${{MOCK_ROOT}}/design_rounds/" 2>/dev/null \
    | grep -E "^${{MOCK_ROOT}}/design_rounds/[^/]+_changelist\.src\.lock\.md$" \
    | head -1) || true
if [[ -n "$SRC_CL_LOCKED" ]]; then
    PHASE="DONE"
elif [[ -n "$SRC_CL_ACTIVE" ]]; then
    PHASE="SRC"
elif [[ -n "$DOC_CL_LOCKED" ]]; then
    PHASE="SRC-PLAN"
elif [[ -n "$DOC_CL_ACTIVE" ]]; then
    PHASE="DOC"
else
    PHASE="TOPIC"
fi
DIRTY_DOCS=$(git diff --name-only 2>/dev/null \
    | grep -E "^${{MOCK_ROOT}}/crates/.*\.(md\.tmpl|md)$" | head -1) || true
# --- Design round files ---
if echo "$REL_PATH" | grep -qE '^design_rounds/'; then
    FULL_GIT_PATH="${{MOCK_ROOT}}/${{REL_PATH}}"
    BASENAME=$(basename "$REL_PATH")
    if [[ "$BASENAME" == "README.md" ]]; then
        exit 0
    fi
    if echo "$REL_PATH" | grep -qE '^design_rounds/[^/]+/'; then
        deny "BLOCKED: '${{REL_PATH}}' is inside a closed round subdirectory.\\n\\nClosed rounds are archived history. Every file in them is frozen forever.\\nNothing in a closed round subdirectory can be edited.\\n\\nCurrent phase: ${{PHASE}}"
    fi
    IS_CHANGELIST=false
    IS_DOC_CHANGELIST=false
    IS_SRC_CHANGELIST=false
    IS_LOCKED=false
    IS_DEPRECATED=false
    if echo "$BASENAME" | grep -qE '_changelist\.(doc|src)\.(lock|deprecated)\.md$'; then
        IS_CHANGELIST=true
        echo "$BASENAME" | grep -q '\.doc\.' && IS_DOC_CHANGELIST=true
        echo "$BASENAME" | grep -q '\.src\.' && IS_SRC_CHANGELIST=true
        echo "$BASENAME" | grep -q '\.lock\.' && IS_LOCKED=true
        echo "$BASENAME" | grep -q '\.deprecated\.' && IS_DEPRECATED=true
    elif echo "$BASENAME" | grep -qE '_changelist\.(doc|src)\.md$'; then
        IS_CHANGELIST=true
        echo "$BASENAME" | grep -q '\.doc\.' && IS_DOC_CHANGELIST=true
        echo "$BASENAME" | grep -q '\.src\.' && IS_SRC_CHANGELIST=true
    fi
    if git ls-files --error-unmatch "$FULL_GIT_PATH" >/dev/null 2>&1; then
        if $IS_CHANGELIST && $IS_LOCKED; then
            deny "BLOCKED: locked changelist '${{BASENAME}}' is FROZEN.\\n\\nCurrent phase: ${{PHASE}}\\nLint: changelist-immutability (HARD_ERROR)"
        fi
        if $IS_CHANGELIST && $IS_DEPRECATED; then
            deny "BLOCKED: deprecated changelist '${{BASENAME}}' is FROZEN.\\n\\nCurrent phase: ${{PHASE}}\\nLint: changelist-immutability (HARD_ERROR)"
        fi
        if $IS_DOC_CHANGELIST && ! $IS_LOCKED && ! $IS_DEPRECATED; then
            if [[ "$PHASE" == "DOC" ]]; then exit 0; fi
            deny "BLOCKED: cannot edit doc changelist '${{BASENAME}}' -- not in DOC phase.\\n\\nPhase: ${{PHASE}}.\\nLint: changelist-immutability (HARD_ERROR)"
        fi
        if $IS_SRC_CHANGELIST && ! $IS_LOCKED && ! $IS_DEPRECATED; then
            if [[ "$PHASE" == "SRC" ]]; then exit 0; fi
            deny "BLOCKED: cannot edit source changelist '${{BASENAME}}' -- not in SRC phase.\\n\\nPhase: ${{PHASE}}.\\nLint: changelist-immutability (HARD_ERROR)"
        fi
        if ! $IS_CHANGELIST; then
            deny "BLOCKED: topic '${{BASENAME}}' is committed and FROZEN.\\n\\nCurrent phase: ${{PHASE}}"
        fi
    fi
    if ! $IS_CHANGELIST; then
        if [[ "$PHASE" != "TOPIC" ]]; then
            deny "BLOCKED: cannot create topic '${{BASENAME}}' -- not in TOPIC phase.\\n\\nPhase: ${{PHASE}}."
        fi
        exit 0
    fi
    if $IS_DOC_CHANGELIST && ! $IS_LOCKED && ! $IS_DEPRECATED; then
        if [[ "$PHASE" != "TOPIC" ]]; then
            deny "BLOCKED: cannot create doc changelist '${{BASENAME}}' -- one already exists or phase is wrong.\\n\\nPhase: ${{PHASE}}."
        fi
        exit 0
    fi
    if $IS_SRC_CHANGELIST && ! $IS_LOCKED && ! $IS_DEPRECATED; then
        if [[ "$PHASE" != "SRC-PLAN" ]]; then
            deny "BLOCKED: cannot create source changelist '${{BASENAME}}' -- not in SRC-PLAN phase.\\n\\nPhase: ${{PHASE}}."
        fi
        exit 0
    fi
    if $IS_LOCKED || $IS_DEPRECATED; then exit 0; fi
    exit 0
fi
# --- Crate files are phase-gated ---
if echo "$REL_PATH" | grep -qE '^crates/'; then
    if echo "$REL_PATH" | grep -qE 'SHAME\.md\.tmpl$'; then exit 0; fi
    if echo "$REL_PATH" | grep -qE '\.(md\.tmpl|md)$'; then
        if [[ "$PHASE" != "DOC" ]]; then
            deny "BLOCKED: cannot edit '${{REL_PATH}}' -- not in DOC phase.\\n\\nPhase: ${{PHASE}}.\\nLint: changelist-doc-gate (HARD_ERROR)"
        fi
        exit 0
    fi
    if echo "$REL_PATH" | grep -qE '\.rs$'; then
        if [[ "$PHASE" != "SRC" ]]; then
            deny "BLOCKED: cannot edit '${{REL_PATH}}' -- not in SRC phase.\\n\\nPhase: ${{PHASE}}.\\nLint: changelist-required (HARD_ERROR)"
        fi
        exit 0
    fi
    if [[ "$PHASE" == "TOPIC" ]] || [[ "$PHASE" == "DONE" ]]; then
        deny "BLOCKED: cannot edit '${{REL_PATH}}' -- no changelist exists or round is complete.\\n\\nPhase: ${{PHASE}}."
    fi
    exit 0
fi
# --- Root Cargo.toml ---
if echo "$REL_PATH" | grep -qE '^Cargo\.toml$'; then
    if [[ "$PHASE" == "TOPIC" ]] || [[ "$PHASE" == "DONE" ]]; then
        deny "BLOCKED: cannot edit '${{REL_PATH}}' -- no changelist exists or round is complete.\\n\\nPhase: ${{PHASE}}."
    fi
    exit 0
fi
exit 0
"##
    )
}

/// Generate the mockspace-reminder.sh hook content.
fn builtin_reminder(cfg: &Config) -> String {
    let mock_rel = cfg
        .mock_dir
        .strip_prefix(&cfg.repo_root)
        .unwrap_or(&cfg.mock_dir)
        .to_string_lossy()
        .to_string();
    format!(
        r##"#!/usr/bin/env bash
# Built-in mockspace hook: print mockspace rules reminder before tool use
# Non-blocking. Only fires when the tool targets mockspace paths.
set -uo pipefail
__INPUT=$(cat)
{{{{HOOK_HELPERS}}}}
FILE_PATH=$(_extract file_path)
COMMAND=$(_extract command)
IS_MOCKSPACE=false
if [[ -n "$FILE_PATH" ]] && echo "$FILE_PATH" | grep -q "{mock_rel}"; then
    IS_MOCKSPACE=true
fi
if [[ -n "$COMMAND" ]] && echo "$COMMAND" | grep -q "{mock_rel}"; then
    IS_MOCKSPACE=true
fi
if [[ "$IS_MOCKSPACE" != "true" ]]; then
    exit 0
fi
context "MOCKSPACE REMINDER: You are operating on mockspace files. Follow the design round workflow: TOPIC -> DOC -> SRC-PLAN -> SRC -> DONE. Check phase before editing. Use 'cargo mock' commands for phase transitions."
exit 0
"##
    )
}

/// Generate the no-yagni-guard.sh hook content.
fn builtin_no_yagni() -> String {
    r##"#!/usr/bin/env bash
# Built-in mockspace hook: flag YAGNI reasoning in commit messages
set -uo pipefail
__INPUT=$(cat)
{{HOOK_HELPERS}}
COMMAND=$(_extract "command")
# Only check git commit commands
if ! echo "$COMMAND" | grep -q "git commit"; then exit 0; fi
# Check for YAGNI-like keywords in the commit message
YAGNI_PATTERNS="yagni|premature|over-engineer|overkill|good enough for now|not needed yet|too early|unnecessary complexity|keep it simple"
if echo "$COMMAND" | grep -qiE "$YAGNI_PATTERNS"; then
    context "WARNING: YAGNI-flavored reasoning detected in commit message. This project embraces the ideal when designing -- extensible, trait-based, registered. Shortcuts justified by 'you ain't gonna need it' are not welcome. Reconsider the commit message."
fi
exit 0
"##
    .to_string()
}

/// Write a single builtin hook to both Claude and Copilot directories.
///
/// Returns the hook metadata and increments count by 2 (one per platform).
fn write_builtin_hook(
    name: &str,
    content: &str,
    claude_hooks_dir: &Path,
    copilot_hooks_dir: &Path,
    count: &mut usize,
) -> HookMeta {
    // The content uses {{HOOK_HELPERS}} (literal double braces) for substitution
    let claude_content = content.replace("{{HOOK_HELPERS}}", CLAUDE_HOOK_HELPERS);
    let claude_path = claude_hooks_dir.join(name);
    fs::write(&claude_path, &claude_content).expect("failed to write builtin claude hook");
    #[cfg(unix)]
    set_executable(&claude_path);
    eprintln!("  {} (builtin)", claude_path.display());
    *count += 1;

    let copilot_content = content.replace("{{HOOK_HELPERS}}", COPILOT_HOOK_HELPERS);
    let copilot_path = copilot_hooks_dir.join(name);
    fs::write(&copilot_path, &copilot_content).expect("failed to write builtin copilot hook");
    #[cfg(unix)]
    set_executable(&copilot_path);
    eprintln!("  {} (builtin)", copilot_path.display());
    *count += 1;

    HookMeta {
        name: name.to_string(),
        matchers: matchers_from_name(name),
    }
}

/// Generate all builtin agent hooks.
///
/// Writes 4 hooks to both `.claude/hooks/` and `.github/hooks/`:
/// - check-byline.sh
/// - mockspace-write-guard.sh
/// - mockspace-reminder.sh
/// - no-yagni-guard.sh
fn generate_builtin_hooks(
    cfg: &Config,
    claude_hooks_dir: &Path,
    copilot_hooks_dir: &Path,
    count: &mut usize,
) -> Vec<HookMeta> {
    let mut hooks = Vec::new();

    hooks.push(write_builtin_hook(
        "check-byline.sh",
        &builtin_check_byline(cfg),
        claude_hooks_dir,
        copilot_hooks_dir,
        count,
    ));

    hooks.push(write_builtin_hook(
        "mockspace-write-guard.sh",
        &builtin_write_guard(cfg),
        claude_hooks_dir,
        copilot_hooks_dir,
        count,
    ));

    hooks.push(write_builtin_hook(
        "mockspace-reminder.sh",
        &builtin_reminder(cfg),
        claude_hooks_dir,
        copilot_hooks_dir,
        count,
    ));

    hooks.push(write_builtin_hook(
        "no-yagni-guard.sh",
        &builtin_no_yagni(),
        claude_hooks_dir,
        copilot_hooks_dir,
        count,
    ));

    hooks
}

// ---------------------------------------------------------------------------
// Phase 7: Auto-generated settings
// ---------------------------------------------------------------------------

/// Generate `settings.json` (Claude) and `hooks.json` (Copilot) from hook metadata.
fn generate_settings(
    repo_root: &Path,
    cfg: &Config,
    all_hooks: &[HookMeta],
) -> usize {
    let mut count = 0;

    // Group hooks by matcher
    let mut matcher_to_hooks: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for hook in all_hooks {
        for matcher in &hook.matchers {
            matcher_to_hooks
                .entry(matcher.clone())
                .or_default()
                .push(hook.name.clone());
        }
    }

    // --- Claude settings.json ---
    let claude_dir = repo_root.join(".claude");
    let _ = fs::create_dir_all(&claude_dir);

    let mut claude_hooks_entries = Vec::new();
    for (matcher, hook_names) in &matcher_to_hooks {
        for hook_name in hook_names {
            claude_hooks_entries.push(format!(
                r#"      {{
        "matcher": "PreToolUse",
        "hooks": [
          {{
            "type": "command",
            "command": ".claude/hooks/{hook_name}",
            "event": "PreToolUse",
            "toolName": "{matcher}"
          }}
        ]
      }}"#
            ));
        }
    }

    // Start with auto-generated hooks
    let hooks_json_inner = claude_hooks_entries.join(",\n");

    // Check for consumer settings override (non-hook fields only)
    let agent_settings_path = cfg.mock_dir.join("agent").join("settings").join("claude.json");
    let attribution = if agent_settings_path.is_file() {
        // Read the consumer template, look for non-hooks fields to merge
        let consumer = fs::read_to_string(&agent_settings_path).unwrap_or_default();
        // Very simple: extract "attribution" field if present
        extract_json_string_field(&consumer, "attribution")
    } else {
        None
    };

    let attribution_line = if let Some(attr) = attribution {
        format!(",\n    \"attribution\": \"{attr}\"")
    } else {
        String::new()
    };

    let claude_settings = format!(
        r#"{{
    "hooks": {{
      "PreToolUse": [
{hooks_json_inner}
      ]
    }}{attribution_line}
}}"#
    );

    let claude_settings_path = claude_dir.join("settings.json");
    fs::write(&claude_settings_path, &claude_settings)
        .expect("failed to write claude settings.json");
    eprintln!("  {} (auto-generated)", claude_settings_path.display());
    count += 1;

    // --- Copilot hooks.json ---
    let copilot_hooks_dir = repo_root.join(".github").join("hooks");
    let _ = fs::create_dir_all(&copilot_hooks_dir);

    let mut copilot_entries = Vec::new();
    for (matcher, hook_names) in &matcher_to_hooks {
        for hook_name in hook_names {
            copilot_entries.push(format!(
                r#"    {{
      "name": "{hook_name}",
      "command": ".github/hooks/{hook_name}",
      "event": "pre_tool_use",
      "tool": "{matcher}"
    }}"#
            ));
        }
    }

    let copilot_hooks_inner = copilot_entries.join(",\n");
    let copilot_hooks_json = format!(
        r#"{{
  "hooks": [
{copilot_hooks_inner}
  ]
}}"#
    );

    let copilot_hooks_path = copilot_hooks_dir.join("hooks.json");
    fs::write(&copilot_hooks_path, &copilot_hooks_json)
        .expect("failed to write copilot hooks.json");
    eprintln!("  {} (auto-generated)", copilot_hooks_path.display());
    count += 1;

    count
}

/// Very simple JSON string field extractor (no serde dependency).
fn extract_json_string_field(json: &str, field: &str) -> Option<String> {
    let pattern = format!("\"{field}\"");
    let pos = json.find(&pattern)?;
    let after = &json[pos + pattern.len()..];
    // Skip whitespace and colon
    let after = after.trim_start();
    let after = after.strip_prefix(':')?;
    let after = after.trim_start();
    let after = after.strip_prefix('"')?;
    let end = after.find('"')?;
    Some(after[..end].to_string())
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

/// Generate agent rules, skills, hooks, and settings from templates in agent/ directory.
///
/// Reads templates from `mock_dir/agent/`, substitutes template variables,
/// and writes dual outputs:
/// - Claude: CLAUDE.md, .claude/rules/*.md, .claude/skills/*/SKILL.md,
///           .claude/hooks/*.sh, .claude/settings.json
/// - Copilot: .github/copilot-instructions.md, .github/instructions/*.instructions.md,
///            .github/skills/*/SKILL.md, .github/hooks/*.sh, .github/hooks/hooks.json
pub fn generate_agent_rules(crates: &CrateMap, cfg: &Config) -> usize {
    let repo_root = &cfg.repo_root;
    let agent_dir = cfg.mock_dir.join("agent");

    if !agent_dir.is_dir() {
        eprintln!("  no agent/ directory found, skipping");
        return 0;
    }

    let mut vars = compute_template_vars(crates, cfg);
    let header_md = render_design::generation_header_md(cfg);
    let preamble = read_optional_template(&agent_dir.join("PREAMBLE.md.tmpl"));
    let postamble = read_optional_template(&agent_dir.join("POSTAMBLE.md.tmpl"));
    vars.push(("PREAMBLE".to_string(), preamble.clone()));
    vars.push(("POSTAMBLE".to_string(), postamble.clone()));
    let mut count = 0;

    // --- MAIN.md.tmpl -> .claude/CLAUDE.md + .github/copilot-instructions.md ---
    let main_tmpl = agent_dir.join("MAIN.md.tmpl");
    if main_tmpl.is_file() {
        let body = read_and_substitute(&main_tmpl, &vars);

        // Claude: .claude/CLAUDE.md (discovered from .claude/ directory)
        let claude_dir = repo_root.join(".claude");
        let _ = fs::create_dir_all(&claude_dir);
        let claude_content = format_with_bookends(&header_md, &preamble, &body, &postamble);
        let claude_path = claude_dir.join("CLAUDE.md");
        fs::write(&claude_path, &claude_content).expect("failed to write CLAUDE.md");
        eprintln!("  {}", claude_path.display());
        count += 1;

        // Clean up legacy root CLAUDE.md if it exists
        let legacy_path = repo_root.join("CLAUDE.md");
        if legacy_path.is_file() {
            let _ = fs::remove_file(&legacy_path);
            eprintln!("  removed legacy {}", legacy_path.display());
        }

        // Copilot: .github/copilot-instructions.md
        let copilot_dir = repo_root.join(".github");
        let _ = fs::create_dir_all(&copilot_dir);
        let copilot_content = format_with_bookends(&header_md, &preamble, &body, &postamble);
        let copilot_path = copilot_dir.join("copilot-instructions.md");
        fs::write(&copilot_path, copilot_content).expect("failed to write copilot-instructions.md");
        eprintln!("  {}", copilot_path.display());
        count += 1;
    }

    // --- rules/*.md.tmpl -> .claude/rules/*.md + .github/instructions/*.instructions.md ---
    let rules_dir = agent_dir.join("rules");
    if rules_dir.is_dir() {
        let claude_rules_dir = repo_root.join(".claude").join("rules");
        let copilot_instructions_dir = repo_root.join(".github").join("instructions");
        let _ = fs::create_dir_all(&claude_rules_dir);
        let _ = fs::create_dir_all(&copilot_instructions_dir);

        let mut entries: Vec<_> = fs::read_dir(&rules_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| {
                e.path()
                    .extension()
                    .map(|x| x == "tmpl")
                    .unwrap_or(false)
            })
            .collect();
        entries.sort_by_key(|e| e.file_name());

        for entry in entries {
            let path = entry.path();
            let raw = fs::read_to_string(&path).expect("failed to read rule template");
            let raw = substitute_vars(&raw, &vars);
            let (frontmatter, body) = split_frontmatter(&raw);
            let apply_to = parse_apply_to(&frontmatter);

            let stem = path
                .file_stem()
                .unwrap()
                .to_string_lossy()
                .trim_end_matches(".md")
                .to_string();

            // Claude: .claude/rules/<name>.md with paths: frontmatter
            let claude_fm = format_claude_paths(&apply_to);
            let claude_content = format!(
                "{claude_fm}\n{}",
                format_with_bookends(&header_md, &preamble, &body, &postamble)
            );
            let claude_path = claude_rules_dir.join(format!("{stem}.md"));
            fs::write(&claude_path, &claude_content).expect("failed to write claude rule");
            eprintln!("  {}", claude_path.display());
            count += 1;

            // Copilot: .github/instructions/<name>.instructions.md with applyTo: frontmatter
            let copilot_fm = format_copilot_apply_to(&apply_to);
            let copilot_content = format!(
                "{copilot_fm}\n{}",
                format_with_bookends(&header_md, &preamble, &body, &postamble)
            );
            let copilot_path = copilot_instructions_dir.join(format!("{stem}.instructions.md"));
            fs::write(&copilot_path, &copilot_content)
                .expect("failed to write copilot instruction");
            eprintln!("  {}", copilot_path.display());
            count += 1;
        }
    }

    // --- skills/*/SKILL.md.tmpl -> .claude/skills/*/SKILL.md + .github/skills/*/SKILL.md ---
    let skills_dir = agent_dir.join("skills");
    if skills_dir.is_dir() {
        let claude_skills_dir = repo_root.join(".claude").join("skills");
        let copilot_skills_dir = repo_root.join(".github").join("skills");

        let mut skill_dirs: Vec<_> = fs::read_dir(&skills_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .collect();
        skill_dirs.sort_by_key(|e| e.file_name());

        for skill_entry in skill_dirs {
            let skill_path = skill_entry.path().join("SKILL.md.tmpl");
            if !skill_path.is_file() {
                continue;
            }

            let skill_name = skill_entry
                .file_name()
                .to_string_lossy()
                .to_string();

            let raw = fs::read_to_string(&skill_path).expect("failed to read skill template");
            let (frontmatter, body) = split_frontmatter(&raw);
            let body = substitute_vars(&body, &vars);
            let name = parse_field(&frontmatter, "skill_name").unwrap_or(skill_name.clone());
            let desc = parse_field(&frontmatter, "skill_description").unwrap_or_default();

            // Both Claude and Copilot use the same skill frontmatter format
            let skill_fm = format!("---\nname: {name}\ndescription: {desc}\n---");

            // Claude: .claude/skills/<name>/SKILL.md
            let claude_skill_dir = claude_skills_dir.join(&skill_name);
            let _ = fs::create_dir_all(&claude_skill_dir);
            let claude_content = format!(
                "{skill_fm}\n{}",
                format_with_bookends(&header_md, &preamble, &body, &postamble)
            );
            let claude_path = claude_skill_dir.join("SKILL.md");
            fs::write(&claude_path, &claude_content).expect("failed to write claude skill");
            eprintln!("  {}", claude_path.display());
            count += 1;

            // Copilot: .github/skills/<name>/SKILL.md
            let copilot_skill_dir = copilot_skills_dir.join(&skill_name);
            let _ = fs::create_dir_all(&copilot_skill_dir);
            let copilot_content = format!(
                "{skill_fm}\n{}",
                format_with_bookends(&header_md, &preamble, &body, &postamble)
            );
            let copilot_path = copilot_skill_dir.join("SKILL.md");
            fs::write(&copilot_path, &copilot_content).expect("failed to write copilot skill");
            eprintln!("  {}", copilot_path.display());
            count += 1;
        }
    }

    // --- Phase 6: Builtin hooks (generated BEFORE consumer hooks) ---
    let claude_hooks_dir = repo_root.join(".claude").join("hooks");
    let copilot_hooks_dir = repo_root.join(".github").join("hooks");
    let _ = fs::create_dir_all(&claude_hooks_dir);
    let _ = fs::create_dir_all(&copilot_hooks_dir);

    let mut all_hooks: Vec<HookMeta> =
        generate_builtin_hooks(cfg, &claude_hooks_dir, &copilot_hooks_dir, &mut count);

    // --- Consumer hooks: hooks/*.sh.tmpl -> .claude/hooks/*.sh + .github/hooks/*.sh ---
    let hooks_dir = agent_dir.join("hooks");
    if hooks_dir.is_dir() {
        let mut entries: Vec<_> = fs::read_dir(&hooks_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| {
                let name = e.file_name().to_string_lossy().to_string();
                name.ends_with(".sh.tmpl")
            })
            .collect();
        entries.sort_by_key(|e| e.file_name());

        for entry in entries {
            let path = entry.path();
            let tmpl_name = entry.file_name().to_string_lossy().to_string();
            // Strip .tmpl suffix: "check-byline.sh.tmpl" -> "check-byline.sh"
            let out_name = tmpl_name.trim_end_matches(".tmpl");

            let template = fs::read_to_string(&path).expect("failed to read hook template");

            // Parse matchers from frontmatter or fall back to naming convention
            let matchers = parse_hook_matchers(&template)
                .unwrap_or_else(|| matchers_from_name(out_name));

            // substitute general template variables first
            let template = substitute_vars(&template, &vars);

            // Claude: tool_input.field, hookSpecificOutput wrapper
            let claude_content = template.replace("{{HOOK_HELPERS}}", CLAUDE_HOOK_HELPERS);
            let claude_path = claude_hooks_dir.join(out_name);
            fs::write(&claude_path, &claude_content).expect("failed to write claude hook");
            #[cfg(unix)]
            set_executable(&claude_path);
            eprintln!("  {}", claude_path.display());
            count += 1;

            // Copilot: toolArgs (stringified JSON), flat output
            let copilot_content = template.replace("{{HOOK_HELPERS}}", COPILOT_HOOK_HELPERS);
            let copilot_path = copilot_hooks_dir.join(out_name);
            fs::write(&copilot_path, &copilot_content).expect("failed to write copilot hook");
            #[cfg(unix)]
            set_executable(&copilot_path);
            eprintln!("  {}", copilot_path.display());
            count += 1;

            all_hooks.push(HookMeta {
                name: out_name.to_string(),
                matchers,
            });
        }
    }

    // --- Phase 7: Auto-generate settings from discovered hooks ---
    count += generate_settings(repo_root, cfg, &all_hooks);

    count
}

/// Compute template variables from parsed crate data.
fn compute_template_vars(crates: &CrateMap, cfg: &Config) -> Vec<(String, String)> {
    let mut vars = Vec::new();

    // {{project_name}}
    vars.push(("project_name".to_string(), cfg.project_name.clone()));

    // {{mock_dir}} — relative path from repo root to mock workspace
    let mock_rel = cfg.mock_dir
        .strip_prefix(&cfg.repo_root)
        .unwrap_or(&cfg.mock_dir)
        .to_string_lossy()
        .to_string();
    vars.push(("mock_dir".to_string(), mock_rel));

    // {{crate_count}}
    let crate_count = crates
        .values()
        .filter(|c| c.short_name != cfg.project_name)
        .count();
    vars.push(("crate_count".to_string(), crate_count.to_string()));

    // {{crate_table}}
    vars.push(("crate_table".to_string(), compute_crate_table(crates, cfg)));

    // {{macro_table}}
    vars.push(("macro_table".to_string(), compute_macro_table(crates, cfg)));

    vars
}

/// Build a markdown table of crates.
fn compute_crate_table(crates: &CrateMap, cfg: &Config) -> String {
    let mut table = String::new();
    writeln!(table, "| Crate | Purpose |").unwrap();
    writeln!(table, "|-------|---------|").unwrap();

    let mut sorted: Vec<_> = crates.values().collect();
    sorted.sort_by_key(|c| &c.short_name);

    let prefix = &cfg.crate_prefix;
    for info in sorted {
        if info.short_name == cfg.project_name {
            continue;
        }
        let name = &info.short_name;
        let purpose = infer_crate_purpose(info);
        writeln!(table, "| {prefix}-{name} | {purpose} |").unwrap();
    }

    table.trim_end().to_string()
}

/// Infer a one-line purpose from a crate's items.
fn infer_crate_purpose(info: &CrateInfo) -> String {
    let mut types: Vec<String> = Vec::new();
    for item in &info.items {
        match item {
            Item::Trait(t) => types.push(t.name.clone()),
            Item::Struct(s) => types.push(s.name.clone()),
            _ => {}
        }
    }
    if types.is_empty() {
        return format!("{} subsystem", info.short_name);
    }
    let max = 3.min(types.len());
    let shown: Vec<_> = types[..max].iter().map(|t| format!("`{t}`")).collect();
    let suffix = if types.len() > max {
        format!(" +{}", types.len() - max)
    } else {
        String::new()
    };
    format!("{}{suffix}", shown.join(", "))
}

/// Build the macros table for agent instructions from config.
fn compute_macro_table(crates: &CrateMap, cfg: &Config) -> String {
    let macros = cfg.effective_agent_macros();

    // Check which macros actually exist
    let mut found = std::collections::BTreeSet::new();
    for info in crates.values() {
        for item in &info.items {
            if let Item::Macro(m) = item {
                if m.name.starts_with("define_") {
                    found.insert(m.name.clone());
                }
            }
        }
    }

    let mut table = String::new();
    writeln!(table, "| Macro | Purpose | Usage |").unwrap();
    writeln!(table, "|-------|---------|-------|").unwrap();

    for (name, purpose, usage) in macros {
        if found.contains(name.as_str()) {
            writeln!(table, "| `{name}!` | {purpose} | {usage} |").unwrap();
        }
    }

    // Any extra macros not in config
    for name in &found {
        if !macros.iter().any(|(n, _, _)| n == name) {
            writeln!(table, "| `{name}!` | Custom | `{name}!(...)` |").unwrap();
        }
    }

    table.trim_end().to_string()
}

/// Read a template file and substitute variables.
fn read_and_substitute(path: &Path, vars: &[(String, String)]) -> String {
    let raw = fs::read_to_string(path).expect("failed to read template");
    let (_frontmatter, body) = split_frontmatter(&raw);
    substitute_vars(&body, vars)
}

/// Replace {{var}} placeholders in text.
fn substitute_vars(text: &str, vars: &[(String, String)]) -> String {
    let mut result = text.to_string();
    for (key, value) in vars {
        result = result.replace(&format!("{{{{{key}}}}}"), value);
    }
    result
}

/// Split YAML frontmatter from body content.
fn split_frontmatter(text: &str) -> (String, String) {
    let trimmed = text.trim_start();
    if !trimmed.starts_with("---") {
        return (String::new(), text.to_string());
    }

    let after_first = &trimmed[3..];
    if let Some(end) = after_first.find("\n---") {
        let fm = after_first[..end].to_string();
        let body = after_first[end + 4..].to_string();
        (fm, body)
    } else {
        (String::new(), text.to_string())
    }
}

/// Parse apply_to field from frontmatter YAML.
fn parse_apply_to(frontmatter: &str) -> Vec<String> {
    let mut patterns = Vec::new();
    let mut in_list = false;

    for line in frontmatter.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("apply_to:") {
            let value = trimmed.trim_start_matches("apply_to:").trim();
            if value.starts_with('[') {
                // Inline array: ["pattern1", "pattern2"]
                let inner = value.trim_start_matches('[').trim_end_matches(']');
                for item in inner.split(',') {
                    let p = item.trim().trim_matches('"').trim_matches('\'');
                    if !p.is_empty() {
                        patterns.push(p.to_string());
                    }
                }
            } else if value.is_empty() {
                in_list = true;
            } else {
                patterns.push(value.trim_matches('"').trim_matches('\'').to_string());
            }
        } else if in_list && trimmed.starts_with("- ") {
            let p = trimmed[2..].trim().trim_matches('"').trim_matches('\'');
            if !p.is_empty() {
                patterns.push(p.to_string());
            }
        } else if in_list && !trimmed.is_empty() && !trimmed.starts_with('#') {
            in_list = false;
        }
    }

    patterns
}

/// Parse a simple key: value field from frontmatter.
fn parse_field(frontmatter: &str, key: &str) -> Option<String> {
    let prefix = format!("{key}:");
    for line in frontmatter.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with(&prefix) {
            let value = trimmed[prefix.len()..].trim();
            return Some(value.trim_matches('"').trim_matches('\'').to_string());
        }
    }
    None
}

/// Format glob patterns as Claude's paths: YAML list.
fn format_claude_paths(patterns: &[String]) -> String {
    if patterns.is_empty() {
        return String::new();
    }
    let mut fm = String::from("---\npaths:\n");
    for p in patterns {
        writeln!(fm, "  - \"{p}\"").unwrap();
    }
    fm.push_str("---");
    fm
}

/// Format glob patterns as Copilot's applyTo: string.
fn format_copilot_apply_to(patterns: &[String]) -> String {
    if patterns.is_empty() {
        return String::new();
    }
    let joined = patterns.join(",");
    format!("---\napplyTo: \"{joined}\"\n---")
}

/// Read an optional template file, returning empty string if missing.
fn read_optional_template(path: &Path) -> String {
    if path.is_file() {
        let raw = fs::read_to_string(path).unwrap_or_default();
        let (_fm, body) = split_frontmatter(&raw);
        body.trim().to_string()
    } else {
        String::new()
    }
}

/// Assemble content with preamble before body and postamble after.
fn format_with_bookends(header: &str, preamble: &str, body: &str, postamble: &str) -> String {
    let mut out = String::new();
    out.push_str(header);
    out.push('\n');
    if !preamble.is_empty() {
        out.push('\n');
        out.push_str(preamble);
        out.push('\n');
    }
    out.push('\n');
    out.push_str(body);
    if !postamble.is_empty() {
        out.push('\n');
        out.push_str(postamble);
        out.push('\n');
    }
    out
}
