//--------------------------------------------------------------------------------------------------
// Copyright (c) 2026                   orgrinrt                 ort@hiisi.digital
// SPDX-License-Identifier: MPL-2.0     https://mozilla.org/MPL/2.0        contact@hiisi.digital
//--------------------------------------------------------------------------------------------------

//! One enumeration of every subcommand and every project tool.
//!
//! # Why this exists
//!
//! A builtin subcommand ([`crate::entry::help`]) and a project tool
//! ([`mockspace_lint_rules::tool::Tool`]) already describe themselves the
//! same way: a name, a one-line summary, declared positional arguments, and
//! an optional longer help body. Nothing combined the two populations into
//! one answer to "what can I run here", so an agent (or a person) either
//! read `mock help` for the builtins and separately walked `<mock>/tools/`
//! for the rest, or somebody hand-wrote a list that was correct on the day
//! it was written and wrong the day after.
//!
//! [`enumerate`] is the one place both populations are read from. `mock
//! tools` ([`crate::entry::dispatch`]) prints its result directly; the
//! builtin agent rule generated by [`crate::render_agent`] embeds a snapshot
//! of it and tells the reader to re-run the live command rather than trust
//! the snapshot, for the reason given on that rule.
//!
//! # What is standardised, and what is not
//!
//! Both populations share [`mockspace_lint_rules::tool::ArgSpec`] for their
//! declared arguments and [`mockspace_lint_rules::tool::usage_from`] for
//! rendering a usage line from a name and those arguments. That is the
//! standardisation: one shape, one renderer, used by both.
//!
//! **What is not standardised is enforcement.** A project tool's declared
//! arguments are checked against a real invocation by
//! [`mockspace_lint_rules::tool::missing_required`] and
//! [`mockspace_lint_rules::tool::contract_faults`], which run every time
//! `mock <tool>` is dispatched. A builtin's declared arguments are checked
//! against nothing: `dispatch.rs` parses each builtin's flags by hand, and
//! nothing here or there compares that parsing against `Cmd::args`. See
//! `every_builtin_declaring_a_required_argument_is_named_here_deliberately`
//! in this module's tests for the one builtin (`panel`) that currently
//! declares a required argument, and how its own dispatch enforces it
//! without the shared mechanism: a claim of "declared the same way" that
//! silently stopped meaning "enforced the same way" is exactly the kind of
//! drift a claim of totality is supposed to name rather than imply.

use mockspace_lint_rules::LintPack;
use mockspace_lint_rules::tool::{ArgSpec, duplicate_tool_names, usage_from, usage_line};

/// Which population a [`Listing`] came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Source {
    /// A subcommand the engine itself answers to.
    Builtin,
    /// A tool declared under `<mock>/tools/<name>/` in this project.
    Project,
}

impl Source {
    #[must_use]
    pub fn label(self) -> &'static str {
        match self {
            Self::Builtin => "builtin",
            Self::Project => "project",
        }
    }
}

/// One command, builtin or project, described uniformly.
pub struct Listing {
    pub name:    String,
    pub summary: String,
    pub usage:   String,
    pub args:    Vec<ArgSpec>,
    pub help:    String,
    pub source:  Source,
}

/// Every builtin subcommand, then every project tool.
///
/// Builtins first because that mirrors `mock help`'s own ordering (the
/// round lifecycle, then everything else); tools follow, in the order the
/// pack loaded them. Neither group is re-sorted: a builtin's position in
/// this list is stable across runs because [`crate::entry::help::commands`]
/// is a `const` array, and a tool's position is stable for as long as the
/// pack loads its directories in a stable order, which
/// [`mockspace_lint_rules::tool::duplicate_tool_names`] already depends on
/// being able to name reliably.
///
/// **No name collision between the two groups is possible by construction**,
/// and this function does not re-check it: [`crate::entry::tool::builtin_collision`]
/// already refuses a project tool sharing a builtin's name before its
/// directory is ever loaded into `pack.tools`, and
/// `every_builtin_subcommand_is_refused_as_a_tool_name` in
/// `crate::entry::tool` pins that for every builtin, not a sample. A
/// collision *within* the project-tool group is a live possibility
/// ([`duplicate_tool_names`] exists because two tool directories can both
/// declare the same `Tool::name()`), and [`duplicates`] reports it
/// separately rather than silently listing both.
#[must_use]
pub fn enumerate(pack: &LintPack) -> Vec<Listing> {
    let mut out: Vec<Listing> = crate::entry::help::commands()
        .iter()
        .map(|c| {
            Listing {
                name:    c.name.to_string(),
                summary: c.summary.to_string(),
                usage:   usage_from(c.name, c.args),
                args:    c.args.to_vec(),
                help:    c.help.to_string(),
                source:  Source::Builtin,
            }
        })
        .collect();

    for t in &pack.tools {
        out.push(Listing {
            name:    t.name().to_string(),
            summary: t.description().to_string(),
            usage:   usage_line(t.as_ref()),
            args:    t.args().to_vec(),
            help:    t.help().to_string(),
            source:  Source::Project,
        });
    }

    out
}

/// Project tool names registered more than once, sorted. Empty is the
/// common and expected case; see [`enumerate`]'s doc for why builtins never
/// appear here.
#[must_use]
pub fn duplicates(pack: &LintPack) -> Vec<String> {
    duplicate_tool_names(&pack.tools)
}

/// The short table `mock tools` prints by default: one line per entry.
#[must_use]
pub fn render_table(listings: &[Listing]) -> String {
    let mut s = String::new();
    render_group(&mut s, "BUILTIN SUBCOMMANDS", listings, Source::Builtin);
    s.push('\n');
    render_group(&mut s, "PROJECT TOOLS", listings, Source::Project);
    s
}

fn render_group(out: &mut String, heading: &str, listings: &[Listing], source: Source) {
    let group: Vec<&Listing> = listings.iter().filter(|l| l.source == source).collect();
    out.push_str(heading);
    out.push('\n');
    if group.is_empty() {
        out.push_str("    (none declared)\n");
        return;
    }
    let width = group.iter().map(|l| l.usage.len()).max().unwrap_or(0);
    for l in group {
        use std::fmt::Write as _;
        let _ = writeln!(out, "    {:<width$}  {}", l.usage, l.summary, width = width);
    }
}

/// The full listing `mock tools --long` prints: usage, summary, declared
/// arguments, and the long help body, one block per entry.
#[must_use]
pub fn render_long(listings: &[Listing]) -> String {
    let mut s = String::new();
    for group in [Source::Builtin, Source::Project] {
        let heading = match group {
            Source::Builtin => "BUILTIN SUBCOMMANDS",
            Source::Project => "PROJECT TOOLS",
        };
        s.push_str(heading);
        s.push('\n');
        let entries: Vec<&Listing> = listings.iter().filter(|l| l.source == group).collect();
        if entries.is_empty() {
            s.push_str("    (none declared)\n\n");
            continue;
        }
        for l in entries {
            use std::fmt::Write as _;
            let _ = writeln!(s, "  {}", l.usage);
            let _ = writeln!(s, "      {}", l.summary);
            for a in &l.args {
                let mark = if a.required { "required" } else { "optional" };
                let _ = writeln!(s, "      {:<12} ({mark}) {}", a.name, a.description);
            }
            if !l.help.is_empty() {
                let _ = writeln!(s, "      {}", l.help);
            }
            s.push('\n');
        }
    }
    s
}

#[cfg(test)]
mod tests {
    use mockspace_lint_rules::tool::{NotALint, Tool, ToolContext, ToolReport};

    use super::*;

    struct Greet;
    impl Tool for Greet {
        fn name(&self) -> &'static str {
            "greet"
        }

        fn description(&self) -> &'static str {
            "say hello to a name"
        }

        fn not_a_lint(&self) -> NotALint {
            NotALint::TakesAQuestion
        }

        fn args(&self) -> &[ArgSpec] {
            &[ArgSpec {
                name:        "who",
                required:    true,
                description: "who to greet",
            }]
        }

        fn help(&self) -> &'static str {
            "Prints a greeting for the given name."
        }

        fn run(&self, _ctx: &ToolContext<'_>) -> ToolReport {
            ToolReport::reported("hi", 1)
        }
    }

    struct Silent;
    impl Tool for Silent {
        fn name(&self) -> &'static str {
            "silent"
        }

        fn description(&self) -> &'static str {
            "does nothing observable"
        }

        fn not_a_lint(&self) -> NotALint {
            NotALint::NoFailingCase
        }

        fn run(&self, _ctx: &ToolContext<'_>) -> ToolReport {
            ToolReport::reported("", 0)
        }
    }

    fn pack_with(tools: Vec<Box<dyn Tool>>) -> LintPack {
        LintPack {
            tools,
            ..LintPack::default()
        }
    }

    #[test]
    fn every_builtin_appears_and_nothing_else_does_with_an_empty_pack() {
        let listings = enumerate(&pack_with(vec![]));
        let builtin_names: Vec<&str> = listings
            .iter()
            .filter(|l| l.source == Source::Builtin)
            .map(|l| l.name.as_str())
            .collect();
        // Not a sample: every name the dispatcher answers to, via the same
        // accessor `mock help` itself renders from.
        for name in crate::entry::help::known_commands() {
            assert!(
                builtin_names.contains(&name),
                "`{name}` is missing from the catalogue"
            );
        }
        assert!(
            listings.iter().all(|l| l.source == Source::Builtin),
            "an empty pack must contribute zero project entries"
        );
    }

    #[test]
    fn a_project_tool_appears_once_with_its_declared_shape() {
        let listings = enumerate(&pack_with(vec![Box::new(Greet)]));
        let g = listings
            .iter()
            .find(|l| l.name == "greet")
            .expect("the declared tool must appear in the catalogue");
        assert_eq!(g.source, Source::Project);
        assert_eq!(g.summary, "say hello to a name");
        assert_eq!(g.usage, "mock greet <who>");
        assert_eq!(g.args.len(), 1);
        assert_eq!(g.help, "Prints a greeting for the given name.");

        // and it appears exactly once, not once per builtin it happens to
        // share nothing with
        assert_eq!(listings.iter().filter(|l| l.name == "greet").count(), 1);
    }

    #[test]
    fn a_tool_with_no_declared_help_or_args_renders_as_an_honest_blank() {
        // The negative arm: `Greet`'s populated fields prove the plumbing
        // carries a value through. `Silent` proves it does not invent one
        // when the tool declared nothing.
        let listings = enumerate(&pack_with(vec![Box::new(Silent)]));
        let s = listings.iter().find(|l| l.name == "silent").unwrap();
        assert!(s.args.is_empty());
        assert_eq!(s.help, "");
        assert_eq!(s.usage, "mock silent");
    }

    #[test]
    fn duplicate_project_tool_names_are_reported_and_builtins_are_never_candidates() {
        struct A;
        impl Tool for A {
            fn name(&self) -> &'static str {
                "audit"
            }

            fn description(&self) -> &'static str {
                "one"
            }

            fn not_a_lint(&self) -> NotALint {
                NotALint::NoFailingCase
            }

            fn run(&self, _c: &ToolContext<'_>) -> ToolReport {
                ToolReport::reported("", 1)
            }
        }
        struct B;
        impl Tool for B {
            fn name(&self) -> &'static str {
                "audit"
            }

            fn description(&self) -> &'static str {
                "two"
            }

            fn not_a_lint(&self) -> NotALint {
                NotALint::NoFailingCase
            }

            fn run(&self, _c: &ToolContext<'_>) -> ToolReport {
                ToolReport::reported("", 1)
            }
        }
        let pack = pack_with(vec![Box::new(A), Box::new(B)]);
        assert_eq!(duplicates(&pack), vec!["audit".to_string()]);

        // the negative: a lone tool with no collision reports nothing
        assert_eq!(
            duplicates(&pack_with(vec![Box::new(Greet)])),
            Vec::<String>::new()
        );
    }

    #[test]
    fn every_builtin_declaring_a_required_argument_is_named_here_deliberately() {
        // The enforcement gap named in the module doc, made mechanical
        // rather than merely stated. `missing_required` and
        // `contract_faults` run against a project tool's declared
        // arguments on every dispatch; nothing shared runs against a
        // builtin's, because a builtin is dispatched by hand rather than
        // through the tool contract.
        //
        // `panel` is the one builtin that currently declares a required
        // argument (`verb`), and its own dispatch (`crate::entry::panel::run`)
        // enforces it directly: `mock panel` with no verb refuses, pinned by
        // `a_missing_verb_is_refused` in that module. So the claim is true,
        // just enforced per-builtin rather than by one shared mechanism.
        //
        // This test is the tripwire for the next one: if a future builtin
        // declares a required argument, it is named here and its own
        // enforcement test is named too, or the declaration is a claim
        // nothing backs.
        let with_required: Vec<&str> = crate::entry::help::commands()
            .iter()
            .filter(|c| c.args.iter().any(|a| a.required))
            .map(|c| c.name)
            .collect();
        assert_eq!(
            with_required,
            vec!["panel"],
            "a builtin started (or stopped) declaring a required argument; update this              list and confirm its own dispatch enforces (or no longer needs to enforce) it"
        );
    }

    #[test]
    fn render_table_lists_a_builtin_and_a_project_tool_each_once() {
        let listings = enumerate(&pack_with(vec![Box::new(Greet)]));
        let table = render_table(&listings);
        assert!(table.contains("BUILTIN SUBCOMMANDS"));
        assert!(table.contains("PROJECT TOOLS"));
        assert!(
            table.contains("mock lock"),
            "a known builtin's usage must appear:\n{table}"
        );
        assert!(
            table.contains("mock greet <who>"),
            "the tool's usage must appear:\n{table}"
        );
        assert!(table.contains("say hello to a name"));
    }

    #[test]
    fn render_table_says_so_when_no_project_tools_are_declared() {
        // The case that must fail if the section were simply omitted: a
        // reader seeing no "PROJECT TOOLS" heading at all cannot tell
        // "this project has none" from "the renderer forgot the section".
        let table = render_table(&enumerate(&pack_with(vec![])));
        assert!(table.contains("PROJECT TOOLS"));
        assert!(table.contains("(none declared)"));
    }

    #[test]
    fn render_long_carries_args_and_help_that_the_table_omits() {
        let listings = enumerate(&pack_with(vec![Box::new(Greet)]));
        let long = render_long(&listings);
        assert!(
            long.contains("who"),
            "the declared argument name must appear:\n{long}"
        );
        assert!(long.contains("required"));
        assert!(
            long.contains("who to greet"),
            "the argument's description must appear:\n{long}"
        );
        assert!(long.contains("Prints a greeting for the given name."));

        let table = render_table(&listings);
        assert!(
            !table.contains("who to greet"),
            "the short table must not carry the long body"
        );
    }
}
