//--------------------------------------------------------------------------------------------------
// Copyright (c) 2026                   orgrinrt                 ort@hiisi.digital
// SPDX-License-Identifier: MPL-2.0     https://mozilla.org/MPL/2.0        contact@hiisi.digital
//--------------------------------------------------------------------------------------------------

//! A commit's author and committer reach the message lints, at both gates.
//!
//! The commit gate hands them over as flags, read by the commit-msg hook from
//! `git var`. The push gate hands them over inside the batch stream, one pair
//! per commit, read by the pre-push hook from `git log`. Both halves are held
//! here against the parser and against the real hook body, so a hook and an
//! engine that stopped agreeing about the framing fail in a test rather than
//! in a push.

use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode, Stdio};
use std::sync::{Arc, Mutex};

use mockspace_lint_rules::{
    Lint,
    LintError,
    LintMode,
    LintPack,
    MessageContext,
    MessageDomain,
    MessageLint,
};

use super::message::{Request, clean_ident, run, run_batch, split_batch};
use crate::config::Config;

// --- the identity as git writes it --------------------------------------------------------

#[test]
fn what_git_var_prints_loses_its_date_and_zone() {
    // `git var GIT_AUTHOR_IDENT` appends the timestamp and the zone, which are
    // not part of who made the commit and would defeat a glob written against
    // `Name <mailbox>`.
    assert_eq!(
        clean_ident("Claude <noreply@anthropic.com> 1791567502 +0000").as_deref(),
        Some("Claude <noreply@anthropic.com>")
    );
    assert_eq!(
        clean_ident("Jane Doe <jane@example.com> 1791567502 -0530").as_deref(),
        Some("Jane Doe <jane@example.com>")
    );
}

#[test]
fn what_git_log_prints_is_already_clean_and_stays_so() {
    assert_eq!(
        clean_ident("Jane Doe <jane@example.com>").as_deref(),
        Some("Jane Doe <jane@example.com>")
    );
}

#[test]
fn an_identity_with_nothing_in_it_is_absent_rather_than_empty() {
    // An empty string handed to a lint reads as a person with no name, which is
    // a different claim from "nobody told us who", and the lint must be able to
    // tell them apart.
    assert_eq!(clean_ident(""), None);
    assert_eq!(clean_ident("   \n"), None);
}

// --- the push gate's framing --------------------------------------------------------------

#[test]
fn a_record_whose_header_carries_two_identities_yields_both() {
    let recs = split_batch(
        "Claude <noreply@anthropic.com>\x1eJane Doe <jane@example.com>\x1eabc123 feat: x\x1ffeat: x\n\0",
        "<stdin>",
    );
    assert_eq!(recs.len(), 1);
    assert_eq!(recs[0].origin, "abc123 feat: x");
    assert_eq!(recs[0].message, "feat: x\n");
    assert_eq!(
        recs[0].author.as_deref(),
        Some("Claude <noreply@anthropic.com>")
    );
    assert_eq!(
        recs[0].committer.as_deref(),
        Some("Jane Doe <jane@example.com>")
    );
}

#[test]
fn a_record_written_before_identities_existed_still_parses_with_none() {
    // A hook generated by an earlier engine sends `<origin>\x1f<message>`, and an
    // engine that updated first must not misread that as carrying an identity.
    let recs = split_batch("abc123 feat: x\x1ffeat: x\n\0", "<stdin>");
    assert_eq!(recs.len(), 1);
    assert_eq!(recs[0].origin, "abc123 feat: x");
    assert_eq!(recs[0].author, None);
    assert_eq!(recs[0].committer, None);
}

#[test]
fn a_header_with_one_separator_does_not_parse() {
    // Exactly two separators make an identity header and none make an origin.
    // One is neither: it is a header cut short, or a name that held the byte, and
    // reading it as an origin would hand a lint half of a header as a subject
    // while the identity it should have judged went missing.
    let recs = split_batch("abc\x1edef\x1fbody\0", "<stdin>");
    assert!(recs[0].fault.is_some(), "got: {:?}", recs[0]);
}

#[test]
fn a_name_holding_the_separator_leaves_a_header_that_does_not_parse() {
    // The hook strips the byte from every name, so this is what arrives from a
    // hook that did not, or from anything else writing the framing by hand. The
    // split lands inside the name, the author is then half a name with no
    // mailbox, and a record that falls open here is how an identity goes
    // unjudged.
    let recs = split_batch("X\x1eY <y@y>\x1eB <b@b>\x1eh s\x1fm\0", "<stdin>");
    assert_eq!(recs.len(), 1);
    assert!(recs[0].fault.is_some(), "got: {:?}", recs[0]);
}

#[test]
fn an_identity_that_is_not_a_name_and_a_mailbox_does_not_parse() {
    for header in ["Jane\x1eB <b@b>\x1eh s", "A <a@a>\x1eBob\x1eh s", "Jane Doe\x1eBob Roe\x1eh s"]
    {
        let recs = split_batch(&format!("{header}\x1fm\0"), "<stdin>");
        assert!(recs[0].fault.is_some(), "{header:?} parsed: {:?}", recs[0]);
    }
}

#[test]
fn a_well_formed_header_and_an_older_one_carry_no_fault() {
    // The controls for the three above: the same parser, a header that is right.
    let identity = split_batch("A <a@a>\x1eB <b@b>\x1eh s\x1fm\0", "<stdin>");
    assert_eq!(identity[0].fault, None);
    let older = split_batch("h s\x1fm\0", "<stdin>");
    assert_eq!(older[0].fault, None);
    let none = split_batch("\x1e\x1eh s\x1fm\0", "<stdin>");
    assert_eq!(
        none[0].fault, None,
        "two empty identities are absent, not a fault"
    );
}

#[test]
fn a_record_that_does_not_parse_is_refused_and_never_reaches_a_lint() {
    // Both halves, so neither falls open alone: the hook strips, and the engine
    // refuses what still does not parse. The good record beside it is the
    // control, and has to be judged.
    let (_tmp, cfg) = config();
    let seen: Seen = Arc::default();
    let stream = "Jane Doe <j@e>\x1eJane Doe <j@e>\x1eaaa feat: ok\x1ffeat: ok\n\0\
                  X\x1eY <y@y>\x1eB <b@b>\x1ebbb feat: bad\x1ffeat: bad\n\0";
    let (checked, failed) = run_batch(
        &cfg,
        &probe_pack(&seen),
        LintMode::Push,
        MessageDomain::CommitMessage,
        stream,
        "<stdin>",
        None,
        None,
    );
    assert_eq!((checked, failed), (2, 1));
    assert_eq!(
        seen.lock().unwrap().len(),
        1,
        "only the good record reached a lint"
    );
}

#[test]
fn an_older_engine_reads_a_newer_hooks_stream_with_the_message_whole() {
    // The other half of the compatibility claim. `legacy_split_batch` is the
    // parser the engine had before records carried an identity, verbatim: it
    // takes everything up to the first 0x1f as the origin and everything after
    // as the message. Fed what the real hook now sends, it must still get each
    // commit's message exactly, with only the origin longer than it expected.
    fn legacy_split_batch(text: &str, default_origin: &str) -> Vec<(String, String)> {
        text.split('\0')
            .filter(|r| !r.is_empty())
            .map(|r| {
                match r.split_once('\x1f') {
                    Some((o, m)) => (o.to_string(), m.to_string()),
                    None => (default_origin.to_string(), r.to_string()),
                }
            })
            .collect()
    }

    let repo = tempfile::tempdir().unwrap();
    let dir = repo.path();
    git_in(dir, &[], &["init", "-q", "-b", "main"]);
    let person = "Jane Doe <jane@example.com>";
    commit_as(
        dir,
        person,
        person,
        "feat: first\n\nwith a body\nover two lines",
    );
    commit_as(dir, person, person, "fix: second");
    let head = git_in(dir, &[], &["rev-parse", "HEAD"]);

    let sent = what_the_push_scan_sends(dir, &head);
    let text = String::from_utf8_lossy(&sent).into_owned();
    let old = legacy_split_batch(&text, "<stdin>");
    assert_eq!(old.len(), 2, "one record per commit. got: {text:?}");
    let messages: Vec<&str> = old.iter().map(|(_, m)| m.trim_end()).collect();
    assert!(
        messages.contains(&"feat: first\n\nwith a body\nover two lines"),
        "got: {messages:?}"
    );
    assert!(messages.contains(&"fix: second"), "got: {messages:?}");
    // and what the older engine calls the origin carries the identity in front
    assert!(
        old.iter().all(|(o, _)| o.contains("jane@example.com")),
        "got: {old:?}"
    );
}

#[test]
fn a_separator_inside_a_name_is_stripped_by_the_hook_so_the_record_parses() {
    // Git accepts these bytes in a name. The hook takes both out of the four
    // fields before framing, so the identity arrives as the name without them
    // and the record is whole.
    let repo = tempfile::tempdir().unwrap();
    let dir = repo.path();
    git_in(dir, &[], &["init", "-q", "-b", "main"]);
    git_in(
        dir,
        &[
            ("GIT_AUTHOR_NAME", "Ja\x1ene\x1f Doe"),
            ("GIT_AUTHOR_EMAIL", "ja\x1fne@example.com"),
            ("GIT_COMMITTER_NAME", "Bob\x1e Roe"),
            ("GIT_COMMITTER_EMAIL", "bob@example.com"),
        ],
        &["commit", "-q", "--no-verify", "--allow-empty", "-m", "feat: by a strange name"],
    );
    let head = git_in(dir, &[], &["rev-parse", "HEAD"]);

    let sent = what_the_push_scan_sends(dir, &head);
    let text = String::from_utf8_lossy(&sent).into_owned();
    let recs = split_batch(&text, "<stdin>");
    assert_eq!(recs.len(), 1, "got: {text:?}");
    assert_eq!(recs[0].fault, None, "got: {:?}", recs[0]);
    assert_eq!(
        recs[0].author.as_deref(),
        Some("Jane Doe <jane@example.com>")
    );
    assert_eq!(
        recs[0].committer.as_deref(),
        Some("Bob Roe <bob@example.com>")
    );
    assert_eq!(recs[0].message.trim_end(), "feat: by a strange name");
}

#[test]
fn separators_inside_the_message_stay_in_the_message() {
    // The header ends at the first 0x1f; whatever follows, 0x1e and 0x1f
    // included, is the commit's own text.
    let recs = split_batch(
        "A <a@a>\x1eB <b@b>\x1eh s\x1fline\x1e one\x1f two\0",
        "<stdin>",
    );
    assert_eq!(recs[0].message, "line\x1e one\x1f two");
    assert_eq!(recs[0].author.as_deref(), Some("A <a@a>"));
}

#[test]
fn an_empty_identity_field_in_a_header_is_absent() {
    let recs = split_batch("\x1eB <b@b>\x1eh s\x1fm\0", "<stdin>");
    assert_eq!(recs[0].author, None);
    assert_eq!(recs[0].committer.as_deref(), Some("B <b@b>"));
}

// --- what a lint is handed ----------------------------------------------------------------

/// What the probe saw, in order of the runs.
type Seen = Arc<Mutex<Vec<(MessageDomain, Option<String>, Option<String>)>>>;

/// Records the identity it is handed and refuses any identity naming `refuse`.
///
/// The refusal is the probe's own policy and stands for none of the pack's: it
/// exists so the exit code can be seen to depend on the identity alone.
struct IdentityProbe {
    seen:   Seen,
    refuse: &'static str,
}

impl Lint for IdentityProbe {
    fn name(&self) -> &'static str {
        "identity-probe"
    }
}

impl MessageLint for IdentityProbe {
    fn check_message(&self, ctx: &MessageContext) -> Vec<LintError> {
        self.seen.lock().unwrap().push((
            ctx.domain,
            ctx.author.map(str::to_string),
            ctx.committer.map(str::to_string),
        ));
        [ctx.author, ctx.committer]
            .into_iter()
            .flatten()
            .filter(|who| who.contains(self.refuse))
            .map(|who| {
                LintError::error(
                    ctx.origin.to_string(),
                    1,
                    "identity-probe",
                    format!("refused {who}"),
                )
            })
            .collect()
    }
}

fn probe_pack(seen: &Seen) -> LintPack {
    LintPack {
        message_lints: vec![Box::new(IdentityProbe {
            seen:   Arc::clone(seen),
            refuse: "Claude",
        })],
        ..LintPack::default()
    }
}

fn config() -> (tempfile::TempDir, Config) {
    let tmp = tempfile::tempdir().unwrap();
    let mock = tmp.path().join("mock");
    std::fs::create_dir_all(&mock).unwrap();
    std::fs::write(mock.join("mockspace.toml"), "project_name = \"probe\"\n").unwrap();
    let cfg = Config::from_dir(&mock);
    (tmp, cfg)
}

fn request<'a>(
    domain: MessageDomain,
    author: Option<&'a str>,
    committer: Option<&'a str>,
) -> Request<'a> {
    Request {
        domain,
        message: "feat: a subject\n".to_string(),
        origin: "COMMIT_EDITMSG".to_string(),
        command: None,
        tool: None,
        author,
        committer,
    }
}

#[test]
fn the_gate_hands_a_commits_author_and_committer_to_every_message_lint() {
    let (_tmp, cfg) = config();
    let seen: Seen = Arc::default();
    let req = request(
        MessageDomain::CommitMessage,
        Some("Jane Doe <jane@example.com>"),
        Some("Bob Roe <bob@example.com>"),
    );
    run(&cfg, &probe_pack(&seen), LintMode::Commit, &req);
    assert_eq!(*seen.lock().unwrap(), vec![(
        MessageDomain::CommitMessage,
        Some("Jane Doe <jane@example.com>".to_string()),
        Some("Bob Roe <bob@example.com>".to_string()),
    )]);
}

#[test]
fn a_forge_body_reaches_the_lints_with_no_identity_at_all() {
    // No git hook ever sees a pull-request body, so it has neither author nor
    // committer, and that has to arrive as absent rather than as a blank one.
    let (_tmp, cfg) = config();
    let seen: Seen = Arc::default();
    let req = request(MessageDomain::PullRequestBody, None, None);
    run(&cfg, &probe_pack(&seen), LintMode::Commit, &req);
    assert_eq!(*seen.lock().unwrap(), vec![(
        MessageDomain::PullRequestBody,
        None,
        None
    )]);
}

#[test]
fn an_identity_sent_with_a_forge_body_is_not_handed_on() {
    // The flags are valid on any domain at the command line, and a body they
    // arrive with has no author in git's sense. Handing the lint a name for it
    // would let a policy about commits fire on a pull request.
    let (_tmp, cfg) = config();
    let seen: Seen = Arc::default();
    let req = request(
        MessageDomain::PullRequestBody,
        Some("Claude <noreply@anthropic.com>"),
        Some("Claude <noreply@anthropic.com>"),
    );
    let code = run(&cfg, &probe_pack(&seen), LintMode::Commit, &req);
    assert_eq!(*seen.lock().unwrap(), vec![(
        MessageDomain::PullRequestBody,
        None,
        None
    )]);
    assert_eq!(code, ExitCode::SUCCESS);
}

#[test]
fn the_exit_code_turns_on_the_identity_alone() {
    // The message is the same clean subject in every run below, so the only
    // thing that can move the verdict is who the commit is by. The person is
    // the control: without it, a probe that refused everything would pass.
    let (_tmp, cfg) = config();
    let seen: Seen = Arc::default();
    let pack = probe_pack(&seen);
    let verdict = |author, committer| {
        run(
            &cfg,
            &pack,
            LintMode::Commit,
            &request(MessageDomain::CommitMessage, author, committer),
        )
    };
    let person = Some("Jane Doe <jane@example.com>");
    let agent = Some("Claude <noreply@anthropic.com>");
    assert_eq!(verdict(person, person), ExitCode::SUCCESS);
    assert_eq!(verdict(agent, person), ExitCode::FAILURE);
    assert_eq!(verdict(person, agent), ExitCode::FAILURE);
}

// --- the pre-push hook body, run for real -------------------------------------------------

fn git_in(dir: &Path, envs: &[(&str, &str)], args: &[&str]) -> String {
    let mut c = Command::new("git");
    c.current_dir(dir).args(args);
    for (k, v) in envs {
        c.env(k, v);
    }
    let out = c.output().expect("git runs");
    assert!(out.status.success(), "git {args:?}: {out:?}");
    String::from_utf8_lossy(&out.stdout).trim().to_string()
}

fn commit_as(repo: &Path, author: &str, committer: &str, subject: &str) {
    let split = |who: &str| -> (String, String) {
        let (name, rest) = who.split_once(" <").expect("Name <mailbox>");
        (name.to_string(), rest.trim_end_matches('>').to_string())
    };
    let (an, ae) = split(author);
    let (cn, ce) = split(committer);
    git_in(
        repo,
        &[
            ("GIT_AUTHOR_NAME", &an),
            ("GIT_AUTHOR_EMAIL", &ae),
            ("GIT_COMMITTER_NAME", &cn),
            ("GIT_COMMITTER_EMAIL", &ce),
        ],
        &["commit", "-q", "--no-verify", "--allow-empty", "-m", subject],
    );
}

/// A PATH holding git and coreutils but no `mock` of the machine's own.
fn path_with(stub_dir: &Path) -> String {
    let which = Command::new("sh")
        .arg("-c")
        .arg("command -v git")
        .output()
        .unwrap();
    let git = String::from_utf8_lossy(&which.stdout).trim().to_string();
    let git_dir = Path::new(&git)
        .parent()
        .map(|p| p.display().to_string())
        .unwrap_or_default();
    format!(
        "{}:{git_dir}:/usr/local/bin:/usr/bin:/bin",
        stub_dir.display()
    )
}

/// Run the real pre-push scan body in `repo` against a stub launcher that keeps
/// whatever it is sent on stdin, and return those bytes.
fn what_the_push_scan_sends(repo: &Path, head: &str) -> Vec<u8> {
    let stub_dir = tempfile::tempdir().unwrap();
    let sent: PathBuf = stub_dir.path().join("stdin.bin");
    let stub = stub_dir.path().join("mock");
    std::fs::write(
        &stub,
        format!("#!/usr/bin/env bash\ncat > {}\nexit 0\n", sent.display()),
    )
    .unwrap();
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut p = std::fs::metadata(&stub).unwrap().permissions();
        p.set_mode(0o755);
        std::fs::set_permissions(&stub, p).unwrap();
    }

    let script = format!(
        "#!/usr/bin/env bash\nset -u\nPREPUSH_STDIN=$(cat)\n{}",
        crate::bootstrap::message_prepush_scan_body()
    );
    let refs = format!("refs/heads/main {head} refs/heads/main {}", "0".repeat(40));
    let mut child = Command::new("bash")
        .arg("-c")
        .arg(&script)
        .current_dir(repo)
        .env("PATH", path_with(stub_dir.path()))
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .unwrap();
    std::io::Write::write_all(&mut child.stdin.take().unwrap(), refs.as_bytes()).unwrap();
    assert!(child.wait().unwrap().success(), "the stub launcher passes");
    std::fs::read(&sent).unwrap_or_default()
}

#[test]
fn the_push_scan_sends_each_commit_with_its_own_author_and_committer() {
    // Three commits whose two fields differ in each of the three ways that
    // matter: a person authored under a forge's committer, an agent authored
    // and committed, and an agent authored under a person's committer. Every
    // record has to carry its own pair, which a stream sharing one identity
    // across the batch would get wrong for two of the three.
    let repo = tempfile::tempdir().unwrap();
    let dir = repo.path();
    git_in(dir, &[], &["init", "-q", "-b", "main"]);
    let person = "Jane Doe <jane@example.com>";
    let forge = "GitHub <noreply@github.com>";
    let agent = "Claude <noreply@anthropic.com>";
    commit_as(dir, person, forge, "feat: by a person");
    commit_as(dir, agent, agent, "feat: by an agent");
    commit_as(dir, agent, person, "feat: by an agent under a person");
    let head = git_in(dir, &[], &["rev-parse", "HEAD"]);

    let sent = what_the_push_scan_sends(dir, &head);
    let text = String::from_utf8_lossy(&sent).into_owned();
    let recs = split_batch(&text, "<stdin>");
    assert_eq!(recs.len(), 3, "one record per commit. got: {text:?}");

    let by_subject = |subject: &str| {
        recs.iter()
            .find(|r| r.message.trim_end() == subject)
            .unwrap_or_else(|| panic!("no record for {subject:?} in {text:?}"))
    };
    let r = by_subject("feat: by a person");
    assert_eq!(r.author.as_deref(), Some(person));
    assert_eq!(r.committer.as_deref(), Some(forge));
    let r = by_subject("feat: by an agent");
    assert_eq!(r.author.as_deref(), Some(agent));
    assert_eq!(r.committer.as_deref(), Some(agent));
    let r = by_subject("feat: by an agent under a person");
    assert_eq!(r.author.as_deref(), Some(agent));
    assert_eq!(r.committer.as_deref(), Some(person));

    // And the label that names a rejected commit is still the hash and subject.
    assert!(
        recs.iter()
            .all(|r| r.origin.contains(" feat: by ") && !r.origin.contains('<')),
        "origins must stay `<hash> <subject>`. got: {:?}",
        recs.iter().map(|r| &r.origin).collect::<Vec<_>>()
    );
}
